export interface FamousPerson {
  name: string;
  day: number;
  month: number;
  year: number;
  tags: string[];
}

export const famousBirthdays: FamousPerson[] = [
  // Original List
  { name: 'Albert Einstein', day: 14, month: 3, year: 1879, tags: ['Scientist'] },
  { name: 'Marie Curie', day: 7, month: 11, year: 1867, tags: ['Scientist'] },
  { name: 'Leonardo da Vinci', day: 15, month: 4, year: 1452, tags: ['Artist', 'Inventor'] },
  { name: 'Isaac Newton', day: 4, month: 1, year: 1643, tags: ['Scientist'] },
  { name: 'Martin Luther King Jr.', day: 15, month: 1, year: 1929, tags: ['Activist'] },
  { name: 'William Shakespeare', day: 23, month: 4, year: 1564, tags: ['Writer', 'Playwright'] },
  { name: 'Nelson Mandela', day: 18, month: 7, year: 1918, tags: ['Heads of State', 'Activist', 'South Africa'] },
  { name: 'Mahatma Gandhi', day: 2, month: 10, year: 1869, tags: ['Activist', 'India'] },
  { name: 'Nikola Tesla', day: 10, month: 7, year: 1856, tags: ['Inventor', 'Scientist'] },
  { name: 'Ada Lovelace', day: 10, month: 12, year: 1815, tags: ['Scientist', 'Mathematician'] },
  { name: 'Stephen Hawking', day: 8, month: 1, year: 1942, tags: ['Scientist'] },
  { name: 'Galileo Galilei', day: 15, month: 2, year: 1564, tags: ['Scientist'] },
  { name: 'Frida Kahlo', day: 6, month: 7, year: 1907, tags: ['Artist'] },
  { name: 'Vincent van Gogh', day: 30, month: 3, year: 1853, tags: ['Artist'] },
  { name: 'Pablo Picasso', day: 25, month: 10, year: 1881, tags: ['Artist'] },
  { name: 'Wolfgang Amadeus Mozart', day: 27, month: 1, year: 1756, tags: ['Musician', 'Composer'] },
  { name: 'Ludwig van Beethoven', day: 17, month: 12, year: 1770, tags: ['Musician', 'Composer'] },
  { name: 'Cleopatra', day: 13, month: 1, year: -69, tags: ['Heads of State', 'Royalty'] },
  { name: 'Joan of Arc', day: 6, month: 1, year: 1412, tags: ['Historical Figure'] },
  { name: 'Rosa Parks', day: 4, month: 2, year: 1913, tags: ['Activist'] },
  { name: 'Charles Darwin', day: 12, month: 2, year: 1809, tags: ['Scientist'] },
  { name: 'Jane Austen', day: 16, month: 12, year: 1775, tags: ['Writer'] },
  { name: 'Emily Dickinson', day: 10, month: 12, year: 1830, tags: ['Writer', 'Poet'] },
  { name: 'Mark Twain', day: 30, month: 11, year: 1835, tags: ['Writer'] },
  { name: 'George Orwell', day: 25, month: 6, year: 1903, tags: ['Writer'] },
  { name: 'J.R.R. Tolkien', day: 3, month: 1, year: 1892, tags: ['Writer'] },
  { name: 'Virginia Woolf', day: 25, month: 1, year: 1882, tags: ['Writer'] },
  { name: 'Sigmund Freud', day: 6, month: 5, year: 1856, tags: ['Scientist', 'Psychology'] },
  { name: 'Carl Jung', day: 26, month: 7, year: 1875, tags: ['Scientist', 'Psychology'] },
  { name: 'Friedrich Nietzsche', day: 15, month: 10, year: 1844, tags: ['Philosopher'] },
  { name: 'Socrates', day: 4, month: 6, year: -470, tags: ['Philosopher'] },
  { name: 'Plato', day: 21, month: 5, year: -428, tags: ['Philosopher'] },
  { name: 'Aristotle', day: 20, month: 7, year: -384, tags: ['Philosopher'] },
  { name: 'Maya Angelou', day: 4, month: 4, year: 1928, tags: ['Writer', 'Poet', 'Activist'] },
  { name: 'James Baldwin', day: 2, month: 8, year: 1924, tags: ['Writer', 'Activist'] },
  { name: 'Toni Morrison', day: 18, month: 2, year: 1931, tags: ['Writer'] },
  { name: 'Langston Hughes', day: 1, month: 2, year: 1902, tags: ['Writer', 'Poet'] },
  { name: 'Zora Neale Hurston', day: 7, month: 1, year: 1891, tags: ['Writer'] },
  { name: 'Harriet Tubman', day: 1, month: 3, year: 1822, tags: ['Activist'] },
  { name: 'Sojourner Truth', day: 1, month: 1, year: 1797, tags: ['Activist'] },
  { name: 'Frederick Douglass', day: 14, month: 2, year: 1818, tags: ['Activist', 'Writer'] },
  { name: 'W.E.B. Du Bois', day: 23, month: 2, year: 1868, tags: ['Activist', 'Sociologist'] },
  { name: 'Malcolm X', day: 19, month: 5, year: 1925, tags: ['Activist'] },
  { name: 'Susan B. Anthony', day: 15, month: 2, year: 1820, tags: ['Activist'] },
  { name: 'Elizabeth Cady Stanton', day: 12, month: 11, year: 1815, tags: ['Activist'] },
  { name: 'Marie Antoinette', day: 2, month: 11, year: 1755, tags: ['Royalty'] },
  { name: 'Queen Elizabeth I', day: 7, month: 9, year: 1533, tags: ['Royalty', 'Heads of State'] },
  { name: 'Julius Caesar', day: 12, month: 7, year: -100, tags: ['Heads of State', 'Historical Figure'] },
  { name: 'Alexander the Great', day: 20, month: 7, year: -356, tags: ['Heads of State', 'Historical Figure'] },
  { name: 'Genghis Khan', day: 1, month: 1, year: 1162, tags: ['Heads of State', 'Historical Figure'] },
  { name: 'Winston Churchill', day: 30, month: 11, year: 1874, tags: ['Heads of State', 'Prime Minister', 'United Kingdom'] },
  { name: 'Franklin D. Roosevelt', day: 30, month: 1, year: 1882, tags: ['Heads of State', 'President', 'United States'] },
  { name: 'Abraham Lincoln', day: 12, month: 2, year: 1809, tags: ['Heads of State', 'President', 'United States'] },
  { name: 'George Washington', day: 22, month: 2, year: 1732, tags: ['Heads of State', 'President', 'United States'] },
  { name: 'Thomas Jefferson', day: 13, month: 4, year: 1743, tags: ['Heads of State', 'President', 'United States'] },
  { name: 'John F. Kennedy', day: 29, month: 5, year: 1917, tags: ['Heads of State', 'President', 'United States'] },
  { name: 'Marilyn Monroe', day: 1, month: 6, year: 1926, tags: ['Hollywood', 'Actor'] },
  { name: 'Audrey Hepburn', day: 4, month: 5, year: 1929, tags: ['Hollywood', 'Actor'] },
  { name: 'Grace Kelly', day: 12, month: 11, year: 1929, tags: ['Hollywood', 'Actor', 'Royalty'] },
  { name: 'Charlie Chaplin', day: 16, month: 4, year: 1889, tags: ['Hollywood', 'Actor', 'Director'] },
  { name: 'Alfred Hitchcock', day: 13, month: 8, year: 1899, tags: ['Hollywood', 'Director'] },
  { name: 'Stanley Kubrick', day: 26, month: 7, year: 1928, tags: ['Hollywood', 'Director'] },
  { name: 'Akira Kurosawa', day: 23, month: 3, year: 1910, tags: ['Hollywood', 'Director'] },
  { name: 'Elvis Presley', day: 8, month: 1, year: 1935, tags: ['Musician'] },
  { name: 'John Lennon', day: 9, month: 10, year: 1940, tags: ['Musician'] },
  { name: 'Paul McCartney', day: 18, month: 6, year: 1942, tags: ['Musician'] },
  { name: 'Jimi Hendrix', day: 27, month: 11, year: 1942, tags: ['Musician'] },
  { name: 'Bob Dylan', day: 24, month: 5, year: 1941, tags: ['Musician'] },
  { name: 'David Bowie', day: 8, month: 1, year: 1947, tags: ['Musician'] },
  { name: 'Freddie Mercury', day: 5, month: 9, year: 1946, tags: ['Musician'] },
  { name: 'Michael Jackson', day: 29, month: 8, year: 1958, tags: ['Musician'] },
  { name: 'Prince', day: 7, month: 6, year: 1958, tags: ['Musician'] },
  { name: 'Madonna', day: 16, month: 8, year: 1958, tags: ['Musician'] },
  { name: 'Beyoncé', day: 4, month: 9, year: 1981, tags: ['Musician'] },
  { name: 'Taylor Swift', day: 13, month: 12, year: 1989, tags: ['Musician'] },
  { name: 'Lady Gaga', day: 28, month: 3, year: 1986, tags: ['Musician', 'Actor'] },
  { name: 'Rihanna', day: 20, month: 2, year: 1988, tags: ['Musician', 'Business'] },
  { name: 'Oprah Winfrey', day: 29, month: 1, year: 1954, tags: ['Media', 'Business'] },
  { name: 'Bill Gates', day: 28, month: 10, year: 1955, tags: ['Business', 'Technology', 'Microsoft'] },
  { name: 'Steve Jobs', day: 24, month: 2, year: 1955, tags: ['Business', 'Technology', 'Apple'] },
  { name: 'Elon Musk', day: 28, month: 6, year: 1971, tags: ['Business', 'Technology', 'Tesla', 'SpaceX'] },
  { name: 'Jeff Bezos', day: 12, month: 1, year: 1964, tags: ['Business', 'Technology', 'Amazon'] },
  { name: 'Mark Zuckerberg', day: 14, month: 5, year: 1984, tags: ['Business', 'Technology', 'Facebook'] },
  { name: 'Serena Williams', day: 26, month: 9, year: 1981, tags: ['Sports', 'Tennis'] },
  { name: 'Venus Williams', day: 17, month: 6, year: 1980, tags: ['Sports', 'Tennis'] },
  { name: 'Michael Jordan', day: 17, month: 2, year: 1963, tags: ['Sports', 'Basketball'] },
  { name: 'LeBron James', day: 30, month: 12, year: 1984, tags: ['Sports', 'Basketball'] },
  { name: 'Kobe Bryant', day: 23, month: 8, year: 1978, tags: ['Sports', 'Basketball'] },
  { name: 'Muhammad Ali', day: 17, month: 1, year: 1942, tags: ['Sports', 'Boxing'] },
  { name: 'Simone Biles', day: 14, month: 3, year: 1997, tags: ['Sports', 'Gymnastics'] },
  // Heads of State
  { name: 'Abiy Ahmed', day: 15, month: 8, year: 1976, tags: ['Heads of State', 'Prime Minister', 'Ethiopia'] },
  { name: 'William Ruto', day: 21, month: 12, year: 1966, tags: ['Heads of State', 'President', 'Kenya'] },
  { name: 'Paul Kagame', day: 23, month: 10, year: 1957, tags: ['Heads of State', 'President', 'Rwanda'] },
  { name: 'Samia Suluhu Hassan', day: 27, month: 1, year: 1960, tags: ['Heads of State', 'President', 'Tanzania'] },
  { name: 'Yoweri Museveni', day: 15, month: 9, year: 1944, tags: ['Heads of State', 'President', 'Uganda'] },
  { name: 'Ismail Omar Guelleh', day: 27, month: 11, year: 1947, tags: ['Heads of State', 'President', 'Djibouti'] },
  { name: 'Isaias Afwerki', day: 2, month: 2, year: 1946, tags: ['Heads of State', 'President', 'Eritrea'] },
  { name: 'Hassan Sheikh Mohamud', day: 29, month: 11, year: 1955, tags: ['Heads of State', 'President', 'Somalia'] },
  { name: 'Salva Kiir Mayardit', day: 13, month: 9, year: 1951, tags: ['Heads of State', 'President', 'South Sudan'] },
  { name: 'Évariste Ndayishimiye', day: 17, month: 6, year: 1968, tags: ['Heads of State', 'President', 'Burundi'] },
  { name: 'Lazarus Chakwera', day: 5, month: 4, year: 1955, tags: ['Heads of State', 'President', 'Malawi'] },
  { name: 'Hakainde Hichilema', day: 4, month: 6, year: 1962, tags: ['Heads of State', 'President', 'Zambia'] },
  { name: 'Filipe Nyusi', day: 9, month: 2, year: 1959, tags: ['Heads of State', 'President', 'Mozambique'] },
  { name: 'Azali Assoumani', day: 1, month: 1, year: 1959, tags: ['Heads of State', 'President', 'Comoros'] },
  { name: 'Wavel Ramkalawan', day: 15, month: 3, year: 1961, tags: ['Heads of State', 'President', 'Seychelles'] },
  { name: 'José Maria Neves', day: 28, month: 3, year: 1960, tags: ['Heads of State', 'President', 'Cape Verde'] },
  { name: 'Carlos Vila Nova', day: 27, month: 10, year: 1965, tags: ['Heads of State', 'President', 'São Tomé and Príncipe'] },
  { name: 'Andry Rajoelina', day: 30, month: 5, year: 1974, tags: ['Heads of State', 'President', 'Madagascar'] },
  { name: 'Bola Tinubu', day: 29, month: 3, year: 1952, tags: ['Heads of State', 'President', 'Nigeria'] },
  { name: 'Nana Akufo-Addo', day: 29, month: 3, year: 1944, tags: ['Heads of State', 'President', 'Ghana'] },
  { name: 'Bassirou Diomaye Faye', day: 25, month: 3, year: 1980, tags: ['Heads of State', 'President', 'Senegal'] },
  { name: 'Alassane Ouattara', day: 1, month: 1, year: 1942, tags: ['Heads of State', 'President', 'Ivory Coast'] },
  { name: 'Adama Barrow', day: 15, month: 2, year: 1965, tags: ['Heads of State', 'President', 'Gambia'] },
  { name: 'Julius Maada Bio', day: 12, month: 5, year: 1964, tags: ['Heads of State', 'President', 'Sierra Leone'] },
  { name: 'Joseph Boakai', day: 30, month: 11, year: 1944, tags: ['Heads of State', 'President', 'Liberia'] },
  { name: 'Umaro Sissoco Embaló', day: 23, month: 9, year: 1972, tags: ['Heads of State', 'President', 'Guinea-Bissau'] },
  { name: 'Patrice Talon', day: 1, month: 5, year: 1958, tags: ['Heads of State', 'President', 'Benin'] },
  { name: 'Faure Gnassingbé', day: 6, month: 6, year: 1966, tags: ['Heads of State', 'President', 'Togo'] },
  { name: 'Ibrahim Traoré', day: 14, month: 3, year: 1988, tags: ['Heads of State', 'President', 'Burkina Faso'] },
  { name: 'Abdourahamane Tchiani', day: 1, month: 4, year: 1961, tags: ['Heads of State', 'President', 'Niger'] },
  { name: 'Mamady Doumbouya', day: 4, month: 3, year: 1980, tags: ['Heads of State', 'President', 'Guinea'] },
  { name: 'Mohamed Ould Ghazouani', day: 31, month: 12, year: 1956, tags: ['Heads of State', 'President', 'Mauritania'] },
  { name: 'Assimi Goïta', day: 11, month: 11, year: 1983, tags: ['Heads of State', 'President', 'Mali'] },
  { name: 'Abdel Fattah el-Sisi', day: 19, month: 11, year: 1954, tags: ['Heads of State', 'President', 'Egypt'] },
  { name: 'Kais Saied', day: 22, month: 2, year: 1958, tags: ['Heads of State', 'President', 'Tunisia'] },
  { name: 'Abdelmadjid Tebboune', day: 17, month: 11, year: 1945, tags: ['Heads of State', 'President', 'Algeria'] },
  { name: 'Mohammed VI', day: 21, month: 8, year: 1963, tags: ['Heads of State', 'Royalty', 'King', 'Morocco'] },
  { name: 'Mohamed al-Menfi', day: 3, month: 3, year: 1976, tags: ['Heads of State', 'Libya'] },
  { name: 'Abdel Fattah al-Burhan', day: 11, month: 7, year: 1960, tags: ['Heads of State', 'Sudan'] },
  { name: 'Emmerson Mnangagwa', day: 15, month: 9, year: 1942, tags: ['Heads of State', 'President', 'Zimbabwe'] },
  { name: 'Nangolo Mbumba', day: 15, month: 8, year: 1941, tags: ['Heads of State', 'President', 'Namibia'] },
  { name: 'Mokgweetsi Masisi', day: 21, month: 7, year: 1962, tags: ['Heads of State', 'President', 'Botswana'] },
  { name: 'Mswati III', day: 19, month: 4, year: 1968, tags: ['Heads of State', 'Royalty', 'King', 'Eswatini'] },
  { name: 'Letsie III', day: 17, month: 7, year: 1963, tags: ['Heads of State', 'Royalty', 'King', 'Lesotho'] },
  { name: 'Paul Biya', day: 13, month: 2, year: 1933, tags: ['Heads of State', 'President', 'Cameroon'] },
  { name: 'Mahamat Déby', day: 1, month: 1, year: 1984, tags: ['Heads of State', 'President', 'Chad'] },
  { name: 'Félix Tshisekedi', day: 13, month: 6, year: 1963, tags: ['Heads of State', 'President', 'DR Congo'] },
  { name: 'Denis Sassou Nguesso', day: 23, month: 11, year: 1943, tags: ['Heads of State', 'President', 'Republic of the Congo'] },
  { name: 'Teodoro Obiang Nguema Mbasogo', day: 5, month: 6, year: 1942, tags: ['Heads of State', 'President', 'Equatorial Guinea'] },
  { name: 'Brice Oligui Nguema', day: 3, month: 3, year: 1975, tags: ['Heads of State', 'President', 'Gabon'] },
  { name: 'Donald Trump', day: 14, month: 6, year: 1946, tags: ['Heads of State', 'President', 'United States'] },
  { name: 'Joe Biden', day: 20, month: 11, year: 1942, tags: ['Heads of State', 'President', 'United States'] },
  { name: 'Justin Trudeau', day: 25, month: 12, year: 1971, tags: ['Heads of State', 'Prime Minister', 'Canada'] },
  { name: 'Claudia Sheinbaum', day: 24, month: 6, year: 1962, tags: ['Heads of State', 'President', 'Mexico'] },
  { name: 'Nayib Bukele', day: 24, month: 7, year: 1981, tags: ['Heads of State', 'President', 'El Salvador'] },
  { name: 'Bernardo Arévalo', day: 7, month: 10, year: 1958, tags: ['Heads of State', 'President', 'Guatemala'] },
  { name: 'Xiomara Castro', day: 30, month: 9, year: 1959, tags: ['Heads of State', 'President', 'Honduras'] },
  { name: 'Rodrigo Chaves Robles', day: 10, month: 6, year: 1961, tags: ['Heads of State', 'President', 'Costa Rica'] },
  { name: 'José Raúl Mulino', day: 13, month: 6, year: 1959, tags: ['Heads of State', 'President', 'Panama'] },
  { name: 'Daniel Ortega', day: 11, month: 11, year: 1945, tags: ['Heads of State', 'President', 'Nicaragua'] },
  { name: 'Johnny Briceño', day: 17, month: 7, year: 1960, tags: ['Heads of State', 'Prime Minister', 'Belize'] },
  { name: 'Dickon Mitchell', day: 9, month: 2, year: 1977, tags: ['Heads of State', 'Prime Minister', 'Grenada'] },
  { name: 'Gaston Browne', day: 9, month: 2, year: 1967, tags: ['Heads of State', 'Prime Minister', 'Antigua and Barbuda'] },
  { name: 'Mia Mottley', day: 1, month: 10, year: 1965, tags: ['Heads of State', 'Prime Minister', 'Barbados'] },
  { name: 'Philip Davis', day: 7, month: 6, year: 1951, tags: ['Heads of State', 'Prime Minister', 'Bahamas'] },
  { name: 'Roosevelt Skerrit', day: 8, month: 6, year: 1972, tags: ['Heads of State', 'Prime Minister', 'Dominica'] },
  { name: 'Philip Pierre', day: 1, month: 10, year: 1954, tags: ['Heads of State', 'Prime Minister', 'Saint Lucia'] },
  { name: 'Terrance Drew', day: 24, month: 2, year: 1968, tags: ['Heads of State', 'Prime Minister', 'Saint Kitts and Nevis'] },
  { name: 'Keith Rowley', day: 24, month: 10, year: 1949, tags: ['Heads of State', 'Prime Minister', 'Trinidad and Tobago'] },
  { name: 'Ralph Gonsalves', day: 8, month: 8, year: 1946, tags: ['Heads of State', 'Prime Minister', 'Saint Vincent and the Grenadines'] },
  { name: 'Andrew Holness', day: 22, month: 7, year: 1972, tags: ['Heads of State', 'Prime Minister', 'Jamaica'] },
  { name: 'Garry Conille', day: 26, month: 2, year: 1966, tags: ['Heads of State', 'Prime Minister', 'Haiti'] },
  { name: 'Luis Abinader', day: 12, month: 7, year: 1967, tags: ['Heads of State', 'President', 'Dominican Republic'] },
  { name: 'Miguel Díaz-Canel', day: 20, month: 4, year: 1960, tags: ['Heads of State', 'President', 'Cuba'] },
  { name: 'Luiz Inácio Lula da Silva', day: 27, month: 10, year: 1945, tags: ['Heads of State', 'President', 'Brazil'] },
  { name: 'Javier Gerardo Milei', day: 22, month: 10, year: 1970, tags: ['Heads of State', 'President', 'Argentina'] },
  { name: 'Gabriel Boric', day: 11, month: 2, year: 1986, tags: ['Heads of State', 'President', 'Chile'] },
  { name: 'Gustavo Petro', day: 19, month: 4, year: 1960, tags: ['Heads of State', 'President', 'Colombia'] },
  { name: 'Nicolás Maduro', day: 23, month: 11, year: 1962, tags: ['Heads of State', 'President', 'Venezuela'] },
  { name: 'Daniel Noboa', day: 30, month: 11, year: 1987, tags: ['Heads of State', 'President', 'Ecuador'] },
  { name: 'Dina Boluarte', day: 31, month: 5, year: 1962, tags: ['Heads of State', 'President', 'Peru'] },
  { name: 'Luis Lacalle Pou', day: 11, month: 8, year: 1973, tags: ['Heads of State', 'President', 'Uruguay'] },
  { name: 'Santiago Peña', day: 16, month: 11, year: 1978, tags: ['Heads of State', 'President', 'Paraguay'] },
  { name: 'Luis Arce', day: 28, month: 9, year: 1963, tags: ['Heads of State', 'President', 'Bolivia'] },
  { name: 'Irfaan Ali', day: 25, month: 4, year: 1980, tags: ['Heads of State', 'President', 'Guyana'] },
  { name: 'Chan Santokhi', day: 3, month: 2, year: 1959, tags: ['Heads of State', 'President', 'Suriname'] },
  { name: 'Xi Jinping', day: 15, month: 6, year: 1953, tags: ['Heads of State', 'President', 'China'] },
  { name: 'Fumio Kishida', day: 29, month: 7, year: 1957, tags: ['Heads of State', 'Prime Minister', 'Japan'] },
  { name: 'Yoon Suk-yeol', day: 18, month: 12, year: 1960, tags: ['Heads of State', 'President', 'South Korea'] },
  { name: 'Kim Jong-un', day: 8, month: 1, year: 1983, tags: ['Heads of State', 'Supreme Leader', 'North Korea'] },
  { name: 'Lai Ching-te', day: 6, month: 10, year: 1959, tags: ['Heads of State', 'President', 'Taiwan'] },
  { name: 'John Lee', day: 7, month: 12, year: 1957, tags: ['Heads of State', 'Chief Executive', 'Hong Kong'] },
  { name: 'Ukhnaagiin Khürelsükh', day: 14, month: 6, year: 1968, tags: ['Heads of State', 'President', 'Mongolia'] },
  { name: 'Prabowo Subianto', day: 17, month: 10, year: 1951, tags: ['Heads of State', 'President', 'Indonesia'] },
  { name: 'Ferdinand Marcos Jr.', day: 13, month: 9, year: 1957, tags: ['Heads of State', 'President', 'Philippines'] },
  { name: 'Tô Lâm', day: 10, month: 7, year: 1957, tags: ['Heads of State', 'President', 'Vietnam'] },
  { name: 'Thongloun Sisoulith', day: 10, month: 11, year: 1945, tags: ['Heads of State', 'President', 'Laos'] },
  { name: 'Hun Manet', day: 20, month: 10, year: 1977, tags: ['Heads of State', 'Prime Minister', 'Cambodia'] },
  { name: 'Paetongtarn Shinawatra', day: 21, month: 8, year: 1986, tags: ['Heads of State', 'Prime Minister', 'Thailand'] },
  { name: 'Lawrence Wong', day: 18, month: 12, year: 1972, tags: ['Heads of State', 'Prime Minister', 'Singapore'] },
  { name: 'Hassanal Bolkiah', day: 15, month: 7, year: 1946, tags: ['Heads of State', 'Sultan', 'Royalty', 'Brunei'] },
  { name: 'Anwar Ibrahim', day: 10, month: 8, year: 1947, tags: ['Heads of State', 'Prime Minister', 'Malaysia'] },
  { name: 'José Ramos-Horta', day: 26, month: 12, year: 1949, tags: ['Heads of State', 'President', 'Timor-Leste'] },
  { name: 'Min Aung Hlaing', day: 3, month: 7, year: 1956, tags: ['Heads of State', 'Military Leader', 'Myanmar'] },
  { name: 'Narendra Modi', day: 17, month: 9, year: 1950, tags: ['Heads of State', 'Prime Minister', 'India'] },
  { name: 'Shehbaz Sharif', day: 23, month: 9, year: 1951, tags: ['Heads of State', 'Prime Minister', 'Pakistan'] },
  { name: 'Sheikh Hasina', day: 28, month: 9, year: 1947, tags: ['Heads of State', 'Prime Minister', 'Bangladesh'] },
  { name: 'Anura Kumara Dissanayake', day: 24, month: 11, year: 1968, tags: ['Heads of State', 'President', 'Sri Lanka'] },
  { name: 'Jigme Khesar Namgyel Wangchuck', day: 21, month: 2, year: 1980, tags: ['Heads of State', 'Royalty', 'King', 'Bhutan'] },
  { name: 'Pushpa Kamal Dahal', day: 11, month: 12, year: 1954, tags: ['Heads of State', 'Prime Minister', 'Nepal'] },
  { name: 'Mohamed Muizzu', day: 15, month: 6, year: 1978, tags: ['Heads of State', 'President', 'Maldives'] },
  { name: 'Kassym-Jomart Tokayev', day: 17, month: 5, year: 1953, tags: ['Heads of State', 'President', 'Kazakhstan'] },
  { name: 'Shavkat Mirziyoyev', day: 24, month: 7, year: 1957, tags: ['Heads of State', 'President', 'Uzbekistan'] },
  { name: 'Serdar Berdimuhamedow', day: 22, month: 9, year: 1981, tags: ['Heads of State', 'President', 'Turkmenistan'] },
  { name: 'Sadyr Japarov', day: 6, month: 12, year: 1968, tags: ['Heads of State', 'President', 'Kyrgyzstan'] },
  { name: 'Emomali Rahmon', day: 5, month: 10, year: 1952, tags: ['Heads of State', 'President', 'Tajikistan'] },
  { name: 'Emmanuel Macron', day: 21, month: 12, year: 1977, tags: ['Heads of State', 'President', 'France'] },
  { name: 'Friedrich Merz', day: 11, month: 11, year: 1955, tags: ['Heads of State', 'Chancellor', 'Germany'] },
  { name: 'Keir Starmer', day: 2, month: 9, year: 1962, tags: ['Heads of State', 'Prime Minister', 'United Kingdom', 'Opposition Leader'] },
  { name: 'Pedro Sánchez', day: 29, month: 2, year: 1972, tags: ['Heads of State', 'Prime Minister', 'Spain'] },
  { name: 'Luís Montenegro', day: 16, month: 2, year: 1973, tags: ['Heads of State', 'Prime Minister', 'Portugal'] },
  { name: 'Karl Nehammer', day: 18, month: 10, year: 1972, tags: ['Heads of State', 'Chancellor', 'Austria'] },
  { name: 'Viola Amherd', day: 7, month: 6, year: 1962, tags: ['Heads of State', 'President', 'Switzerland'] },
  { name: 'Luc Frieden', day: 16, month: 9, year: 1963, tags: ['Heads of State', 'Prime Minister', 'Luxembourg'] },
  { name: 'Alexander De Croo', day: 3, month: 11, year: 1975, tags: ['Heads of State', 'Prime Minister', 'Belgium'] },
  { name: 'Dick Schoof', day: 8, month: 3, year: 1957, tags: ['Heads of State', 'Prime Minister', 'Netherlands'] },
  { name: 'Mette Frederiksen', day: 19, month: 11, year: 1977, tags: ['Heads of State', 'Prime Minister', 'Denmark'] },
  { name: 'Ulf Kristersson', day: 29, month: 12, year: 1963, tags: ['Heads of State', 'Prime Minister', 'Sweden'] },
  { name: 'Jonas Gahr Støre', day: 25, month: 8, year: 1960, tags: ['Heads of State', 'Prime Minister', 'Norway'] },
  { name: 'Petteri Orpo', day: 3, month: 11, year: 1969, tags: ['Heads of State', 'Prime Minister', 'Finland'] },
  { name: 'Halla Tómasdóttir', day: 11, month: 10, year: 1968, tags: ['Heads of State', 'President', 'Iceland'] },
  { name: 'Kaja Kallas', day: 18, month: 6, year: 1977, tags: ['Heads of State', 'Prime Minister', 'Estonia'] },
  { name: 'Gitanas Nausėda', day: 19, month: 5, year: 1964, tags: ['Heads of State', 'President', 'Lithuania'] },
  { name: 'Evika Siliņa', day: 3, month: 8, year: 1975, tags: ['Heads of State', 'Prime Minister', 'Latvia'] },
  { name: 'Vladimir Putin', day: 7, month: 10, year: 1952, tags: ['Heads of State', 'President', 'Russia'] },
  { name: 'Volodymyr Zelenskyy', day: 25, month: 1, year: 1978, tags: ['Heads of State', 'President', 'Ukraine'] },
  { name: 'Andrzej Duda', day: 16, month: 5, year: 1972, tags: ['Heads of State', 'President', 'Poland'] },
  { name: 'Viktor Orbán', day: 31, month: 5, year: 1963, tags: ['Heads of State', 'Prime Minister', 'Hungary'] },
  { name: 'Petr Pavel', day: 1, month: 11, year: 1961, tags: ['Heads of State', 'President', 'Czech Republic'] },
  { name: 'Peter Pellegrini', day: 6, month: 10, year: 1975, tags: ['Heads of State', 'President', 'Slovakia'] },
  { name: 'Klaus Iohannis', day: 13, month: 6, year: 1959, tags: ['Heads of State', 'President', 'Romania'] },
  { name: 'Rumen Radev', day: 18, month: 6, year: 1963, tags: ['Heads of State', 'President', 'Bulgaria'] },
  { name: 'Robert Golob', day: 23, month: 1, year: 1967, tags: ['Heads of State', 'Prime Minister', 'Slovenia'] },
  { name: 'Andrej Plenković', day: 8, month: 4, year: 1970, tags: ['Heads of State', 'Prime Minister', 'Croatia'] },
  { name: 'Milorad Dodik', day: 12, month: 3, year: 1959, tags: ['Heads of State', 'President', 'Bosnia and Herzegovina'] },
  { name: 'Jakov Milatović', day: 7, month: 12, year: 1986, tags: ['Heads of State', 'President', 'Montenegro'] },
  { name: 'Vjosa Osmani', day: 17, month: 5, year: 1982, tags: ['Heads of State', 'President', 'Kosovo'] },
  { name: 'Hristijan Mickoski', day: 29, month: 9, year: 1977, tags: ['Heads of State', 'Prime Minister', 'North Macedonia'] },
  { name: 'Edi Rama', day: 4, month: 7, year: 1964, tags: ['Heads of State', 'Prime Minister', 'Albania'] },
  { name: 'Alexander Lukashenko', day: 30, month: 8, year: 1954, tags: ['Heads of State', 'President', 'Belarus'] },
  { name: 'Aleksandar Vučić', day: 5, month: 3, year: 1970, tags: ['Heads of State', 'President', 'Serbia'] },
  { name: 'Giorgia Meloni', day: 15, month: 1, year: 1977, tags: ['Heads of State', 'Prime Minister', 'Italy'] },
  { name: 'Kyriakos Mitsotakis', day: 4, month: 3, year: 1968, tags: ['Heads of State', 'Prime Minister', 'Greece'] },
  { name: 'Nikos Christodoulides', day: 6, month: 12, year: 1973, tags: ['Heads of State', 'President', 'Cyprus'] },
  { name: 'Pope Francis', day: 17, month: 12, year: 1936, tags: ['Heads of State', 'Royalty', 'Pope', 'Vatican City'] },
  { name: 'Albert II', day: 14, month: 3, year: 1958, tags: ['Heads of State', 'Royalty', 'Prince', 'Monaco'] },
  { name: 'Robert Abela', day: 7, month: 12, year: 1977, tags: ['Heads of State', 'Prime Minister', 'Malta'] },
  { name: 'Recep Tayyip Erdoğan', day: 26, month: 2, year: 1954, tags: ['Heads of State', 'President', 'Turkey'] },
  { name: 'Benjamin Netanyahu', day: 21, month: 10, year: 1949, tags: ['Heads of State', 'Prime Minister', 'Israel'] },
  { name: 'Bashar al-Assad', day: 11, month: 9, year: 1965, tags: ['Heads of State', 'President', 'Syria'] },
  { name: 'Salman bin Abdulaziz Al Saud', day: 31, month: 12, year: 1935, tags: ['Heads of State', 'Royalty', 'King', 'Saudi Arabia'] },
  { name: 'Masoud Pezeshkian', day: 29, month: 9, year: 1954, tags: ['Heads of State', 'President', 'Iran'] },
  { name: 'Abdullah II', day: 30, month: 1, year: 1962, tags: ['Heads of State', 'Royalty', 'King', 'Jordan'] },
  { name: 'Tamim bin Hamad Al Thani', day: 3, month: 6, year: 1980, tags: ['Heads of State', 'Royalty', 'Emir', 'Qatar'] },
  { name: 'Haitham bin Tariq', day: 11, month: 10, year: 1954, tags: ['Heads of State', 'Royalty', 'Sultan', 'Oman'] },
  { name: 'Hamad bin Isa Al Khalifa', day: 28, month: 1, year: 1950, tags: ['Heads of State', 'Royalty', 'King', 'Bahrain'] },
  { name: 'Mohammed bin Zayed Al Nahyan', day: 11, month: 3, year: 1961, tags: ['Heads of State', 'President', 'UAE'] },
  { name: 'Najib Mikati', day: 24, month: 11, year: 1955, tags: ['Heads of State', 'Prime Minister', 'Lebanon'] },
  { name: 'Mahmoud Abbas', day: 15, month: 11, year: 1935, tags: ['Heads of State', 'President', 'Palestine'] },
  { name: 'Mishal Al-Ahmad Al-Jaber Al-Sabah', day: 27, month: 9, year: 1940, tags: ['Heads of State', 'Royalty', 'Emir', 'Kuwait'] },
  { name: 'Anthony Albanese', day: 2, month: 3, year: 1963, tags: ['Heads of State', 'Prime Minister', 'Australia'] },
  { name: 'Christopher Luxon', day: 19, month: 7, year: 1970, tags: ['Heads of State', 'Prime Minister', 'New Zealand'] },
  { name: 'Sitiveni Rabuka', day: 13, month: 9, year: 1948, tags: ['Heads of State', 'Prime Minister', 'Fiji'] },
  { name: 'Charlot Salwai', day: 24, month: 4, year: 1963, tags: ['Heads of State', 'Prime Minister', 'Vanuatu'] },
  { name: 'Surangel Whipps Jr.', day: 29, month: 3, year: 1968, tags: ['Heads of State', 'President', 'Palau'] },
  { name: 'David Kabua', day: 8, month: 11, year: 1951, tags: ['Heads of State', 'President', 'Marshall Islands'] },
  { name: 'Lionel Aingimea', day: 28, month: 6, year: 1976, tags: ['Heads of State', 'President', 'Nauru'] },
  { name: 'Taneti Maamau', day: 16, month: 9, year: 1960, tags: ['Heads of State', 'President', 'Kiribati'] },
  { name: 'Feleti Teo', day: 9, month: 2, year: 1959, tags: ['Heads of State', 'Prime Minister', 'Tuvalu'] },
  { name: 'Fiamē Naomi Mataʻafa', day: 29, month: 4, year: 1957, tags: ['Heads of State', 'Prime Minister', 'Samoa'] },
  { name: 'Moetai Brotherson', day: 30, month: 7, year: 1969, tags: ['Heads of State', 'President', 'French Polynesia'] },
  { name: 'James Marape', day: 24, month: 4, year: 1971, tags: ['Heads of State', 'Prime Minister', 'Papua New Guinea'] },
  // Opposition Leaders
  { name: 'Alexei Navalny', day: 4, month: 6, year: 1976, tags: ['Opposition Leader', 'Russia'] },
  { name: 'Bobi Wine', day: 12, month: 2, year: 1982, tags: ['Opposition Leader', 'Uganda', 'Musician'] },
  { name: 'Nelson Chamisa', day: 2, month: 2, year: 1978, tags: ['Opposition Leader', 'Zimbabwe'] },
  { name: 'Kizza Besigye', day: 22, month: 4, year: 1956, tags: ['Opposition Leader', 'Uganda'] },
  { name: 'Sviatlana Tsikhanouskaya', day: 11, month: 9, year: 1982, tags: ['Opposition Leader', 'Belarus'] },
  { name: 'Hamdeen Sabahi', day: 5, month: 7, year: 1954, tags: ['Opposition Leader', 'Egypt'] },
  { name: 'Julius Malema', day: 3, month: 3, year: 1981, tags: ['Opposition Leader', 'South Africa'] },
  { name: 'Mmusi Maimane', day: 6, month: 6, year: 1980, tags: ['Opposition Leader', 'South Africa'] },
  { name: 'Raila Odinga', day: 7, month: 1, year: 1945, tags: ['Opposition Leader', 'Kenya'] },
  { name: 'Kalonzo Musyoka', day: 24, month: 12, year: 1953, tags: ['Opposition Leader', 'Kenya'] },
  { name: 'Musalia Mudavadi', day: 21, month: 9, year: 1960, tags: ['Opposition Leader', 'Kenya'] },
  { name: 'Aminata Touré', day: 12, month: 10, year: 1962, tags: ['Opposition Leader', 'Senegal'] },
  { name: 'Khalifa Sall', day: 1, month: 1, year: 1956, tags: ['Opposition Leader', 'Senegal'] },
  { name: 'Jean Ping', day: 24, month: 11, year: 1942, tags: ['Opposition Leader', 'Gabon'] },
  { name: 'Léon Mba', day: 9, month: 2, year: 1902, tags: ['Opposition Leader', 'Gabon'] },
  { name: 'Jean-Hilaire Aubame', day: 10, month: 11, year: 1912, tags: ['Opposition Leader', 'Gabon'] },
  { name: 'Louis-Gaston Mayila', day: 5, month: 12, year: 1947, tags: ['Opposition Leader', 'Gabon'] }
];
