
export const zodiac_data = {
    "Rat": {
        "general": `Illustrious Rat, you are a lucky one indeed. In China, your sign is very highly prized (and not just for supper). You are power-hungry and know how to 'go for it.' Once you get your claws firmly around an honored position, you hold on for dear life. Leadership becomes you. You are fun-loving and sociable, but your private self is often fidgety and nervous. You feel a need to talk problems through, as getting anxiety off your chest is as good as putting it out of your mind.

Some may accuse you of being too communicative; let's just say you talk a lot. You are not a willing idler. You are quick-witted. You speed through work so you can have plenty of time left to meddle in what others are up to. When dealing in delicate matters, you instinctively know how to keep your whiskers clean. Yet, you are not a born straight arrow. You would always rather zigzag your way to fame and fortune than trot the straight and narrow path.

You have a tendency to be picky… and paradoxical. You are an odd mix of being a big spender and being thrifty, saving everything from worn-out rubber bands to frayed shirt collars, just in case. Then, you will go out spending like a bandit on some extortionately costly bauble that you deem essential to your well-being.

You charm others into doing what you want. Winning friends and seducing lovers is child's play for you. Still, you are not seen as promiscuous: you are the marrying kind and you require a family.

Why not run out and win yourself a flamboyant Dragon, a conscientious Ox, or a trickier-than-thou Monkey as a mate? You should steer clear of Cats (Rabbits) and Horses. Your youth is a jolly time, energetic Rat, but your midlife can bring a downfall due to errors of judgment in love or business matters. If you are willing to seek counsel from friends, your golden years should prove to be comfortable and cloudless. My advice to you? Stop fretting. You will never starve, for love or for money. Crafty go-getters like you rarely do.`,
        "elements": {
            "Wood": `The Wood element settles a healthy coating of balm on your zigzag nervousness. Unlike other Rats, you know how to relax and take things as they come. Your temperament is cooler than that of other Rats, but as if to camouflage your native standoffishness, as a gregarious Wood Rat you exhibit more amiable charm and extroversion. While most Rats worry about their image and care immensely about how others feel towards them, you, the Wood Rat, seem to possess a more solid sense of your position in society. This added security allows you to demonstrate a carefree, open attitude and gives your personality an edge of merriment and devil-may-care that others find enchanting. You are jocular and even a bit light-headed when serious issues are in the offing. Wood gives you a special talent for discerning both the beauty and the worth of art objects. Add this to your powerful business acumen, and you may make a killing in antiques or become a respected art dealer. Or you may become an author of important literary works, a painter of no little renown, or a world-class musician. You are inspired by your environment and sensitive to every nuance of aesthetic input that comes your way. Ever conscious of your need to belong to a social group, you wear your ironclad principles on your sleeve. You are forever making pronouncements about what you will and will not tolerate in your life and the lives of those you love. You worry incessantly about your offspring and their progeny and would probably commit a crime to protect them from earning a bad reputation. As a Wood Rat, you have a giant ego. You need approval, applause, and encouragement almost more than you need food. Part of your open-door policy and seeming willingness to be flexible comes from your desire to be accepted by those to whom you extend your hospitality. If you are left on your own to fend for yourself without moral support, others will reap nothing but your complaints and hard-luck stories. You hate to be alone and feel justified in blaming everyone who doesn't give you what you need. You are usually successful at what you undertake, knowing your limitations and intelligently aiming only as high as you know you can go. You are, however, socially frustrated. People outwardly like you, are willing to chat and hang out with you, but you often feel slighted and have few real friends. Although you give them every opportunity, people don't confide in you easily. They may fear your sharp critical tongue, or perhaps it is a lack of compassion on your part. Either way, you feel left out. Take this to heart: love those you befriend for their hearts and not for what you think you can get out of their networks. Always look for qualities of soul in those you love, and you will be rewarded with unconditional friendship and steady loyalty.`,
            "Fire": `You, the Fire Rat, are the apotheosis of all Rats. As a high-strung talker, you are fashioned of raw energy, laced with a giant injection of nerves and overlaid with a serious case of the jitters. No slouches need apply if they wish to be with you. You, a Fire Rat, will gnaw your way through game-players, false friends, snobs, and charlatans. You want truth, beauty, and justice—or else! In appearance, you are a concentration of your busy-bee Rat brothers and sisters. You are like them in every way: outwardly calm, inwardly nerve-racked, protective, generous, greedy, charming, eloquent, persuasive, and tough—except that you are more completely immersed in being yourself than in being the person who pleases and cares for others. This characteristic, which some consider arch selfishness, sets you apart from the Rat who settles down and raises a family. Fire Rats like you want to build something wonderful you can irretrievably call your own. You make passionate lovers and are swashbuckling pursuers of the romantic life. You gorge on passion and never stop nibbling on the bones of love. You are also a brilliant intellectual. Not only do you win all the glittering academic prizes, you are endowed with lightning-quick perception. You can throw action into a passing thought before competitors have even noticed the thought was there. As all success comes early and relatively easily to you, you are impatient with rejection, heartbreak, and obstacles. When confronted with a major disappointment, you may find it hard to concentrate and will bolt to where the grass looks a shade greener. You fear loneliness worse than death. You are impulsive and always searching for a new experience to distract and excite you. Whether as a palliative to frustration or in answer to a whim, you dive in headfirst, gobbling your way through the new situation, relationship or job, eventually discovering that you have spread yourself too thin. You may have acquired three ex-wives, as many families, four lovers, several careers, and a dozen hobbies. Then, it’s too late. You are caught in your own rattrap.`,
            "Earth": `You are the grounded, no-nonsense Rat who gets to the top cleverly and fast. You seem to have known your goal from the day you were born, worked diligently to get the position you have always coveted and, by the age of forty, you are there, sitting pretty and whistling a happy tune. Something about you, the Earth Rat, tells people straight away that you can deal sensibly with anything life places before you. You are strong-minded and demanding, always expressing your own priorities first, yet being unafraid to make concessions and negotiate where you cannot win. You are steadier than other Rats, more desirous of keeping the peace. Your willpower is enormous: you can chomp through resistant detractors or inhuman workloads and come out fresh and ready for more. Unlike most other Rats, you maintain your calm in the face of emotional turmoil. Your philosophical view helps you to see through panic so as not to get scorched in the heat of the moment as other Rats so often do. As an Earth Rat, you are a plodder. You get up at a reasonable hour, follow a disciplined routine, and approach work and play with a measured, sensible intelligence. The rapaciousness of most Rats is absent; you are solidly trustworthy and remarkably soft-spoken. You may have unshakeable opinions and are a persuasive talker, but you don't feel obliged to force your ideals on others. You are a congenial person. You love to eat and need to be surrounded. Throwing parties or small social gatherings is a major talent: you know instinctively how to match up compatible guests at a dining table. Despite your conviviality, you will not often be found attending smart catered affairs in expensive restaurants; you feel more at home during cozy family receptions where your superior position as host is never in question. Take an Earth Rat like yourself out of your hospitable home environment, and you will discover that in daily life or business you are rather smug and self-satisfied. As you have always struggled hard to get where you are, you have a marked tendency to judge others as less industrious or eager to succeed, dubbing them layabouts and ne'er-do-wells without just cause.`,
            "Metal": `While other Rats have their strengths, your street-wise instincts are more fully developed. You are the great persuader, who will stop at nothing to produce the outcome you seek. When embarking on an eloquent chat-up session, as a wily Metal Rat, you tirelessly seduce, cajole, and caress your object until your goal is in sight and you can feel certain you've made your point. You take achievement and “getting there” almost too seriously. You are not in a hurry and never leap before you look at your landing pad a hundred times. You think things through, picking over each detail as you go along. You are a ponderer and a troubleshooter too. Though you may absorb information slowly, you pick up hostility and grudges, registering pain and rage on your inner radar screen like quicksilver. Any profession where hunches and extrasensory perception are useful will be a perfect vehicle for your sensitive soul's special talents. You might choose psychiatry, education, astrology, the police force, detective work, research, or social work. Such vivid perspicacity as you have may, however, backfire. You see so clearly the flaws in someone else that you quickly become judgmental. These extra lucid evaluations can take some of the pleasure from your life, tearing away illusion and youthful idealism. Some Metal Rats become pessimistic, possessive, and materialistic, even paranoid about the way others treat them. Being so alert to others' mistakes makes you edgy, and you are given to fits of brooding and pure pessimism. If you don't take steps in early adulthood to develop your objectivity and hone your social skills, by middle age, you may develop into a jaded cynic to whom social acceptance is difficult to find. Meticulous by nature, you detest anything slapdash or halfhearted. You think yourself businesslike and try to behave soberly when dealing with your fellows. You are economical and criticize those you see as wasteful or spendthrift. You dislike lukewarm sentiment and deplore halfway measures, which you consider both lazy and slipshod. You cannot bear people who lack enthusiasm - especially if they lack it for you and your pet projects. Curiously, though, as a sometimes curmudgeonly person, you are overtly hedonistic. You love food and eat plenty of it. You take love and marriage seriously, seeking pleasure in sex with gusto, dexterity, and skill.`,
            "Water": `Your aggressive Rat personality is pleasantly diluted with the influence of the Yin element, Water. For you, ambition and the race for success are second nature. Your first interest is to live a charmed life and move gracefully through its vicissitudes without emerging scarred and crippled. You, the Water Rat, are more feminine than many of your fellow Rats. You favor elegant clothes and fineries such as gold earrings, diamond clips, or rings - not often associated with hardier Rats. You are gifted for giving advice, for which people seek you out. Water Rats, especially women, love sweets. While you are unwilling to damage other important aspects of your health, you tend to binge on sugar, and a tendency to obesity in middle age is common among you. The remedy would be to cut down on sweets, eat greens, and replace meat with fish and grain dishes. Sugar not only fattens you but it also adversely affects the healthy function of your pancreas and your fragile nervous system. You have sound intuition and intellect: you grasp inner meanings and also know how to solve human problems almost before they arise. You are a great one for pulling rank, one-upping your adversaries quietly yet effectively, and beating enemies at their own game. Though not quite dangerous or cruel, you can destabilize the bravest of men by demonstrating your uncanny ability to see through opacity. Your dreams are clear visions and often premonitory. Heeding their messages may save your intimates much pain. This type of Rat is happy to live the comfortable bourgeois life. You are ambitious, yet you want to live in comfort, even luxury, and seem less driven to work as hard as others. Prizes, jobs, important positions, and even fame and fortune come your way without much effort. You are not born altruistic. Evolving in the rarefied atmosphere of your plush home and immediate surroundings, you sometimes forget that there are poorer, less fortunate souls than you. Instead of improving your sophisticated central heating system, you ought, perhaps, to look at the lives of those who are in need of a blanket, a cup of coffee, or even a pat on the head to keep going. Your politics often lean toward the conservative.`
        },
        "compatibilities": `Rat with Rat: A marriage guaranteed to enrich your lives. Both of you fear loneliness; each clings to the unit with tiny tough teeth and claws. You both know how to behave as a friend as well as a lover, taking a mate’s part in business ventures as well as helping them over rough patches. You shower each other with presents and solicitude, and you both appreciate kindness, understand each other's needs, and supply complete support. A few spiky moments may crop up. You both flirt—outrageously! One of you will be eyeing a comely dinner guest while the other plays footsie under the table with the guest’s hubby. Bitter accusations ensue. Early on, you should vow to discuss everything when it happens to avoid weeklong silences. Normally, the sex is fantastic. Both of you require masses of time together in bed and agree on adventurous sex. Rat bed games are enormously complicated—but harmless.

Rat with Ox: This union guarantees matrimonial stability. The Ox provides you with the grounding you lack, and you, the Rat, peek through the Ox’s wall of convention and resistance to change, pepping up a possibly dreary, plodding existence. This combination fits, each rounding out the other’s sharper edges. The Ox’s steadfastness provides you with the security you need. The devoted Ox will be happy to take on the role of provider, which allows you to act as family protector. You, the gregarious Rat, enjoy giving parties and attending social functions, which is all the better for the quiet Ox who would otherwise stay home ruminating. You are a perfect, alluring, and meticulous helpmate for an Ox in business.

Rat with Tiger: At first meeting, you two charm the pants off each other. You find the Tiger charming and would love to show them off, while the confident Tiger is amused by your vigorous chatter and lively sense of humor. But there is bound to be friction in the long run. The rambunctious, adventurous Tiger will forever be seeking excitement. You, being more domestic, will come to hate the sight of suitcases. The Tiger stalks instability, tempted by danger. Your mental stability depends greatly on material security, and with the Tiger always job-hopping, you will fret over money. To endure, you both must remember the initial reasons which drew you together. If you can recall how the Tiger roared attractively into your life, and the Tiger can continue to appreciate your powers of seduction, there is hope for an exciting, long-lived marriage.

Rat with Rabbit/Cat: This game of Cat and Mouse is one you should resist playing. Although both of you have some similar traits, you are not very compatible. Both have strong needs for a home, yet you disagree on just about everything. In conflict, you will forever elude each other, neither prepared to make concessions or take steps towards reconciliation. The Cat will be hissing and you will be sulking. This testy relationship grows pickier and pettier by the day. Sexually, you may be excited by sadomasochistic games, but in time such practices will lead to a sexually destructive relationship.

Rat with Dragon: This is an absolutely delicious marriage: the Chinese claim it as one of their best-arranged unions. As a restless Rat, you will be warmed by the heat of the dashing Dragon, and the Dragon will bask in your generous applause. These two will complement each other beautifully. Guaranteed bliss. With the strong-willed Dragon around, you will be happy to give up total control: anxieties slowly subside, bringing peace and comfort. The Dragon is so emotionally effusive that the burden of worry will be taken off your shoulders. You will not feel competitive about the Dragon’s position of strength in this couple, happy to stand in the shadows of a fervent friend/mate.

Rat with Snake: Although this alliance can often make for an interesting friendship, it is not recommended as a romantic relationship. You and the Snake may attract each other sexually, but ideally, your alliance should remain purely social. On an everyday level, your life together will be full of upheaval, disagreement, and disappointment. The Rat will grow uneasy and fearful of security. The Snake’s investments may not prove fruitful, and you will have to commandeer direction of the family accounts. Tempers will boil. The only moments of repose will be spent between the sheets. Be wary, gentle Rat, of your enchanting Snake. Snakes will reel you in with promises, love you to pieces, then swallow you whole for breakfast.

Rat with Horse: In China, even the corner grocer shudders at the mention of this unlikely pairing. The Horse is far too self-centered for your kindly, giving, dependent nature. Although initially attracted by your differences, you should not marry. Beyond a shared love of money, no common ground exists. You are likely to be mistreated by the haughty Horse, who is moody and individualistic, causing you to feel unstable. Ultimately, the Horse will not feel sufficiently challenged by you and may criticize and attack you for what they perceive as "weakness." The Horse’s impatience can lead to a search for pleasure elsewhere and subsequent merciless infidelity. A definite marital no-no.

Rat with Goat: This is a tricky one. The Goat enjoys your loving company but finds your nervousness unappealing. The Goat’s peaceful nature appeals to you, but their lack of interest in the menial tasks of everyday life will cause you to fret. The Goat's lackadaisical nature will strike you as rank laziness, and you will suffer anxiety about debt and fiscal responsibility. This household will be in a constant state of cold war. You will long for a partner with more oomph. Your mutual feelings of inadequacy will be put to rest when you have sex. The Goat is ultra-sensual and can exert an almost magical power over you. Thrilled by such intense sexual excitement, you (for once) will be happy to surrender power.

Rat with Monkey: If all else fails, you two can go on the road as a comedy duo. Humor, games, parties, and friends! What fun you’ll have! You are lucky to have been brought together. Your lives will be a never-ending roller-coaster ride. The amusing Monkey has you in perpetual stitches. The sometimes-repressed Rat will become a tiresome chatterbox alongside a mellow Monkey. But the Monkey never tires of the clever Rat. As neither is afraid of hard work, money comes easily to you. Should the Monkey betray the ever-devoted Rat, the relationship will become strained, but terminal dissension is rare. Mostly, this gleeful couple lives in an amusement park of joy.

Rat with Rooster: You and the Rooster incessantly peck away at each other. You are equally jealous and possessive, as well as anxious about your combined future. You both want freedom from burdensome responsibility and are forever arguing over money. A racy Rat with an active social calendar turns a possessive Rooster green. Crushed by your frequent absences, the Rooster grows insecure and looks for new ways to imprison you. Using sex as a weapon, you each deprive the other when you quarrel. The union is shaky, at best.

Rat with Dog: This is a potentially happy marriage. Providing the cards are played fairly, you and the Dog can be more than satisfied in each other’s company. Be prepared for long, heated discussions sorting out political, social, and financial differences of opinion. As a materialistic Rat, you can find it difficult to reason with a generous Dog. Disagreements abound. But as each half of this couple feels deeply passionate about the other, true harmony is possible. The Dog’s love is unconditional, offering a gentle cradle for your frenetic soul.

Rat with Pig: Indeed, you two make marvelous mates. In China, the Pig symbolizes affluence, which alone keeps a disquiet Rat from tooth-grinding. The practical Pig mellows your fretful nature and is lucky with money. You share a common love for food. The restive Rat, now safe in the peaceable Pig’s presence, finally lets go. Having a robust savings to depend on will make the jolly Rat jollier. The circumspect Rat’s counsel is welcome here. This gregarious and delightful couple is on every host’s A-list. Genuine love marks this union. The sensual Pig not only tickles your lusty erogenous zones, but emotional and financial security allow you to surrender fully in bed – where it counts!`,
        "futures": {
            2025: {"year": "Snake", "element": "Wood", "prediction": `This threatens to be a belt-tightening spell for you. Commerce slows in Snake years. You won’t go broke, but your income may diminish sufficiently to cause you a few sleepless nights. Put some cash away in a safe place. There is political unrest and global turbulence now, so get ready to hunker down and perhaps even shoulder new and different responsibilities. Your love life may cool somewhat during the months of June and July. The chill is but temporary, so don’t lose heart. Someone in your direct entourage will want to concoct a damaging rumor, and your private life may just be its subject.`},
            2026: {"year": "Horse", "element": "Fire", "prediction": `You and the Horse typically quarrel – over everything from how money is spent to how to raise geraniums. Despite the Horse’s odd attraction for you, as soon as you two strike up a relationship, the fight is on! Arguments can be productive, but in the case of Horse and Rat, perpetual spats take up much of your precious time and get neither of you anywhere positive. So rather than live this year in permanent tumult, try staying out of the limelight. Do not try to gain more power. The Horse hates to be dictated to, and you like to be the boss. As you can see, this year bodes disruptive chaos – unless of course you wisely choose to stay out of the spotlight.`},
            2027: {"year": "Goat", "element": "Fire", "prediction": `In the Goat year, you will be sailing in smoother waters. You have had a couple of lean seasons of late which may well have cramped your style and dulled your creativity. But this year promises to relieve all of the stress connected with economic slowdown for you. Money will cease to be the most crucial issue. By June, you will feel more like getting out and showing off your sparkling social skills. Of course, as soon as you stick out your furry little neck, someone gorgeous and lovable may latch onto it. This new romantic interest could threaten an already stable marriage or long-term relationship. Beware of putting the steady home life that you so desperately need in jeopardy. Be polite, but firm.`},
            2028: {"year": "Monkey", "element": "Earth", "prediction": `Here comes fun! You and the Monkey always hit it off. Monkeys are partial to surprises and excitement. They take kindly to movement and enjoy action for its own sake. But unlike you, Monkeys don’t really care about power. They are willing back-seat drivers who prefer to lurk in the wings solving problems. So in Monkey years, you are free to take charge again. Go after that seat on the board. Run for office. Try to become the president of the world. Ask for dominion and you shall most likely receive your wish. Be prepared to flatter a family member who is most decidedly not on your team; as they are sensitive to adulation and praise, go ahead and slather it on.`},
            2029: {"year": "Rooster", "element": "Earth", "prediction": `Don’t count on getting rich this year. The Rooster has a reputation for economizing in hard times. Do the best you can with what you have. That’s the Rooster’s message for Rats. Don’t overspend. Catch yourself before you indulge in what appear on the surface to be “bargains”. A bargain is only as useful as how much it subtracts from your budget. The good news is that this early in the year, you will be very close to falling in love. It may not be THE one, but it may be a “teaching affair” where you learn to accept that certain independent aspects of a loved one’s character will never mesh with your need to protect and “own” that person’s full attention.`},
            2030: {"year": "Dog", "element": "Metal", "prediction": `Money worries fly out the window for you this year. You can breathe more easily now and even splurge on one or two lavish parties or luxury holidays. Do however use your time wisely for a new endeavor. It may not be a business venture, but rather a charitable pursuit of some sort. Research well before you give. Sparks may fly in your love life in 2030. You tend to be inflexible on matters which are key to your mate’s emotional survival. Take all that they tell you more seriously than you have been. Be willing to discuss alternatives to the lifestyle you have previously been able to impose.`},
            2031: {"year": "Pig", "element": "Metal", "prediction": `This is a lucky year for you. The Pig approves of you and encourages all of your money-making and wealth-amassing schemes. You will, however, have to be more cautious about health issues. You probably have a chronic condition of some sort that you have been successfully ignoring for a while now. This will be the year to clear up those symptoms. Get thee to a medical professional before summer sets in. Whatever it is, you must take it very seriously in order not to allow the condition to worsen.`},
            2032: {"year": "Rat", "element": "Water", "prediction": `Your year at last! Here begins a whole new cycle of Chinese animal signs and, as usual, you are leading the pack. Life will seem easier. Bumps and lumps will even out. Watch out for a tendency to let down your guard. Romance will increase in intensity and want to become engagement. Commitment beckons. If you feel you have found “The One”, then tie the knot. Your main objective this year is to carefully plot the next dozen years of your life. Make major long-term decisions and don’t look back. Leap into new projects with your usual enthusiasm, but hold the reckless abandon.`},
            2033: {"year": "Ox", "element": "Water", "prediction": `Talk about hard labor! If you planned properly last year, then you already knew that this would be a year to put all others to shame in the work department. As things looked so rosy last year, you might have gotten out of the habit of pushing that rock up the hillside. In this new Ox year, you will need all the grit and determination you were born with to impress the Ox with your industriousness. Pay particular attention to details in contracts and verify all incoming bills, invoices, and even bank statements for slipups and errors in calculation.`},
            2034: {"year": "Tiger", "element": "Wood", "prediction": `The general climate of instability engendered by this Tigerish time is not your favorite. You are a security-seeker and you like to be in control. The tenuous atmosphere created in this changeable year promises to destabilize you. In Tiger years, nobody quite knows what’s around the next corner. So my advice to you is to roll with the punches. Don’t make waves. Keep a low profile, all the time managing to steer things your way. If you play your cards close to the vest, your Tiger year can turn out to be a giant success.`},
            2035: {"year": "Rabbit", "element": "Wood", "prediction": `You will be needing all of your wily skills this year because the Rabbit and you are traditionally at odds. Your jitteriness rubs the Rabbit’s fur the wrong way. This will be an excellent year for investment. Make it your business to do business, but keep your beady little eyes peeled for chicanery and theft. If you are not permanently attached, you could very well fall madly in love this year. If you do, then whisk your new heartthrob off to a desert isle where the two of you can daydream.`},
            2036: {"year": "Dragon", "element": "Fire", "prediction": `This will be another hectic but lucky year, a mirror of 2024. You will again be in high demand, networking and leading. It's a celebratory time where your skills at managing grand events will shine. Make the most of the Dragon's energy to further your ambitions, but remember to take moments for yourself to avoid burnout. It is guaranteed to be one of your memorable best.`}
        }
    },
    "Ox": {
        "general": `Hail, Diligent Ox. You are a veritable Gibraltar, an indomitable fortress. Your sign might have been called Bulldozer instead of Ox. You are an essentially temperate person who cares greatly for rigor, labor, strength of character, and... results!

You can stick at a task longer and go at it harder than anybody else. You spare no elbow grease. You hate to be beaten, so you simply never give up. Some may call you slow, while others complain that you are clumsy. In fact, you move at your own sweet pace and refuse to be pushed or prodded by hotheaded fly-by-nights. You believe in simplicity and achievement, and levity in business exasperates you.

You are capable of profound, enduring love, yet romance leaves you cold. You prefer action to beds of roses and vials of exotic perfumes. You take life very seriously, but life doesn't always return the favor. You don't normally talk much, but you have a remarkable talent for storytelling.

If it's really results you're after, use that special flair. Chat up the conservative Rooster you've been longing to invite to dinner, share some pink bubbly with a garrulous Rat, or send dozens of white roses to a luxury-loving Snake. They are all well equipped to handle your peculiar brand of seduction.

The first two eras of your life will be characterized by hard work. During your second adult phase, a misunderstanding between you and a neighbor or colleague may cause a deep, long-lasting rift.

Don't lose heart. Your old age will be both long and healthy, with peace of mind taking over after fifty as your priority number one. My advice? Yes. Lighten up. Stop judging others by your own high standards, as you'll only be disappointed. Nobody (except you, my dear Ox) is perfect.`,
        "elements": {
            "Wood": `You, the Wood Ox, are the heaviest-duty of the heavy-duty Oxen. The day that you are not working, studying, composing, or struggling to lift some monster weight, one may consider you dead. Even in death, you are not the type to slip gently away, leaving sweet memories of a romantic, lyrical spirit. When a person like you takes a dive, all the water whooshes out of the swimming pool, leaving a humongous, booming memory of your weighty, creative, and effective presence. You are not everybody's favorite nice guy. Au contraire! You are what some would call “a real piece of work,” a relentless fighter against all forces that you do not already control. In an effort to dominate, direct, gain superiority, and emerge as the controlling element in every undertaking, you, a dauntless, wily, brilliant, persevering person, let no obstacle discourage you. Your motto is “Progress Gratia Progress”—advancement for its own sake—and if you must walk over a few dead bodies along the route, well, you say, c'est la vie. Wood Oxen are tough customers. But, though specialists in the art of domination, you can be extremely generous. You love nature, children, and family, and revere those who know how to ply nature in return for its best bounty. Be they farmers, doctors, artists, or householders, you will always help out those you feel are doing a 'good job,' exerting all your strength and being successful.`,
            "Fire": `The most pleasant way to describe you is to warn that Fire affects the Ox in precisely the same way it affects dynamite, jet planes, and helium-filled dirigible balloons. Where there is already a surfeit of latent power, the Fire element leads to excess and sometimes even to disaster. Unlike other Oxen, you are impatient. Like them, you want to move ahead and get places, but you have more difficulty with the long view. While other Oxen are born planners, your long view is on backwards; you leap before you look. Like most Oxen, you assume that you are intrinsically superior. You feel you are better and more deserving of success, money, and whatever else you see, want, and take. To the adorable Oxen cocktail of self-assurance and strength of will, you add an endearing new characteristic called: moral self-righteousness. You fear nothing—even ridicule—and will forge ahead brandishing slogans as though married to your moral exhortations, proselytizing speeches, and “enlightened” schemes until death do you part. It can be a terrible bore. It can even be self-destructive. But you will carry on, a firebrand waving, wearing your moral indignation on your sleeve, and often losing the respect due you from your peers. The flipside is that you are often a genius, mightily successful, and frequently accurate in choosing your targets. The Fire Ox can be a family person. If you decide to breed, you are deeply responsible and committed to the well-being of your spouse and offspring. You will rule their domain, too, and refuse to take any back talk or flak. You can be kindly and make a generous parent, though you may not be very receptive to kids who complain—feelings are not your strong suit.`,
            "Earth": `You are the busybody Ox. You're curious to a fault, nosy, and meddlesome. You think you know best, and you often do. In general, Oxen consider themselves somewhat superior; you not only think you are better, you believe you were born to lead others, to teach the poor things how to live, and to boss them around. You are a very nature-oriented, earth-bound, power-mad megalomaniac whose nose for locating flies in life’s various ointments is practically infallible. A more self-possessed person one will rarely meet. You are not only self-reliant—you are convinced that others are not. Ask a silly question and you will receive a great sigh of impatience in return. Your tyrannical teaching methods can be offensive, but they require patience and forbearance. You firmly believe that the true goal in life is to achieve perfection in every area. You do not quail at the idea of intense hard work. You are terminally organized and cannot tolerate too much spontaneity. The life and soul of the party, you are not. You lead. You are never really part of the group.`,
            "Metal": `You are the most socially adept Ox. You have charisma. There's a magical quality about you; an aura or halo surrounds your spirit. And it glows. People are automatically drawn to your warm public personality. The charm which emanates from you is natural, artless, and winning. In true Ox style, you have great personal ambition, want to achieve in the areas you choose, and see no reason why you shouldn't become the best in your field. You are not the average stay-at-home, pipe-and-slippers type. You do not usually moon about waiting for Godot or the Tooth Fairy to tell you that you are loved. If you are the partner of a Metal Ox, remember that you are expected to be not only faithful, loyal, and true, but also dutiful, jolly, and up-tempo. Because not every day brings sufficient victory, you will grow frustrated and often come home in a foul temper. At these times, you are unreachable, lost in a haze of blue smoke, sulking. As far as you are concerned, it is your family's job to either get you out of it or get out themselves. You will not accept criticism gracefully. You cannot tolerate reassessment of your methods or approach by anyone but yourself.`,
            "Water": `Water endows you, the Ox, with an extra helping of ponderousness. You are a thinking, planning, plotting plodder who always takes the long view. A sturdy rice-paddy water buffalo—symbol of fertility and patience, service, and strength—offers a true picture of your kindly, yet stern and unflinching soul. If you can help it, you will never beg for a living. You are clever and hard-working and will eventually dominate and thrive in every professional undertaking. You are strong and persistent, accomplishing things in a deliberate manner that suits your measured temperament. You make little noise and demand little attention. You always move ahead. Slowly. You are born knowing how to succeed. Nobody should stand in your way. Because you are patient, you are slow to react. Instead of bonking your adversaries, you simmer for a long while, going quietly about your business, saying nothing, and waiting to see how things develop. Then, just as you are about to boil over, you pick up speed and THWACK! You put an end to your rage by annihilating the enemy.`
        },
        "compatibilities": `Ox with Rat: See Rat with Ox. This is a highly stable and recommended union.

Ox with Ox: The brute force of a double-Ox marriage could plough forty acres before breakfast. Dutiful and methodical, you mutually protect and provide. The household will be blessed with a rare harmony, so even-keeled that any outside influence might throw it off balance. Expect a certain healthy monotony. In your tidy kitchen, you scheme to uphold your common need for order. Despite basic concord, this willful pair sometimes has trouble sharing power. You both like to dominate. Depending on your Western signs, you can probably work things out amicably. Ox couples are mutually stubborn and will not be prepared to expose petty disagreements—not even to each other. Rather than convey dissatisfaction, you will deny your differences and assume a façade of marital bliss.

Ox with Tiger: Disastrous. No matter how you slice it, this combo is in for a rocky ride. Both of you possess an iron will, backed by the power to exert it. Equally self-possessed and determined, you, the obstinate Ox, and the temperamental Tiger are better known as rivals than accomplices. Often, the Tiger jump-starts your tranquil day by stirring up trouble. The stoical Ox wants only to stay close to home and plod on. You must exercise much patience with the rambunctious Tiger, which you will find exhausting. The rebellious Tiger roars off to a trade union demonstration, complaining bitterly about the humdrum, dreary Ox, while you, the Ox, bully the Tiger, accusing them of everything from incurable restlessness to insanity.

Ox with Rabbit/Cat: Cozy. Nestled against a solid-as-a-rock Ox like you, the Cat will have plenty to purr about. You bring the anxious Kitty security, allowing the Cat to spend time on creative activities without having to fret over money. In return, the Cat, endowed with natural refinement, provides your coarser counterpart with much-needed class. Your bossiness is handily managed by a Cat, who usually opts out of conflict. Quiet and submissive, the Cat is happy to take a back seat and let you, the Bull, bully, safe in the presence of a strong, forceful mate. To show gratitude, the Cat lavishes love on you. Of course, you find excessive displays of affection difficult to endure and may shun gestures of tenderness or poke fun at them.

Ox with Dragon: Be prepared for plenty of late-night squabbles in an Ox/Dragon combo. Both of you believe you are righter than right. The Dragon dictates their will over you, the opinionated Ox, and you, the Bull, bully back. You have little patience with vanity. Your indifference to the Dragon’s fiery appearance is a perpetual disappointment to the Dragon’s ego. The glamorous, extravagant Dragon loves to spend money but, with you counting pennies, feels hampered and ill at ease. The Dragon’s wandering eye unsettles you, the faithful Ox, who rarely strays from a good sexual union – you just don’t have time! Too busy working.

Ox with Snake: A slithery Snake wraps themselves around your Ox yoke and goes along for the ride. You welcome this slippery passenger and chug merrily through life. A Snake feels cozy in your presence. Yet, the fickle Snake has an appetite for flesh— especially flesh as yet unexplored, while you are devoutly monogamous. If you can learn to tame your suspicious nature and control a jealous temper, you can hold on to a fetching Snake partner better than anyone else. After all, you have all the money, power, and patience, and Snakes adore all those attributes. Should you start to fret over failed ventures or depleted reserves, the Snake must surreptitiously drag you off to bed. You are happy to oblige with lusty quantity but, to keep the reptile’s eye from wandering, you must develop more imaginative foreplay.

Ox with Horse: Exhausting! These two get along so poorly that the effort which goes into trying is hardly worth the result. What a struggle! You, the conventional Ox, want to tame the wild, independent Horse, whose only urge is to gallop far away. The obstinate Ox never stops bossing and advising. If you interfere too strongly with the Horse’s single-mindedness, the haughty Horse will take every opportunity to mortify you—in public! The best thing about this marriage is the work ethic. It’s very high. Both partners will labor and tote barges and bales without complaint. But the Horse will simply not conform to your ways.

Ox with Goat: In the beginning, the delicate Goat seems like a great catch for a domineering Ox like you. But never judge a Goat by appearances! I caution all Oxen against this union. At first, you feel a surge of power next to this dainty mountain creature. But after several shared hikes, your puffed-up ego will flop like a tired soufflé. The Goat complains endlessly and you (slowly but surely) lose interest. The patient Ox puts up with the Goat’s lackadaisical attitude for a while but soon comes to believe that the Goat is not only lazy but directionless. A hard-working Ox simply can’t understand the Goat’s inertia.

Ox with Monkey: If you can relinquish stubborn conformism and trust your beloved Monkey, the Monkey can greatly improve the quality of your life. In return for the Monkey’s gift of freedom, you will lend security to your Monkey mate. Much to everyone’s surprise, you, the Ox, usually incensed by any disturbance of routine, are fascinated by the tricky Monkey. The Monkey, in turn, tries harder to amuse and enchant you. Both of you are basically practical and project-oriented. Moreover, Monkeys can teach you to step outside yourself and be willingly kind to others.

Ox with Rooster: Should you be lucky enough to have found each other, stay put. Astrologers in China recommend this as one of the best unions ever! Together, your lives will be enhanced by a mixture of easy conviviality and hard-line security. Independently, you can both be equally fussy, nervous, and perfectionist. One might expect this match to come together and self-destruct. But, for some reason, you find peace. This traditional couple lives by the book. You do everything right and the Rooster follows. Not known for passion or folly, your sex life reflects your down-to-earth lifestyle.

Ox with Dog: Don't expect the loyal Dog to bay at the moon out of blind love for an Ox mate. You have polarized goals. The Dog’s job—pleading a case for the homeless—is bound to take priority. And, you? You will be going to bat for a major corporation. These two are so different in their philosophies that mini-battles form craters in their living room carpet. Both are devout moralizers, but you don’t see eye to eye. Sex between you can be fun! This is the only place where your roll-over command has clout. The Dog is tickled by and admiring of your relentlessness and brutally frank style in bed. This is just an okay marriage.

Ox with Pig: Indeed, you two get on famously. The good-natured Pig is so malleable that you will end up thinking you really are boss. Let’s say that at the summit of a beautiful hill, you and the Pig own a home. This home is so well-cared-for that it sparkles. Pig loves to cook and doesn’t mind cleaning up. Before bedtime, you, the careful Ox, turn off all the lights and put out the garbage and the cat. Then this cuddly combo springs into bed. It’s ideal. You are well-matched. Sex between you two country folk is lusty and satisfying. The Ox is a bit square and rude at first, but the Pig’s rich sensuality soon takes over, and you enjoy making a lovely, languorous lifetime of love.`,
        "futures": {
            2025: {"year": "Snake", "element": "Wood", "prediction": `You and the Snake get along like a set of fraternal twins. You don’t look anything alike, yet you are inseparable pals. Snakes always carry their weight in attraction and are not afraid of assuming power. Your styles do not interfere with each other. You plod, Snakes slither. But you are both rather slow and deep-thinking. Hence, your wave lengths match and you truly appreciate each other. You will be granted all manner of successes in this year. Kudos, prizes, and honors will come your way because the Snake admires you Ox people and the feeling is mutual.`},
            2026: {"year": "Horse", "element": "Fire", "prediction": `Because of the general ambiance of diligent labor which characterizes all Horse years, this year will be fortuitous for you. It’s no secret that you Oxen love to work and work hard. You enjoy an exceptional capacity for exertion – both physical and mental. Work energizes you. So when Horse years come around, you are favored and applauded and praised for your unparalleled work ethic. The results will be precisely what you were after because the Horse’s influence protects and preserves The Ox.`},
            2027: {"year": "Goat", "element": "Fire", "prediction": `Goats get your goat. There is friction between you and the Goat because the Goat puts more emphasis on the lighter side of life and is frequently not a self-starter. They don’t have the kind of kick-ass presence and plodding spirit that you have. You want more equilibrium in your day-to-day. In this Goat year, I suggest you take to the hills. But don’t try to compete for prizes or honors. Steer all contests a wide berth. Enjoy your love life now. When you’re not busy making love, why not plan your next business coup?`},
            2028: {"year": "Monkey", "element": "Earth", "prediction": `This year bodes plenty of activity and a speeding up of the pace for you Oxen. I know you don’t adore hurrying and hate to be told to go faster. But Monkeys have no time to waste standing around tapping their feet whilst you ponder and plod through mountains of useless details. You will have to drop the spread sheets, abandon your precious red tape, and learn to hurry. This hectic cadence, however, may take its toll on your health. Be sure to get regular checkups. Bottom line? You will thrive in a Monkey year because the Monkey is cleverer than all of us and knows when they have found a sane, safe ally: you.`},
            2029: {"year": "Rooster", "element": "Earth", "prediction": `Rooster years are always salutary for hardworking people, and you are no exception. You will tend this year to be reluctant to co-operate. Joint projects, group efforts, and partnerships will suffer because you want to have a year off from being a frenetic someone’s ally. You just want to be your own person and move once again at your own sweet (slow) pace. For this year, I suggest you go it alone. Stay working at whatever you enjoy and are sure will bring you success. Your love life suffered a bit from the general tumult of last year. Take some time to bill and coo with your sweetheart or spouse this year.`},
            2030: {"year": "Dog", "element": "Metal", "prediction": `The Dog is no threat to you Oxen. A Dog can yap and growl and snarl at a stolid Ox for as long and as loudly as they want, while you just stand there silent and Oxlike waiting for the tantrum to be spent. However, wisdom has it that in Dog years, the Ox should keep out of the public eye. Why? Because the criticisms and outcries against injustice for which the Dog is so famous don’t appeal to you. If you joined in, you might be noticed. That’s what I mean by keeping a low profile.`},
            2031: {"year": "Pig", "element": "Metal", "prediction": `Oxen usually thrive in the early part of Pig Years. This year will be no exception. You will surely find both adventure and fun aplenty in the first months. But round about June, just before summer sets in, you will need to keep a closer eye on your budget than you have been doing. Do verify all banking and investment statements as computers tend to make more mistakes in Pig years. Overly generous to those they love, Oxen also frequently fall prey to oversight or miscalculation. The Pig and the Ox are generally complicit in their pursuit of affluence for its own sake.`},
            2032: {"year": "Rat", "element": "Water", "prediction": `Rats covet power and they often get it. This year fairly reeks of the Rat’s powerful influence. But that smell doesn’t bother you Oxen too much as you were born with a fine sense of your own strength and haven’t had to struggle, as the Rat does, to gain control. In your case, control comes with the territory. Because the Rat’s drive for supremacy doesn’t threaten you, you usually cruise right through Rat years without missing a beat. You will be left alone to accumulate wealth, nurture your crops, and tend to your family’s harmony this year. In the autumn, tension threatens your professional life.`},
            2033: {"year": "Ox", "element": "Water", "prediction": `Finally! Steady plodding really does win the race. At last you find yourself here in your own very own year. This year offers a major chance to make a big difference in your life now and for the next dozen years. The year itself usually runs relatively sedately along without too many political or social hitches. The message? In Ox years, take charge of your existence and make it different from what has gone before. This year, either you do so or you will be condemned to slog and drudge for 12 more years without making any real progress.`},
            2034: {"year": "Tiger", "element": "Wood", "prediction": `Lie low, Oxen. Avoid the fray. Don’t get caught up in the Tiger’s frenetic pace or you may lose your sense of direction and feel your brain turning to cooked cabbage. Tigers move far too quickly for your taste. Thrashing and hunting are not at all what you Oxen are about. You like to till and toil and build and improve. And you like to do it all at your own sweet, deliberate pace. Stay at home by the fire in your lovely new castle with that kindly ally of yours. Take time to concentrate on gaining the advantage over your enemies this year. Be wise. Strategize.`},
            2035: {"year": "Rabbit", "element": "Wood", "prediction": `A bumper year for the canniest of Oxen, and a bummer year for those of you who lumber clumsily along. First of all, Cat/Rabbits long for security and almost always make good investments. Normally their stealth doesn’t get in your way because you don’t feel jealous about other peoples’ successes. But neither your presence nor conflict characterize their strong points. So furtiveness must suffice. If you were an Ox in a Cat/Rabbit year, you should remain as invisible as possible and as mute as a drum so as not to allow any of your secrets to be stolen or plagiarized. Work will be fruitful. Keep quiet about it.`},
            2036: {"year": "Dragon", "element": "Fire", "prediction": `The percussion level this year will no doubt be well above your tolerance point again. Try and ignore the din and get on with being you. The Dragon’s influence means you no harm, but they do not fancy competition. So stay out of the way. May I suggest holing up in your country house with a pair of hefty earmuffs to keep out the noise? Whatever you do, expect to be drowning in decibels. The love picture improves for you this year. Make it your business to mean business.`}
        }
    },
    "Tiger": {
        "general": `Honorable Tiger, you are noble and fearless. You are respected for your courage and dreaded for your ferocity and incessant intemperance. Like a raging torrent, you constantly overflow your banks. Where are you going in such a hurry? Can't you take just one teensy peek before you pounce? Try to slow down, practice a little moderation. Stop going around being so heartbreakingly attractive. It's exhausting.

Of course, some people find you so dashing and plucky that they want to climb aboard and go along for the ride. But you, Tiger dear, are a swashbuckling loner. The top is the only place you want to be. You court danger. The fiercer the enemy, the more dramatic and calamitous the situation, the broader grows your Tigerish grin. Your changeability, disdain for rules, self-sufficiency and devil-may-care jauntiness could be your undoing.

In matters of the heart, you are too demanding. But you certainly aren't boring. You get on best with devoted Dogs, who espouse your causes. Independent Horses will stay off your case and complicitous Dragons find loving you quite scrumptious as well. Monkeys admire you, but remember—Monkeys can be tricky. Whatever you do, don't take up with a tempestuous Tiger like yourself. You are lucky, but not that lucky.

You'll breeze through your youth. But by the age of thirty-five, half a lifetime's excesses may start to catch up with you. Call yourself to order by forty, and by the time you reach fifty you'll be young again, ready for a productive old age. A piece of advice? Go ahead and take the job as a five-star general, but choose your lieutenants wisely—you’ll be needing lots of loyal counsel.`,
        "elements": {
            "Wood": `Energetic and resilient, you, the Wood Tiger, are a hyper-creative innovator and you bound around like a mad dervish, leaping unscathed in and out of a monumental vat of piping hot water. You lack the guile and stealth of gentler Tigers. You're sociable, up-front, and constantly yearn to undertake the most grandiose projects and make public your extraordinary views of both the world—and of yourself! There is a positive side to your hasty behavior. With so many irons in the fire at once, you are always busy juggling, plotting, and strategizing. You are never bored. You are delighted when your alarm rings in the morning, as you can almost taste the variety of possibilities for expansion and instant involvement in new deals that you stand to get out of each new day. All Tigers like change, but you are addicted to it. The very idea of buying a loaf of bread in a new shop or taking a different route to the hardware store sends ripples of anticipation down your striped spine. You have a dickens of a time sitting still. You're affable, too, and quite easy to get along with, but you are proud, and rankle when others attempt to direct or counsel you. You are not an intellectual, but you think brilliantly on your feet. You're impatient with high-flown idealism and theorizing. You prefer to get down to the job in hand and get it over with—the faster the better.`,
            "Fire": `You, the Fire Tiger, are a charismatic, highly dramatic, and sensual leader. Fire gives your vibrantly impressive Tiger nature even more pizzazz and oomph. You're as energetic, if not more so, than your Tiger brothers and sisters. But your power gets ahead of your good sense. You're recklessly spendthrift with your strengths and you overdo and over-achieve everything you undertake. You simply refuse to husband your own vitality. You push and strain and force yourself through the tightest knotholes for the sake of your brave ideals, wearing yourself to a frazzle to give shape to projects in which you believe almost too fervently. Sleepless nights are the norm rather than the exception for you. Erratic dietary habits and exorbitant sexual exploits are the fuel that fires your powerhouse's constantly revving engine. From fifty onwards (if you live that long), you would be well advised to slow down, take it easy, and stabilize your private life. The Fire Tiger is a revolutionary, too. You want change and are not afraid to initiate it, manage it, and sell it to the people. You devise grand plans effortlessly and can carry them through better than almost any other Tiger. Most Fire Tigers either make a world-class difference or die trying.`,
            "Earth": `You, a twentieth-century Earth Tiger, have a gruesome history of early death resulting from sudden and tragic events - suicides, accidents, and even murder. In China, the Earth Tiger has a reputation as the thinking person's Tiger. You are thought to be less restless, more determined, and sagacious than your counterparts. You make a superior political chief or top business executive. Your desire to lead is strong and so is the desire to occupy a respected position in society. Your spirit here is autonomous, self-reliant, and fiercely individualistic. Despite the calming influence of the Earth element, you are impetuous and headstrong. You concoct scheme after scheme and rush around flashing your complicitous smile and charming the wits out of the world. However, you generally avoid utter ruin because you ask for advice before you act on your rash impulses. You consult your pals, your lawyer, your doctor, and even your neighbors before you make big decisions. Another special thing about you is your non-Tigerish ability to lie about and do nothing. Most Tigers have trouble sitting still, but you can stare into the distance for hours, musing and dreaming of greater moments. You are the most laidback and temperate of Tigers. You enjoy learning new disciplines and putting together logical plans for the betterment of your own and other people's lives. Because of this, you are sometimes seen to be meddlesome and over-interfering in the lives of those you love. You are a monument of strength and a purveyor of justice. You cannot tolerate unfair practices and will fight against social injustice and combat ethical wrongdoing. Like a combination terrier and elephant, you take an idea between your teeth and hang on forever if necessary, because you never forget.`,
            "Metal": `You, the Metal Tiger, are principled, straight-arrow, conservative, and energetic, yet you maintain your Tiger charm and jet propulsion. You're a powerhouse of energy and a doer of grand deeds. But you are somehow more serious than most Tigers. You are not one to leave projects unfinished. You're a bulldozer with the engine of a tank and the scope of at least sixteen aircraft carriers. You have a reputation for making the right decisions at the right time and will hang about waiting for the precise moment to pounce. This behavior can sometimes seem like procrastination, but your hesitation is a form of strategy. You lie in wait, raising an eyelid from time to time to check out the scene. Then you get up, yawns, stretches your limbs, tenses your muscles, and POW! On the other hand, if you have to wait for someone to show up or for something to happen, you go berserk. You want what you want when you want it and have difficulty understanding why others might not want to adhere to your schedule. You hate to obey, yet insist on obedience from others. You also have a somber penchant. From a young age, you may be fascinated by weapons and intrigued with death and death symbols. You face a lifelong struggle to squelch this tendency. You need to surround yourself with 'up' people who keep your mind on the positive aspects of life.`,
            "Water": `You, a Water Tiger, exhibit smooth, creamy manners and seem to lead a charmed life. Great personal (and often early) success characterizes your life. You are a lovable and loving creature, whose strength of will and determination to gain both respect and power are admirable. People honor and esteem you. You are more stable and lead a more balanced life than many of your fellow Tigers. You are often artistic and able to perform in public. You tend to be musical and know how to imitate accents and speech patterns with remarkable accuracy. Having a good ear makes you a natural linguist. Travel appeals to your taste for easy adventure: you prefer to go first class. Long-term discipline is not always your strong suit, but you are capable of protracted diligence in the accomplishment of work projects. You also boast a socially pleasing personality and love being with groups, making jokes, and displaying your seductive talents. As you love company, you want to be a family person. You are reliable and take responsibility for your kin and look after your home. You are known for your sense of fairness. Unlike some Tigers who cannot tolerate advice or criticism, you are able to view your own shortcomings objectively. Your open-minded approach to thorny issues might make you choose to study law. You would make an excellent magistrate: your judgments would be unbiased and humane.`
        },
        "compatibilities": `Tiger with Rat: See Rat with Tiger. This is a relationship with initial charm but long-term friction. Your adventurous nature may clash with the Rat's need for domestic security.

Tiger with Ox: See Ox with Tiger. A disastrous and rocky relationship. You are rivals, not partners, and your differing temperaments will lead to constant conflict.

Tiger with Tiger: Two Tigers? Burn-out alert! You believe fervently in love at first sight and may pounce on each other with gusto. This tandem is full of instant enthusiasms, quick-fix plans, and clever strategies. But there is a basic problem: while both of you are out changing the world, who’s watching the store? Your torrid embraces become passionate arguments. Forever in combat, you two are messily content. A love affair will be played out in fast-forward mode and promises to be ultra-dynamic. But this marriage is unlikely to be either peaceful, long-lasting, or productive. And… God help the Tiger cubs. The insecurity! The ever-changing domiciles and decors. Arrgh!

Tiger with Rabbit/Cat: A style clash. You might very possibly enter into a so-called “marriage of convenience,” but underneath roils a mute tension that screams, “Get me outta here!” In this union, it’s you, the Tiger, who’s doing the silent shrieking. The Cat usually has the money, and you, who married the Cat for the loot, are busy having a nervous breakdown. You live for change and victory; Cats dream only of peace and quiet. No common ground. Even in bed, this pair is not apt to be compatible. You are aggressive, possessing a raw, frank, pushy sexuality that overwhelms the Cat’s delicate sensuality.

Tiger with Dragon: Sexed! The Tiger/Dragon love relationship bears serious consideration. Combined, your strength is almost excessive. And energy! Enough to fuel several large power plants. There is EGO flashing in red neon all over this couple. Overbearing and self-propelled, you are both a bit too much. But as a pair, you can succeed. The dashing Dragon begs for constant flattery and applause. However, you, the strong-minded Tiger, find the pontificating Dragon tiresome and tease the spotlight away. You are undaunted by fire-breathing antics. In fact, you love a good shouting match and respect a worthy opponent. The generous Dragon is amused by and tolerates your love of danger and precipitous behavior. In short, you two get along.

Tiger with Snake: The slithering Snake and you, the tempestuous Tiger, are irresistibly drawn to each other, but this union is not encouraged. It can be a disastrous alliance. As different as black and white, yin and yang, the Tiger/Snake combo just doesn’t blend. The slow-moving Snake will inflict tremendous frustration on your peppy psyche. Initially, you misguidedly see the enchanting serpent as quiet and submissive and attempt to dominate. But reptiles don’t take kindly to bullying. They retaliate. The impressive tantrums of the Tiger can make the Snake’s calm, reflective, philosophical life miserable.

Tiger with Horse: Auspicious, to say the least. Both of you have unruly natures. Individually, you are independent. You might clash, but the attraction between you is strong and so is the mutual respect. In love, you become wilting passion flowers of vulnerability. As a loving pair, your passion knows few bounds. The Tiger and the Horse are equally inventive and creative. In family matters, the Horse’s conservatism curbs your hotheadedness. You work hard together to raise a fine family in a proper way, yet, thanks to your rebelliousness, the kids will get some relief from the seriousness of the Horsey’s approach. The initial sexual attraction is volcanic and you are both imaginative and faithful enough to keep sex exciting over the long haul. This relationship can endure.

Tiger with Goat: This union is among the worst possible known to Chinese astrologers. Although you may make a fabulous start (in bed), from there on it's all downhill. The practicalities just don't work out. The Goat is charming, beautifully seductive, and loving. You are passion and mettle. But who will bring home the bacon? In this family, nobody wants the job. No concessions are made. The Goat remains laid back while you, the ambitious Tiger, bombast a hole in the kitchen ceiling. What was a great passion ends in lifelong misunderstanding and acrimony. Affairs? Yes. Marriage? Abstinence is advised.

Tiger with Monkey: You two make eager lovers. Initially, you will leap frequently on each other’s bones, accomplishing astonishing feats of extreme passion, but in the long run, the ardor may die a natural death, because you hate to be clung to— and innately neurotic Monkeys don’t know how not to cling. The strong intellectual tug between you frequently keeps you together, anyway. You admire the Monkey’s keen eye for strategy, and the Monkey enjoys and applauds your feisty wit and temerity. You have an easy, common viewpoint and, even if you cannot keep the love flame burning, will go far together as lifelong pals. Except… the Chinese say that you should beware. Traditionally, the Monkey is the Tiger’s natural enemy. Marriage is not advised.

Tiger with Dog: Harmony incarnate. You and the Dog just plain get along. You have common causes and common philosophies. But you are very different. You are overly optimistic, the Dog pessimistic. Each helps the other to understand these basic character differences. The Chinese call this pairing a happy alliance of muscle and heart. You have the strength to put the Dog’s ideals across to the public. The disquiet Dog keeps watch and prevents you from leaping into the wrong frays. You are, simply, a great couple. Harmony reigns right from the start.

Tiger with Pig: The basic characters here are vastly different. Pigs are scrupulous and peace-loving. You strategize every move and carry banners for your own noisy causes. Yet with the proper amount of gentle understanding from Piggy and the sort of generous reasonableness for which you are famous, the pair can make a real go of marriage. The Pig admires your punchy gall, and you respect the Pig’s guilelessness and purity of spirit. Instead of clashing, these two complement one another. Your physical relationship is full of tenderness and mutual understanding. You need a lot of affection and cherish the sort of warmth and homeliness the Pig offers your restless nature. Steamy cuddling sessions abound in the Pig/Tiger household.`,
        "futures": {
            2025: {"year": "Snake", "element": "Wood", "prediction": `A year of love and romance is ahead for you when the luscious Snake is in charge. Better for you, Tiger, to be snuggled under the quilt with some sexy character you adore than to be racing about at your usual breakneck pace. Snakes hate to hurry. Money will not avalanche into your bank account this year, but you will have more time and good luck with projects and business deals. Take stock of your treasures and heed the sage advice of your lieutenants. There is much to be learned from the Snake’s wisdom. Stop. Look. And listen. Slow to a crawl and don’t look too busy. Imitate them this year.`},
            2026: {"year": "Horse", "element": "Fire", "prediction": `In Horse years, you Tigers are not always as lucky as usual. The Horse truly loves you and approves of your zany energy. But sometimes misfortune befalls you. Don’t panic. This bad luck is not life-threatening, but it does mean you will have to labor harder under somewhat adverse conditions. Small events will arise as obstacles and may cause you grievances. You will have to work harder to keep fit, avoid sugars and starches to stay thin, and double up on the workouts at the gym. The mood will be jolly this year, but the work may prove difficult.`},
            2027: {"year": "Goat", "element": "Fire", "prediction": `You generally fare better under the Goat’s influence this year, but you also have to fight harder to get what you want. You and the Goat do not view life in the same manner. You are a born independent and don’t enjoy being tethered anywhere. As a result of this major difference, you often feel disapproved of. Ideally, in these years, you will do more traveling for business and pleasure. The money Gods are on your side in Goat years. This may not mean millions, but it does signify that you are doing something right, i.e., itinerating!`},
            2028: {"year": "Monkey", "element": "Earth", "prediction": `No monkeying around! This next 12 months will offer you a spree of activity just the way you like it. Take the Monkey up on all of these propositions. You, more than any other sign, can surely multi-manage such a variety of goings-on. A change in your work environment is in the offing this year too. You are a person whose enthusiasms need changing about as often as you change your shirt. So get cracking on finding that unusual job straightaway. Love life? Medium rare. I say that because the love situation you have been in for so long is well done by this time. Over done in fact. Hence, time to make big changes. Pounce a bit now from prey to prey. See how it feels to enjoy seduction again.`},
            2029: {"year": "Rooster", "element": "Earth", "prediction": `Let the Rooster run the show. Or at least give them the impression they are in a position of leadership. Roosters like to move quickly into action and have their fun, and (unlike yourself) prefer not to leave a trail of dead bodies behind. Your nose needs some application to the grindstone this year. Roosters want to see people busy at work on their various projects and are not amused by stragglers. So keep a high profile. When you are laboring in the hot sun or mining coal deep underground, groan a lot and sweat profusely to let your superiors know just how tough Tiger life can be.`},
            2030: {"year": "Dog", "element": "Metal", "prediction": `Phew! There is relatively little that can go plumb wrong for a Tiger in Dog years. You and Dogs get on well together because you have similar beliefs and take a world view of even the minorest events. Differences of opinion arise when you sense the Dog’s innate paranoia rise to the surface. My advice to you in this otherwise somewhat thorny year is to enjoy the goodwill that the Dog offers you as a protective companion. Bask a bit. Let up on the accelerator at work. Spend some enriching down time just hanging out with friends or family. Go see the Pyramids or visit Niagara Falls. Do something wonderful for yourself, but leave the Dog and their paranoia at home.`},
            2031: {"year": "Pig", "element": "Metal", "prediction": `Pigs confess to a certain gaping awe when confronted by you gadabout Tiger people. Pigs are strong and knowledgeable, but they do not understand your exaggerated need for change. You are forever buzzing about, never lighting long enough to accumulate capital or amass riches. Nevertheless, you and the Pig can be bosom buddies. You admire the Pig’s purity and authenticity of spirit. What they don’t understand about you is what will get in your way this year. The air of plenty will lead you to assume you can spend and give and squander your money and so – you overspend. So tighten your stripes, Tiger.`},
            2032: {"year": "Rat", "element": "Water", "prediction": `As you no doubt already know, the Rat always wants power. For you Tigers, this peculiar Rat character trait is both un-nerving and irritating in the extreme. You don’t necessarily want to be in control of much of anything. But the Rat does not necessarily know this about you. You appear so strong and so sure of yourself that the nervous Rat feels threatened. Hence your life in the Rat year can prove to be less than delightful. The Rat may try to thwart even your most innocent of desires for leadership. Advice? Plan to travel this year and stay out of public view. If you don’t menace the Rat in any way, they will do you the favor of ignoring you completely.`},
            2033: {"year": "Ox", "element": "Water", "prediction": `You must warn yourself off trying to make a lot of money or landing a prime job in an Ox year. Your speedy, catch-as-catch-can methods drive the Ox to distraction. You are well-advised in advance to remove at least one of your jet engines so as not to appear threatening or to confuse the ponderous, drudgery-loving Ox. You won’t have to bow and scrape to get ahead, but you will need to do some “yessing” to those in power. You need all the approval and affection you can garner from those who love and admire your saucy style.`},
            2034: {"year": "Tiger", "element": "Wood", "prediction": `After a couple of slow, but not disastrous years, you will take wing and soar over all you survey. This is your year to rule. You will no doubt adore the power, but you probably will not abuse it as you will be using your superior position to further an ideal – something you are proud of. Do also remember that this year you must plan the next 12 years of your existence. Don’t let the months slip by without sitting down with yourself somewhere quiet and thinking hard about where you want to be in 12 years. Then decide how you want and need to behave in order to reach that goal.`},
            2035: {"year": "Rabbit", "element": "Wood", "prediction": `Cat/Rabbit years are rife with elegance, keen on security, and skittish about conflict. Your naturally hurried style and incorrigible taste for change doesn’t always sit well with the Rabbit’s taste for refinement, which means you will meet with opposition if you attempt to bully your way into anything at all. My advice? Keep your elbows to yourself. Don’t plunge ahead into new adventures without doing some serious planning and plotting beforehand. Romance with a capital “R” will present itself a few times this year. Love will bloom in unexpected places and times.`},
            2036: {"year": "Dragon", "element": "Fire", "prediction": `Not your year to shine. Rather, you should take a back seat during this chaotic and festive twelve months. Let the Dragon take the wheel and don’t get any fancy ideas about back seat driving. Dragons are lovingly egomaniacal. They want the floor, and if you don’t concede the spotlight, they will simply douse the electricity. Tigers are beloved by Dragons and are even perceived as allies and cronies, but both of you always want to take the lead. My advice? Stay out of sight. Don’t compete. Ponder your next coup.`}
        }
    },
    "Rabbit": {
        "general": `Ah, Virtuous Cat/Rabbit, you seek harmony. You are careful and practice discretion in all things. When you sense a conflict lurching your way, you skitter off and hide.

Distinguished, diplomatic, and well-mannered, you are also as nervous as a cat. Culture and refinement comfort you. You don't hate money either: you know instinctively how to earn and keep your fortune without flash or flaunt. You favor traditional antique furnishings over chrome and glass contemporary. You're a soft-stepping go-getter... ambitious but never aggressive, strong but never rough.

Your brand of wisdom says, “He who fights and runs away lives to fight another day.” You are hypersensitive—squeamish, even. You are a bit of a hypochondriac: an innocent hangnail on your big toe alarms you. "Call an ambulance, get me to the emergency room!" Chronic illnesses—migraine, asthma, hay fever, lower back pain, warts, hives—you've tried them all.

Choose a partner from among gentle Goats, scrupulous Pigs, or loyal Dogs. If you're feeling lavish, remember that Snakes are delighted to languish on your velvet divans. Avoid Tigers, Roosters, and Dragons. Their unrelenting panache threatens your tranquil existence. You plan your life to run smoothly. And usually it does.

But should spontaneity enter the picture and events go awry, you freak out. Take my advice and lighten up. Not only on yourself but, more especially, on the rest of us.`,
        "elements": {
            "Wood": "PENDING_RABBIT_WOOD",
            "Fire": "PENDING_RABBIT_FIRE",
            "Earth": "PENDING_RABBIT_EARTH",
            "Metal": "PENDING_RABBIT_METAL",
            "Water": "PENDING_RABBIT_WATER",
        },
        "compatibilities": "PENDING_RABBIT_COMPATIBILITIES",
        "futures": "PENDING_RABBIT_FUTURES",
    },
    "Dragon": {
        "general": "PENDING_DRAGON_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_DRAGON_WOOD",
            "Fire": "PENDING_DRAGON_FIRE",
            "Earth": "PENDING_DRAGON_EARTH",
            "Metal": "PENDING_DRAGON_METAL",
            "Water": "PENDING_DRAGON_WATER",
        },
        "compatibilities": "PENDING_DRAGON_COMPATIBILITIES",
        "futures": "PENDING_DRAGON_FUTURES",
    },
    "Snake": {
        "general": "PENDING_SNAKE_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_SNAKE_WOOD",
            "Fire": "PENDING_SNAKE_FIRE",
            "Earth": "PENDING_SNAKE_EARTH",
            "Metal": "PENDING_SNAKE_METAL",
            "Water": "PENDING_SNAKE_WATER",
        },
        "compatibilities": "PENDING_SNAKE_COMPATIBILITIES",
        "futures": "PENDING_SNAKE_FUTURES",
    },
    "Horse": {
        "general": "PENDING_HORSE_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_HORSE_WOOD",
            "Fire": "PENDING_HORSE_FIRE",
            "Earth": "PENDING_HORSE_EARTH",
            "Metal": "PENDING_HORSE_METAL",
            "Water": "PENDING_HORSE_WATER",
        },
        "compatibilities": "PENDING_HORSE_COMPATIBILITIES",
        "futures": "PENDING_HORSE_FUTURES",
    },
    "Goat": {
        "general": "PENDING_GOAT_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_GOAT_WOOD",
            "Fire": "PENDING_GOAT_FIRE",
            "Earth": "PENDING_GOAT_EARTH",
            "Metal": "PENDING_GOAT_METAL",
            "Water": "PENDING_GOAT_WATER",
        },
        "compatibilities": "PENDING_GOAT_COMPATIBILITIES",
        "futures": "PENDING_GOAT_FUTURES",
    },
    "Monkey": {
        "general": "PENDING_MONKEY_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_MONKEY_WOOD",
            "Fire": "PENDING_MONKEY_FIRE",
            "Earth": "PENDING_MONKEY_EARTH",
            "Metal": "PENDING_MONKEY_METAL",
            "Water": "PENDING_MONKEY_WATER",
        },
        "compatibilities": "PENDING_MONKEY_COMPATIBILITIES",
        "futures": "PENDING_MONKEY_FUTURES",
    },
    "Rooster": {
        "general": "PENDING_ROOSTER_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_ROOSTER_WOOD",
            "Fire": "PENDING_ROOSTER_FIRE",
            "Earth": "PENDING_ROOSTER_EARTH",
            "Metal": "PENDING_ROOSTER_METAL",
            "Water": "PENDING_ROOSTER_WATER",
        },
        "compatibilities": "PENDING_ROOSTER_COMPATIBILITIES",
        "futures": "PENDING_ROOSTER_FUTURES",
    },
    "Dog": {
        "general": "PENDING_DOG_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_DOG_WOOD",
            "Fire": "PENDING_DOG_FIRE",
            "Earth": "PENDING_DOG_EARTH",
            "Metal": "PENDING_DOG_METAL",
            "Water": "PENDING_DOG_WATER",
        },
        "compatibilities": "PENDING_DOG_COMPATIBILITIES",
        "futures": "PENDING_DOG_FUTURES",
    },
    "Pig": {
        "general": "PENDING_PIG_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_PIG_WOOD",
            "Fire": "PENDING_PIG_FIRE",
            "Earth": "PENDING_PIG_EARTH",
            "Metal": "PENDING_PIG_METAL",
            "Water": "PENDING_PIG_WATER",
        },
        "compatibilities": "PENDING_PIG_COMPATIBILITIES",
        "futures": "PENDING_PIG_FUTURES",
    },
};

