
export const zodiac_data = {
    "Rat": {
        "general": "Illustrious Rat, you lucky Rat, you. In China, you are very highly prized (and not just for supper). You are power hungry and know how to “go for it”. Once you get those tiny Rat claws firmly around an honored position, you hold on for dear life. Leadership becomes you. You are fun-loving and sociable. But your private self is often fidgety and nervous. You need to talk problems through. Getting anxiety off your chest is as good as putting it out of your mind.\nSome accuse you of being too communicative. Let's just say you talk a lot. You are not a willing idler. You're quick-witted. You speed through work so as to have plenty of time left to meddle in what others are up to. When dealing in delicate matters, you instinctively know how to keep your whiskers clean. Yet, you are not a born straight arrow. You would always rather zigzag your way to fame and fortune than trot the straight and narrow.\nYou tend to be picky… and paradoxical. You are an odd mix of profligate and thrifty, saving everything from worn-out rubber bands to frayed shirt collars, just in case. Then you go spending like a bandit on some extortionately costly bauble that you deem essential to your well-being.\nYou charm others into doing what you want. Winning friends and seducing lovers is child's play for you sexy Rat folk. Still, I don't see you as promiscuous: you are the marrying kind; you require a family.\nWhy not run out and win yourself a flamboyant Dragon, a conscientious Ox or a trickier-than-thou Monkey mate? Steer clear of Cats and Horses. Youth is a jolly time for you, energetic Rat, but midlife can bring your downfall due to errors of judgment in love or business matters. If you deign to seek counsel from friends, your golden years should prove comfortable and cloudless. My advice? Stop fretting. You'll never starve. For love or money. Crafty go-getters like you rarely do.",
        "elements": {
            "Wood": "PENDING_RAT_WOOD",
            "Fire": "PENDING_RAT_FIRE",
            "Earth": "PENDING_RAT_EARTH",
            "Metal": "PENDING_RAT_METAL",
            "Water": "PENDING_RAT_WATER",
        },
        "compatibilities": "PENDING_RAT_COMPATIBILITIES",
        "futures": "PENDING_RAT_FUTURES",
    },
    "Ox": {
        "general": "PENDING_OX_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_OX_WOOD",
            "Fire": "PENDING_OX_FIRE",
            "Earth": "PENDING_OX_EARTH",
            "Metal": "PENDING_OX_METAL",
            "Water": "PENDING_OX_WATER",
        },
        "compatibilities": "PENDING_OX_COMPATIBILITIES",
        "futures": "PENDING_OX_FUTURES",
    },
    "Tiger": {
        "general": "PENDING_TIGER_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_TIGER_WOOD",
            "Fire": "PENDING_TIGER_FIRE",
            "Earth": "PENDING_TIGER_EARTH",
            "Metal": "PENDING_TIGER_METAL",
            "Water": "PENDING_TIGER_WATER",
        },
        "compatibilities": "PENDING_TIGER_COMPATIBILITIES",
        "futures": "PENDING_TIGER_FUTURES",
    },
    "Rabbit": {
        "general": "PENDING_RABBIT_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_RABBIT_WOOD",
            "Fire": "PENDING_RABBIT_FIRE",
            "Earth": "PENDING_RABBIT_EARTH",
            "Metal": "PENDING_RABBIT_METAL",
            "Water": "PENDING_RABBIT_WATER",
        },
        "compatibilities": "PENDING_RABBIT_COMPATIBILITIES",
        "futures": "PENDING_RABBIT_FUTURES",
    },
    "Dragon": {
        "general": "PENDING_DRAGON_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_DRAGON_WOOD",
            "Fire": "PENDING_DRAGON_FIRE",
            "Earth": "PENDING_DRAGON_EARTH",
            "Metal": "PENDING_DRAGON_METAL",
            "Water": "PENDING_DRAGON_WATER",
        },
        "compatibilities": "PENDING_DRAGON_COMPATIBILITIES",
        "futures": "PENDING_DRAGON_FUTURES",
    },
    "Snake": {
        "general": "PENDING_SNAKE_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_SNAKE_WOOD",
            "Fire": "PENDING_SNAKE_FIRE",
            "Earth": "PENDING_SNAKE_EARTH",
            "Metal": "PENDING_SNAKE_METAL",
            "Water": "PENDING_SNAKE_WATER",
        },
        "compatibilities": "PENDING_SNAKE_COMPATIBILITIES",
        "futures": "PENDING_SNAKE_FUTURES",
    },
    "Horse": {
        "general": "PENDING_HORSE_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_HORSE_WOOD",
            "Fire": "PENDING_HORSE_FIRE",
            "Earth": "PENDING_HORSE_EARTH",
            "Metal": "PENDING_HORSE_METAL",
            "Water": "PENDING_HORSE_WATER",
        },
        "compatibilities": "PENDING_HORSE_COMPATIBILITIES",
        "futures": "PENDING_HORSE_FUTURES",
    },
    "Goat": {
        "general": "PENDING_GOAT_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_GOAT_WOOD",
            "Fire": "PENDING_GOAT_FIRE",
            "Earth": "PENDING_GOAT_EARTH",
            "Metal": "PENDING_GOAT_METAL",
            "Water": "PENDING_GOAT_WATER",
        },
        "compatibilities": "PENDING_GOAT_COMPATIBILITIES",
        "futures": "PENDING_GOAT_FUTURES",
    },
    "Monkey": {
        "general": "PENDING_MONKEY_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_MONKEY_WOOD",
            "Fire": "PENDING_MONKEY_FIRE",
            "Earth": "PENDING_MONKEY_EARTH",
            "Metal": "PENDING_MONKEY_METAL",
            "Water": "PENDING_MONKEY_WATER",
        },
        "compatibilities": "PENDING_MONKEY_COMPATIBILITIES",
        "futures": "PENDING_MONKEY_FUTURES",
    },
    "Rooster": {
        "general": "PENDING_ROOSTER_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_ROOSTER_WOOD",
            "Fire": "PENDING_ROOSTER_FIRE",
            "Earth": "PENDING_ROOSTER_EARTH",
            "Metal": "PENDING_ROOSTER_METAL",
            "Water": "PENDING_ROOSTER_WATER",
        },
        "compatibilities": "PENDING_ROOSTER_COMPATIBILITIES",
        "futures": "PENDING_ROOSTER_FUTURES",
    },
    "Dog": {
        "general": "PENDING_DOG_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_DOG_WOOD",
            "Fire": "PENDING_DOG_FIRE",
            "Earth": "PENDING_DOG_EARTH",
            "Metal": "PENDING_DOG_METAL",
            "Water": "PENDING_DOG_WATER",
        },
        "compatibilities": "PENDING_DOG_COMPATIBILITIES",
        "futures": "PENDING_DOG_FUTURES",
    },
    "Pig": {
        "general": "PENDING_PIG_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_PIG_WOOD",
            "Fire": "PENDING_PIG_FIRE",
            "Earth": "PENDING_PIG_EARTH",
            "Metal": "PENDING_PIG_METAL",
            "Water": "PENDING_PIG_WATER",
        },
        "compatibilities": "PENDING_PIG_COMPATIBILITIES",
        "futures": "PENDING_PIG_FUTURES",
    },
};
