
export const zodiac_data = {
    "Rat": {
        "general": "Illustrious Rat, you lucky Rat, you. In China, you are very highly prized (and not just for supper). You are power hungry and know how to “go for it”. Once you get those tiny Rat claws firmly around an honored position, you hold on for dear life. Leadership becomes you. You are fun-loving and sociable. But your private self is often fidgety and nervous. You need to talk problems through. Getting anxiety off your chest is as good as putting it out of your mind.\nSome accuse you of being too communicative. Let's just say you talk a lot. You are not a willing idler. You're quick-witted. You speed through work so as to have plenty of time left to meddle in what others are up to. When dealing in delicate matters, you instinctively know how to keep your whiskers clean. Yet, you are not a born straight arrow. You would always rather zigzag your way to fame and fortune than trot the straight and narrow.\nYou tend to be picky… and paradoxical. You are an odd mix of profligate and thrifty, saving everything from worn-out rubber bands to frayed shirt collars, just in case. Then you go spending like a bandit on some extortionately costly bauble that you deem essential to your well-being.\nYou charm others into doing what you want. Winning friends and seducing lovers is child's play for you sexy Rat folk. Still, I don't see you as promiscuous: you are the marrying kind; you require a family.\nWhy not run out and win yourself a flamboyant Dragon, a conscientious Ox or a trickier-than-thou Monkey mate? Steer clear of Cats and Horses. Youth is a jolly time for you, energetic Rat, but midlife can bring your downfall due to errors of judgment in love or business matters. If you deign to seek counsel from friends, your golden years should prove comfortable and cloudless. My advice? Stop fretting. You'll never starve. For love or money. Crafty go-getters like you rarely do.",
        "elements": {
            "Wood": "Wood settles a healthy coating of balm on your zigzag nervousness. Unlike other Rats, you know how to relax and take things as they come. Your temperament is cooler, but to camouflage your native standoffishness, you exhibit more amiable charm and extroversion. You possess a more solid sense of your position in society, allowing you to demonstrate a carefree, open attitude. Wood gives you a special talent for discerning both the beauty and the worth of art objects.",
            "Fire": "You are the apotheosis of all Rats. You are a high-strung talker, fashioned of raw energy, laced with a giant injection of nerves and overlaid with a serious case of the jitters. You are like your Rat brethren in every way: outwardly calm, inwardly nerve-racked, protective, generous, greedy, and charming, except that you are more completely immersed in being yourself than in being the person who pleases and cares for others. You want to build something wonderful you can irretrievably call your own. You are also a brilliant intellectual.",
            "Earth": "You are the grounded, no-nonsense Rat who gets to the top cleverly and fast. You seem to have known your goal from the day you were born and work diligently to get the position you have always coveted. Something about you tells people straight away that you can deal sensibly with anything life places before you. You are strong-minded and demanding, always expressing your own priorities first, yet are unafraid to make concessions and negotiate where you cannot win. You are steadier than other Rats and more desirous of keeping the peace.",
            "Metal": "Your street-wise instincts are more fully developed. You are the great persuader, who will stop at nothing to produce the outcome you seek. You take achievement and “getting there” almost too seriously. You’re not in a hurry and never leap before you look at your landing pad a hundred times. You think things through, picking over each detail as you go. You're a ponderer and a troubleshooter. Though you may absorb information slowly, you pick up hostility and grudges on your inner radar screen like quicksilver.",
            "Water": "Your aggressive Rat personality is pleasantly diluted with the influence of the Yin element, Water. To you, ambition and the race for success are second nature. Your first interest is to live a charmed life and move gracefully through its vicissitudes without emerging scarred and crippled. You are more feminine than many of your fellow Rats. You favor elegant clothes and fineries such as gold earrings or diamond clips—not often associated with hardier Rats. You are gifted for giving advice, for which people seek you out."
        },
        "compatibilities": "PENDING_RAT_COMPATIBILITIES",
        "futures": "PENDING_RAT_FUTURES",
    },
    "Ox": {
        "general": "PENDING_OX_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_OX_WOOD",
            "Fire": "PENDING_OX_FIRE",
            "Earth": "PENDING_OX_EARTH",
            "Metal": "PENDING_OX_METAL",
            "Water": "PENDING_OX_WATER",
        },
        "compatibilities": "PENDING_OX_COMPATIBILITIES",
        "futures": "PENDING_OX_FUTURES",
    },
    "Tiger": {
        "general": "PENDING_TIGER_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_TIGER_WOOD",
            "Fire": "PENDING_TIGER_FIRE",
            "Earth": "PENDING_TIGER_EARTH",
            "Metal": "PENDING_TIGER_METAL",
            "Water": "PENDING_TIGER_WATER",
        },
        "compatibilities": "PENDING_TIGER_COMPATIBILITIES",
        "futures": "PENDING_TIGER_FUTURES",
    },
    "Rabbit": {
        "general": "PENDING_RABBIT_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_RABBIT_WOOD",
            "Fire": "PENDING_RABBIT_FIRE",
            "Earth": "PENDING_RABBIT_EARTH",
            "Metal": "PENDING_RABBIT_METAL",
            "Water": "PENDING_RABBIT_WATER",
        },
        "compatibilities": "PENDING_RABBIT_COMPATIBILITIES",
        "futures": "PENDING_RABBIT_FUTURES",
    },
    "Dragon": {
        "general": "PENDING_DRAGON_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_DRAGON_WOOD",
            "Fire": "PENDING_DRAGON_FIRE",
            "Earth": "PENDING_DRAGON_EARTH",
            "Metal": "PENDING_DRAGON_METAL",
            "Water": "PENDING_DRAGON_WATER",
        },
        "compatibilities": "PENDING_DRAGON_COMPATIBILITIES",
        "futures": "PENDING_DRAGON_FUTURES",
    },
    "Snake": {
        "general": "PENDING_SNAKE_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_SNAKE_WOOD",
            "Fire": "PENDING_SNAKE_FIRE",
            "Earth": "PENDING_SNAKE_EARTH",
            "Metal": "PENDING_SNAKE_METAL",
            "Water": "PENDING_SNAKE_WATER",
        },
        "compatibilities": "PENDING_SNAKE_COMPATIBILITIES",
        "futures": "PENDING_SNAKE_FUTURES",
    },
    "Horse": {
        "general": "PENDING_HORSE_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_HORSE_WOOD",
            "Fire": "PENDING_HORSE_FIRE",
            "Earth": "PENDING_HORSE_EARTH",
            "Metal": "PENDING_HORSE_METAL",
            "Water": "PENDING_HORSE_WATER",
        },
        "compatibilities": "PENDING_HORSE_COMPATIBILITIES",
        "futures": "PENDING_HORSE_FUTURES",
    },
    "Goat": {
        "general": "PENDING_GOAT_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_GOAT_WOOD",
            "Fire": "PENDING_GOAT_FIRE",
            "Earth": "PENDING_GOAT_EARTH",
            "Metal": "PENDING_GOAT_METAL",
            "Water": "PENDING_GOAT_WATER",
        },
        "compatibilities": "PENDING_GOAT_COMPATIBILITIES",
        "futures": "PENDING_GOAT_FUTURES",
    },
    "Monkey": {
        "general": "PENDING_MONKEY_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_MONKEY_WOOD",
            "Fire": "PENDING_MONKEY_FIRE",
            "Earth": "PENDING_MONKEY_EARTH",
            "Metal": "PENDING_MONKEY_METAL",
            "Water": "PENDING_MONKEY_WATER",
        },
        "compatibilities": "PENDING_MONKEY_COMPATIBILITIES",
        "futures": "PENDING_MONKEY_FUTURES",
    },
    "Rooster": {
        "general": "PENDING_ROOSTER_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_ROOSTER_WOOD",
            "Fire": "PENDING_ROOSTER_FIRE",
            "Earth": "PENDING_ROOSTER_EARTH",
            "Metal": "PENDING_ROOSTER_METAL",
            "Water": "PENDING_ROOSTER_WATER",
        },
        "compatibilities": "PENDING_ROOSTER_COMPATIBILITIES",
        "futures": "PENDING_ROOSTER_FUTURES",
    },
    "Dog": {
        "general": "PENDING_DOG_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_DOG_WOOD",
            "Fire": "PENDING_DOG_FIRE",
            "Earth": "PENDING_DOG_EARTH",
            "Metal": "PENDING_DOG_METAL",
            "Water": "PENDING_DOG_WATER",
        },
        "compatibilities": "PENDING_DOG_COMPATIBILITIES",
        "futures": "PENDING_DOG_FUTURES",
    },
    "Pig": {
        "general": "PENDING_PIG_INTRODUCTION",
        "elements": {
            "Wood": "PENDING_PIG_WOOD",
            "Fire": "PENDING_PIG_FIRE",
            "Earth": "PENDING_PIG_EARTH",
            "Metal": "PENDING_PIG_METAL",
            "Water": "PENDING_PIG_WATER",
        },
        "compatibilities": "PENDING_PIG_COMPATIBILITIES",
        "futures": "PENDING_PIG_FUTURES",
    },
};
