
export const dog = {
    introduction: `Dear Doggie,  
Man's best buddy truly: you are truthful, loyal, and real. You provide true worth back for love. You are a nice pal—when you're feeling happy. To meet you is to like you, unless you toss out a mean remark or shoot quick jabs at us clueless folks nearby. You have a loud yap, Doggie, that makes even your worst chomp feel mild.  

But you kindly fix that. You trust in rightness for everyone and gladly pick up good fights and carry big loads against wrong rules. You honor old ways and prize respect. You find true joy in aiding an older person cross a crowded road. In life's grand cowboy tale, you surely sport a white hat.  

A sharp smart knack lets you spot tricks and chase down cheats. Problem is, this skill for honesty is so strong it sometimes makes you turn gloomy. Deep sadness and even gloom might follow.  

To guard against this drift to despair, try to hang out with fun friends whose cheer and zest keep you steady. Pair up with a bold Tiger, a dreamy Horse, or a warm, calming Cat. At a young age, you’ll start to see the world is a really unfair spot. You’ll jump into missions and aim to fix simple wrongs.  

My tip? Try not to be so stiffly proper. Welcome some give-and-take. Snuggle up here by the flames and picture brighter times.`,
    elements: {
        Wood: `With a huge heart, this Dog is very caring, gentle, and sweet. Once people figure out how to break through the Wood Dog’s tough shell, they adore him, and this time, he feels the same. Wood Dogs love meeting others. They wish to chat with all kinds of folks, grow varied friend circles, and mix with every sort of person out there. For this Dog, team fun, work buddies, and group tasks are not just okay but best.  

The Wood Dog often builds himself up. A natural edge comes from being super careful and stubbornly set. This mix pushes Wood Dogs to the top of nearly any job they pick. Plus, they’re great at managing everything, even themselves. They watch every little bit, track each task with close care, and can’t step away from hard work for long without feeling bad. This focus gives the Wood Dog a big lead in jobs needing deep study, exact plans, and pure grit.  

The Wood Dog can sniff out a phony, catch fibs, and dig up hidden stuff. He’s smart in a figuring-out way and has a firm style fit for leading. The Wood Dog has a talent for stirring crowds to big aims. This tough person holds very solid beliefs, too. Somehow, he thinks he can shift the world in just days. He won’t bend easy when pushed on a dream or value. He shows no mercy to fakes or flops and naturally knows how to pick helpers when given a big role.  

The top thing about the Wood Dog is his sense of trust. This guy can be counted on. If he says he’ll do something, you can bet it’ll happen, right when he promised, with no slack or wait. On the flip side, it’s wiser not to push the Wood Dog into stuff he hasn’t set up for. Like most Dogs, he dislikes shocks. Worse yet, he hates being caught off balance. He chases perfection and truly believes he must run every part of his (and maybe your) life to get there.  

Since this guy struggles to handle flaws, sometimes the Wood Dog loses faith in making a perfect world and quits work life way before age says to. Instead of dealing with a half-good fix, the Dog will just step away from the mess, head to the hills, tend goats, and drop thoughts of ruling all. He’s not often bitter, just settled.  

This Dog is clever, too. He has a sharp nose for the funny, a biting wit, and a gift for crafting short sayings. Bold jokers, like Alan Arkin, are often Wood Dogs. Their laughs poke at the dullness of everyday folks. They tease normal life and know how to get us chuckling at ourselves. If they pick poems or songs to share, their lines are often sharp, packed with big thoughts on people.  

Fixers love catching tricks, too. Ralph Nader built a life pointing out flaws in things we buy. His job fits a Wood Dog perfectly. He’s free yet works with a crew. He’s asked daily to judge and spot mistakes. He’s paid to be exact and honest.  

This Dog is so tender and frail, so big-hearted and loving that the only way he might dodge a breakdown is to pour his sad energy into a mission. See Shirley Maclaine’s quests and tales of mystery. Folks called her wild, but that didn’t halt her from wagging, yapping, and leaping at people till she got a crowd. Same with Kate Millett, women’s rights fighter, or Brigitte Bardot, who, though long done with movies, spends all her days and cash bettering animal lives in France. She backs pet homes, runs TV fundraisers for the SPCA, and pops up on shows to push kind care for creatures and fight hunting. Cash? She’s got plenty. Coins don’t really grab her. She’s not in it for profit. Bardot fights for the beasts.  

Wood Dogs are tender, sturdy, and charming, but with a hint of old-school ways, they often bloom late, stay choosy, and don’t dive into big romance till their mid-twenties or even early thirties. With so much warm love to give, they feel they must be super picky about where and how they share their deep, true care.  

The Wood Dog isn’t into stuff. In work and play, he’s a real plodder and worker. Yet cash flows easy to this busy soul. He toils hard, but usually not for gain, just to ease his busy mind. He thinks he should cheer up his neighbors and lift his kin to better goals by showing how. The Wood Dog, aside from his taste for judging folks too hard and his nosy streak, is a straight and able person.`,
        Fire: `Don’t bet on the Fire Dog to sit quietly still and pretty by your home’s fire. All Fire Dogs are lively. Their natural bounce and simple charm add a cute, kid-like spark to a bold spirit and make us warm up and trust them fast. Energy is the big word here.  

Since this guy is so real, serious even, we can’t help but want to hear, get pulled into his kindness, and enjoy his plain talk. “Why don’t we shield the Sahara folks? They live like long ago. Their ways should be safe.” is the kind of warm, good thought we might catch from him. Fire Dog thinking is so pure and basic you almost hope it’s true. Take my Fire Dog brother Peter’s latest smart note on the battle of men and women: “Ladies hate guys flipping TV shows all the time cause gals like to stay put, and guys love to roam.” It’s a sweetly easy take. The Fire Dog is open, and he’s spirited, but his views are often simple and off track. His good points are sweetly full of gaps.  

Fire Dogs are eager fans of their own dream lands. They can turn into lone pushers for fair but kinda basic goals. Since their listeners are usually more jaded and used to the world’s risks and twists, Fire Dogs often struggle to gather followers. Despite lots of flops in sparking big cheers for their dreams, they keep going. They trust their hopes. Really, their sky-high wishes are what pull them up each day. Every morning, they wish and plot for a nicer world. The Fire Dog is a brave dreamer who will rush into the fight and push hard for what he trusts in. We’re glad to have them around—most days.  

Sometimes, before he gets far enough against the tide, the Lone Ranger Fire Dog gets down from the tough facts he faces to hit his mark. Folks he counted on let him slip. Jaded lovers keep damping his sweet dreams. Messy games have fired him up too often. The fiery spark Fire Dog hates to lose. Yet lose he often does—even before he’s beat. In this spot, he might lift his paws and (worst case) turn to booze, pills, overeating, or some bad habit to dull the sting of loss and push-away.  

Though he lets himself slide into his own slips, the Fire Dog doesn’t have much room for his pals’ faults. The Fire Dog struggles to tame his wild spirit or get his act in line to shape his own ways. So, he’s an easy mark for clingy bad habits and must keep a sharp watch on his shaky state. When he’s mad at the world, the Fire Dog stops wanting to rein himself in and might pout or pick flaws in all and everyone near. Of course, as a Dog, he still wants to stay true to his buddies and keep faith in their basic goodness. So he often sits in a mix of mixed-up feelings. This up-and-down tug in his heart stirs inner trouble and brings aches to the Fire Dog. That hurt might quickly set him up for more risky self-soothing tricks.  

Fire Dogs make awesome reviewers, fixers, problem-solvers, and guides. They can spot a slip and find the weak spot in nearly any shield. But no matter how much they try, these hot-tempered folks can’t see their own flaws straight. They might call out “chubby” or “slow” or “tipsy” folks all around, but in the mirror, their own belly or laziness or heavy sipping magically vanish. They love the style of a sharp-dressed person and want to look good too, but they’re often stumped on trends. They feel odd in fancy gear and might even scoff at cool looks, arguing loud against fads or styles.  

Sour grapes? Not quite. It’s more a “who cares” vibe, coming from the Fire Dog once again feeling left out, misread, and mad at people.  

Though they often deal with hot tempers and short blue spells, Fire Dogs never look down. They are always friendly folks whose nice ways come straight from a true wish to help and love for others.  

Fire Dogs are driven go-getters and will push harder than most to rise and stay ahead of the group. Their real foes are: their fiery zeal, their struggle to handle how they react to wrongs, and their unlucky habit to huff, puff, and grumble.  

Since the Fire Dog is basically humble, his open anger fades fast. He thinks of others and would blush to be caught making big scenes. Still, bitterness digs deep into the Fire Dog’s warm little heart and muddles his knack for letting go.  

His recall for details is amazing. He can tell you what shirt his mom wore the night she skipped tucking him in and which shelf hid the candies at the summer cabin his kin borrowed in Maine. Yet this guy’s memory, like much of his makeup, rests big on heartstrings. He remembers the day he missed a tuck-in and recalls losing sweets. But the happy times might slip away.  

Since his deep feelings make the Fire Dog sense things so strong, he often soaks up the darkest bits of any moment. By grown-up years, the hurt might grow too big, and the Fire Dog might turn into a top-notch downer and Sad Sam. He must, for sure, fight this pull to see all in shadows and should stick with calm, bright, cheery folks whose feelings match his. He should also settle in quiet green places so kind Mother Nature can always ease his tender nerves.  

Fire Dogs aren’t quick to bend. They should dodge contests, power games, or trade deals. They aren’t super skilled for smooth talk or tough deals since they wrestle with greed and half-steps.  

Good jobs for the Fire Dog lie in healing or teaching, writing, or tunes. Though the shady ups and downs of showbiz might test the Fire Dog’s core kindness, he’s got a knack for speaking deep and can shine big on stage. Behind-the-curtain roles fit this touchy soul: he’ll make a top sleuth writer or quiet detective. Law or leading, as long as the fierce Fire Dog isn’t asked to haggle deals, give him a great shot to speak out on missions and use his fixer spirit.  

In love, the Fire Dog sees himself as the top one. He’s usually not bold or bossy in romance, though. He’s a careful type and always checks for hints of drift in his sweetie. In bed and out, he loves to be teased and wooed. Once in love, he’s soft and warm. His fretful yet kid-like outside doesn’t even hint at the wild passion he can let loose when sparked right. He’s not meaning to cheat. But he’s often mighty tempted to wander. The Fire Dog is a born love bug who needs steady comfort. Tell him often he’s cared for, and he’ll stick to you like glue on a post.  

Lively, free, and true to the end, the puzzling mix of the odd bold yet shy Fire Dog promises never to dull you.`,
        Earth: `The Earth Dog is quiet. Like other Dogs, he might trust in missions and push for fairness, might hope for a nicer world, but the Earth Dog isn’t a hothead. He’s calmer and more easygoing than his fellow Dogs, more careful and peace-seeking. Thanks to his sharp senses, the Earth Dog is quick to feel shifts in the breeze and can’t miss even the tiniest change around him. He’s super picky. His keen instincts catch the smallest jab or snip, giving him real heart pain. When he’s stung, he walks around in a steady wince. He’s so sensitive and breakable he’d rather stay out of the glow.  

Earth Dogs are artsy and soft, made to live in the wildest green lands, circled by plants and pets. They need a shield from harsh truth and do best with gentle pats and a safe feel.  

The Earth Dog is a maker who shines alone. Again, due to his finely tuned nerves, he has to store up strength, which he does by soaking in nature, keeping clear of crowds, and dodging the rush. Look at Michael Jackson, a star and live-wire on stage for sure, but fragile, lone, and open. He cuts a song or clip and slips back to his California hideout where he stays solo, with critters, helpers, and playthings as his only pals.  

Notice, too, that the list of big-name Earth Dogs is pretty slim. Dogs touched by the Earth often stick to quiet jobs forever. They surely aim for cash wins, and they might keep low, but they aren’t timid. Instead, the Earth Dog is naturally chill and super private. He wants his close moments to stay close and his messes to stay tucked away. If a loud career risks his quiet life, an Earth Dog might pull back for good.  

Since Earth Dogs usually skip the big buzz, they can float, watching how others roll. This gives them a great launch pad to kick off a path as a writer or news hound, peacemaker, or rule-setter. I’d bet not many Earth Dogs mess with power games, as they don’t like or stand for fake talk and fluff. The Earth Dog might turn into a fine builder or style maker, room fixer, or picture-taker. He gets the fine points of people’s ways and, as he’s naturally fresh, he’ll craft works of warmth and grace. Earth Dogs make top thinkers, too. If they turn to doctoring, they’ll likely thrive in study labs.  

This hushed, deep soul is also famed for his charm. Though he might not always flash it, the Earth Dog can sweet-talk leaves off branches. He’s shy, steady, and knows how to hear. He’s kind and gets other, busier, twisty, talky folks. The Earth Dog is real bendy of mind and, for a firm Dog, pretty ready to tweak his ways to match any spot.  

Like all Dogs, the Earth Dog can snap out sharp words when you least guess. Yet thanks to his soft heart and basic goodness, his words are less mean and rough than those of his kin Dogs. If he bites at all, the Earth Dog will likely make his point softly, hiding his sharp edge by nudging your neck or patting your bare legs.  

The Earth Dog is a homebody. He puts heavy thought and care into the happiness of his own clan. Always the helper of the kid who lost his ride or skipped his tasks, this guy makes a great teacher. He naturally knows how to blend big-heartedness with a steady push. He adores kids and tends to hold tight views on birth control and choice.  

Last, the Earth Dog is a jumpy, edgy person. He’s not often cranky, but when he is, he craves quiet, alone time, and rest. His body woes often tie to his slow belly, as he’s not exactly a zippy Dog. He should be nudged to munch lots of greens and fiber, sip tons of water, and get heaps of fresh-air play. If he tends his tender nerves and minds his meals, this guy can live to a grand old age.`,
        Metal: `This is the Dog who aims to fix the world—at least his own patch. He’s firm-minded plus big-hearted and giving. He’s a bold, noble soul whose only point for being here is to hunt the perfect prize. Metal Dogs live for their own quests. They’re clear, eager, orderly, and strict. They don’t buy into fights or chaos, feeling calmer, kinder ways can and do win. They reach for a dream with a drive that stuns the heads of less keen, less set folks.  

Oddly, though they sometimes seem hard to reach, Metal Dogs want more than anything to be known, loved, and looked up to by their crew.  

Metal Dogs are the sort most likely to nab a top award, scale a huge peak, find a fix for a skin itch, or reshape a land’s rules. They’re not just tireless chasing a high aim; they never quit, even holding a long grudge. They’re folks of big swings whose targets are rarely small or mild. When he hunts change, the Metal Dog won’t take less than a total flip.  

Metal gives a kinda me-first streak to this Dog. He can and will do grand things. He’s open and even sweet, but he wants the gains he earns through his own sweat to carry his mark and show his trusts. He’s deeply sure his dreams are finer, his goals more right, and his ways more solid than those of less able sorts.  

Metal Dogs get the need for teamwork. Most Dogs like going solo, but the Metal Dog won’t shy from close ties, especially ones that might speed him to his aims. He’s not scared to set his will on others and can build a work squad and keep it rolling as a unit to push his cause. He’s born with top smarts and can dig up fast, bright fixes to nearly any snag he hits. He’s me-focused and not past getting a smug buzz from the praise, nods, and claps of his work mates.  

He’s often wanted as a pal, teammate, or party guest. When it’s about big stuff, the Metal Dog is almost too deep a talker. Yet he doesn’t skip light chat with Madame La Comtesse, whose main worry might be her pup’s bare patch. He’s a high-driven, truly giving soul who can be leaned on to pitch in as he only wants to do right by all.  

As a parent, the Metal Dog can shine bright. He sticks to plans and naturally knows how to steer a home well. He’s me-first without being grabby. Kids won’t just gain from his big spirit and feel a grounding pull from him, but will never doubt their own worth. The me-focused Metal Dog doesn’t question his own or aim to dim his kids’ sense of self.  

Despite a deep care for others, this guy can be sharp and even harsh on weak spots he spots in outsiders. But his high-and-mighty air fades as, with years, the Metal Dog grows softer and milder. It’s young Metal Dogs who are so loud and stern with their peers, kin, and “the rules.” School heads often clash with Metal Dog kids, as they’re bold to call out plans or dislike strict moves. Since they’re usually top learners, the head might be stumped by this outspoken kid’s stand-off ways.  

Once he’s grown, though, self-control is a trait the Metal Dog handles easy. He can dive into law or healing or take up any thinker’s path as he can focus for hours on thick, dull pages the rest of us might hate even lifting off a shelf.  

To chase his aims, wrap up his learning, and climb to ever-higher spots, this guy needs to feel safe. He might stay home till thirty or set up a place young with a pal or sweetie. His crave for home order is key. The Metal Dog is a picky but true lover and mate. He won’t let home fights or fuss pull him from his trust or goal. He wants a calm, steady life and will stop at nothing to lock it down for him and his clan.  

Sometimes the aims of this driven heart rule out a family. Take Mother Theresa, whose call to aid the poor fills her days full. She smartly picked the safety and rhythm of a faith life: home life for such a driven giver would be too tough.  

There are few “famous” showbiz Metal Dogs, who never settle for the empty cheers of cash or fame alone. Metal Dogs want to hit big marks. Some, like Jacques Cousteau, Akira Kurosawa, Andre Agassi, and Sean “Puff Daddy” Combs, might’ve used the spotlight to share their plans and dreams, but they don’t just wish for a shiny, hollow star life. They aim to touch the whole earth.  

Thanks to his pull to go all-out, the Metal Dog often wrestles with up-and-down feelings. He might be chipper and playful one tick but the next drop into a pit of gloom. He needs folks to prop him up, cheer, and praise him in tough times as he might lose trust in his aim and need a morale lift before jumping back in.  

The Metal Dog has huge wonder and must dig to the root of whatever he takes on, checking every bit till he knows the real deal. Nothing slips this guy’s wide pull of sight, making him a detail nut, always sniffing around, hunting hints, and wildly shaping order from mess. When you pair the fixing giver with the snoop, you’ll see the Metal Dog makes a standout law keeper, sleuth, crime pro, or digger.  

Though he’s usually lean and long of build, the Metal Dog loves to eat hearty. He savors top-notch eats and is often a careful cook himself. He’s set on top quality yet cares little for cash piles or wins. If coins are there, he’ll know how to spend smart, grabbing only the best goods, dining at prime spots, and wearing fine, lasting threads. If he’s got no cash, the Metal Dog can still find a way to live comfy and proper. He might mingle, but he doesn’t give a lick what folks think of him or his yard’s shape.  

The Metal Dog is often a big talker. He’ll launch into a tale, tossing in bits and side stories, yapping with pup-like glee through twists of stray points. He very often (yawn) loses his listeners in a flood of loose details. The only fix for this quirk is to clock his chats, then tell him they run too long. He loves exactness and dreads looking silly. If you note his talk on old fish lasted sixteen minutes and thirty-five ticks, he’ll catch on quick. If that flops and your top Metal Dog won’t stop droning, grab a debate rule book and a loud stopwatch that rings when time’s up. The Metal Dog loves order. He’ll fall right into the debate bell’s trick, and you might get table chat that doesn’t stretch from starters to sweets. If that still fails, drop me a note, and I’ll try to dream up a stricter fix.`,
        Water: `There’s a quirky crew for you. A big batch of writers, a sprinkle of tune-makers, lots of actors and actresses, a painter or two, a pair of movie bosses, and even a couple of power players—bright stars, all of them!  

The watery kind of Dog is tricky to know. Not only are they cool and distant when they first meet you, but they might even growl and flash their teeth. Bold? Yep. But the Water-born Dog is also gentle. He takes charge for those he feels life has hit hard, soothing their hurt feelings and boosting their own basic worth. He’s a “softer” type, milder and gentler than his fellow Dogs, able to show and grasp even the trickiest feelings.  

The Water Dog’s power sits in his knack to break down and blend info into art. He’s got a born gift for neatly sorting the leftovers of people’s ties into a bowl and baking them into a tasty, sharp, and fun treat. He’s a Dog, so he’s naturally super tuned-in. Yet he stays grounded and tough enough to hold up under push or knocks. His task here is to teach us to giggle, weep, feel, hurt, or wake up under the pull of his deep art work.  

The Water Dog never skips a beat. He’s born with skills that let him peek around bends, grab thoughts before they’re said, or catch a noise long before it hits our dull ears. Thanks to this extra sense, in a chat, he might seem to float off short into some hidden spot.  

Funnily, if the Water Dog weren’t so skilled as an artist, we might not spot him. He shows such a far-off air he might seem uncaring. The edge we sense in him usually comes from too much caution. Since he never feels sure of others and doubts new faces, the Water Dog might act distant out of care. He’d rather skip empty chatter, so he opts to stay apart. He’s watchful, but he’s not short on self-trust. He’s just born with a quiet, held-back way.  

Weirdly, once you know the Water Dog and turn into his tight pal, he almost never stops yakking. All Dogs have great recall for tiny bits, but this one’s a geyser of small stuff. He doesn’t just tell how he met his first flame; he spills it like a deep-dive reporter might track a growing cell over a day. He kicks off, “There we were at the thirty-seventh line at fourteen minutes and thirty ticks past seven. He wore a tan vest over a bluish soft shirt. His pants were rough weave, the kind with bumpy twists, not the angled sort. The air was muggy and warm, and he was sweating at the sides. A plane flew over. One motor sounded off. Maybe it was skipping or choking…” Water Dog lead-ins are wildly detailed. It feels like he’ll never hit the end.  

As a buddy, he’s warm and friendly, helpful, and giving. He dives into all you do and never drops a speck of your smallest worry.  

The Water Dog is a fair soul whose hot wish to see right done sometimes makes him poke in. You know how it goes when a kind-hearted type steps up for you when he thinks it fits and ends up catching a heap of flak. The Water Dog often gets this unfair payback. No matter how touchy the spot, the Water Dog can’t fight the urge to jump in with friendly meddling. Water Dogs make awesome, true pals, but they’re not slick peace-weavers, deal-makers, or smooth-talkers. They flash their growl before hearing the other side’s tale.  

These pretty beings are super alluring. Early on, tons of their time goes to wooing and bedding lovers. Since they’re Dogs, they do aim to stay true. But sometimes they can’t resist flaunting their tasty charm on someone fresh. Cheating brings the Water Dog awful guilt, which feeds his born gloom. His best move is to dodge the pull of side flings since his feeling frame is pretty frail, and too much guilt can drag him to dark lows.  

The Water Dog is never mean or nasty. Though he sometimes acts out his upset with a snap, he hardly ever breaks rules or swings fists. He doesn’t hunt excuses for his rare slip-ups. He’s a straight dealer, owning his faults and making up for them by crafting fine art, doing good deeds, and always hauling his load of the group deal.  

Another standout trait here is looks. We can’t help but see it. Male Water Dogs are sharp and classy. Their lady kin are stunningly pretty, mixing a crisp face shape with a moving hint of ache. Water Dogs try to live with grace, circling themselves with fine things and savoring nature’s gifts. Water Dogs are busy, but they’re also deep thinkers. They rarely jump before they peek. They push hard and hit big wins without fake swagger or self-pats. Water Dogs will spend a long, wild youth hunting a life mate and are likely to wed folks way older than them.`
    },
    compatibilities: {
        "Rat": "This is a potentially happy marriage. Provided the relationship is conducted fairly, the Rat and Dog can be more than satisfied in each other's company. However, be prepared for long, intense discussions to resolve political, social, and financial differences of opinion. The materialistic Rat may find it difficult to reason with a generous Dog. The Dog gives money away, sometimes forgetting to save enough for the rent. Dogs cannot resist the opportunity to rescue those in need. The Dog's stability depends on being perceived as the philanthropic good person. The Rat does not agree. It is the hoarder, consumed by anxiety about savings, unable to comprehend its puppy-faced mate's desperate need to give everything away. Disagreements are plentiful. But as each half of this couple feels deeply passionate about the other, true harmony is possible. The Dog's love is unconditional, offering a gentle sanctuary for the Rat's restless soul. The happiness you find together, both in and out of bed, will be enhanced by the arrival of numerous children and pets whom you will nurture and raise together as a team.",
        "Ox": "Do not expect the loyal Dog to howl at the moon out of blind devotion for an Ox mate. They have conflicting objectives. The Dog’s mission—advocating for the homeless in Alaska—is bound to take precedence. And the Ox? It will be championing a major corporation and earning fifty percent of the profits. These two are so divergent in their philosophies that minor disputes create deep rifts in their living room carpet. Despite a gentle, loving nature, a youthful Dog, blessed with clarity, understands that this is a fiercely competitive world, yet believes only in justice and equality. The Dog wants no part of the Ox’s arrogant dominance and responds solely to the call of the afflicted. The Ox believes that charity begins at home and will implore the Dog to disregard the world’s problems. Both are fervent moralizers, but they do not see eye to eye: the Dog argues about starving children in India, attempting to persuade the Ox to contribute to the noble cause; the Ox fights for justice at home, complaining that the money used to establish a shelter for the homeless last month was actually intended to pay for the children’s private school. Sexual intimacy between them can be enjoyable! This is the only area where an Ox's command to 'roll over' holds sway. The Dog is amused by and admires the Ox’s relentlessness and brutally frank style in bed. This is merely an acceptable marriage. No sexual fireworks or undying passion will keep these two very different people together.",
        "Tiger": "This is harmony personified. Dogs and Tigers simply get along well. They share common causes and common philosophies. However, they are very different. The Tiger is excessively optimistic, while the Dog is pessimistic. Each helps the other to understand these fundamental character differences. The Chinese describe this pairing as a happy alliance of strength and compassion. The Tiger possesses the power to convey the Dog’s ideals to the public. The anxious Dog remains vigilant and prevents the Tiger from impulsively engaging in the wrong conflicts. They are, quite simply, a wonderful couple. Harmony prevails from the very beginning. And because the Dog and Tiger respect each other’s deepest convictions, mutual admiration binds them together like super glue. In bed, the Tiger typically takes the lead, which is beneficial for the tense, nervous Dog, who often needs to be relaxed before engaging in any intense intimacy. With time, this couple learns to blend eroticism with affection to achieve physical fulfillment. It is rare for such a marriage to end in divorce.",
        "Rabbit": "In Chinese astrology, Cats and Dogs traditionally get along well with each other. Although sexual intimacy is not the most prominent point of connection here, companionship is. Everyone knows how important companionship is to Dogs. Cats also like to feel secure and well-housed. This couple’s marriage is founded on profound mutual affection and respect for each other’s opinions and aesthetic choices. Both Cats and Dogs have a noticeable tendency towards mood swings. Both are critical and easily discouraged by the realities of everyday life and its various injustices. Although Dogs are more pessimistic, Cats can be irritable and ill-tempered when facing difficulties. Their complicity will be based largely on their mutual mistrust of human nature. Their shared cynicism serves as their consolation for enduring an imperfect world. Both parties are dutiful and unafraid of working hard. Money should not be an issue. Mutual participation in professional and paraprofessional projects will strengthen their union. The Dog’s spontaneous expressions of demonstrative affection might irritate the Cat’s sensitive nerves. But one thing is for sure: the Cat can depend on the Dog’s loyalty, which, in the cautious Cat’s heart, holds significant value.",
        "Dragon": "Polarized outlooks might find happiness, provided the sexual intimacy is sensational. But with the Dragon/Dog duo, this is clearly not the case. According to Chinese astrologers, few relationships are less likely to withstand the test of time. Dragon/Dog bickering and barking prevail. Dragons and Dogs are full of enthusiasm, energy, and vigor. But their styles are so different as to make them nearly adversaries. Dogs dislike making a fuss over nothing. Dragons intentionally create daily scenes complete with flames, smoke, and noise. Dragons consider the moralizing, pessimistic, stern Dog an absolute bore. Dragons live primarily for themselves; Dogs live for others. The Dragon will wish the Dog were a more obedient mate. But the free-thinking Dog will never yield to oppression. While the Dragon boasts of successes, the Dog gloats over his or her mate’s resounding failures. I must agree with the Chinese soothsayers: discord reigns. No marriage here, please.",
        "Snake": "This partnership is imbalanced. We are dealing with two disparate types of people. Dogs are pessimistic, prone to depression and worry. Snakes are naturally relaxed, less anxious, and certainly less sarcastic. Sometimes the doubting Dog even mistrusts a companion Snake’s charm and will whine and snap about it, criticizing the Snake for both frivolity and an easygoing nature. Basic personality differences do not have to destroy relationships. But the Dog dislikes society, has few friends, and stays at home a lot. Snakes are just the opposite, yet they need a home to return to after their numerous forays into the wider world. Returning to the comfortable Dog home after experiencing society's greed can be refreshing for the sociable Snake. Even though they snarl and threaten, Dogs always forgive, are loyal to a fault, and never waver in their devotion to their loved ones. Both parties are sensitive to causes, feel strongly about combating injustice, and believe in right over might. This similarity of purpose can serve to harmonize their relationship and smooth out some potential rough edges. The problem is, their sexual selves are very different. Dogs are physically conventional and direct. Snakes are highly adventurous in bed and enjoy intricate sexual play. The two may not clash over this issue, but the Snake may eventually grow bored, resume a natural inclination for flirting, and irrevocably damage the Dog’s tender-hearted soul.",
        "Horse": "If this pair hires a nanny and a housekeeper, a laundress and a cook, they can establish a very sound love relationship. Neither these two effective, active, project-oriented people is enchanted by a career as a house drudge or nose-wiper, staying at home waiting for the other to appear. Horses are characteristically profligate with money. They gamble away and take chances others would not. This risky trait fills the disquiet Dog with fear. The Horse hates to be reminded of profligacy but the sarcastic Dog cannot keep quiet for long. Fights—yes, I said fights—ensue. As harmony reigns in their bedroom, these two usually end up being friends after vibrant lovemaking sessions wherein each lavish pleasure on the other. The Dog is giving and the Horse is loving. It’s a good sexual match. The lovemaking may be salutary, but what will ultimately hold this pair together is their deep respect for each other’s integrity. They are mutually honorable people with a refined sense of social and loyalty. Time will round off whatever sharp angles this pair encounters. A durable, solid relationship is assured.",
        "Goat": "Not much love is lost between these two. The Dog is all moral standards and high-mindedness. Very often, the Goat’s ideals begin and end with where the next meal is coming from. Goats align themselves with the person carrying the wallet. Dogs deplore pandering. Goats know no other way of life. As a couple, unless the Dog decides, uncharacteristically, to shoulder the burden of changing a poor, misunderstood Goat whom he or she believes to be a hidden genius, they will be two very different people going in opposite directions. The Dog likes things to be clear, just, and fair. The Goat doesn’t even know what those terms mean. Goats are dreamers whose ephemeral plans often go up in smoke. Dogs dream too, but their dreams are founded in reality and seek real solutions to real problems. Goats, of course, love sex and favor open relationships wherein they have full freedom. Dogs wouldn’t think of being disloyal. They may stray—but only for a minute or two. To a Dog, devotion and loyalty come first. To a Goat, blind devotion and loyalty are for fools who don’t know which side their bread is buttered. It would be too optimistic to expect harmony from this essentially unbalanced romantic equation.",
        "Monkey": "The Dog is a fervent idealist, while the Monkey lives for the opportune moments. They might well meet and fall in love while jointly engaged in a social struggle. Each possesses qualities that the other lacks. Although this might make them seem perfectly matched, it takes more than complementary traits for two such fiercely independent individuals to truly communicate. Each is so accustomed to living on their own wavelength that they experience significant difficulty adjusting to make themselves understood to someone on a different plane. The solution is extensive conversation. These two restless souls must sit and talk for hours, days, and months before they achieve mutual comprehension. The Dog will have to cease blurting out hurtful remarks, and the Monkey must accept being restrained for at least some of the time. Although they can be guilty of it themselves, Dogs do not react well to infidelity. Monkeys, however, appreciate sexual freedom. The Monkey often appears carefree, while the Dog seems laughably frustrated. Given their fundamentally good intentions, if they wish to remain together, this pair can develop a harmonious sexual life. The harmony in this relationship is achievable but will not be gained without considerable effort. Unless the union is absolutely destined, I would advise imagining it can work indefinitely rather than expecting it effortlessly.",
        "Rooster": "Incompatibility reigns supreme in this couple. Dogs and Roosters are equally resolute and sensitive. Dogs are constantly blurting out criticisms and bruising the egos of those around them. Roosters are confident but deeply insecure. A single harsh remark from the Dog’s repertoire of biting bluntness can incapacitate the Rooster for days, causing depression and undoing his hard-earned image. Do these individuals fight? They never cease. Backbiting, complaining, bickering over minor details. They disagree on everything. Dogs are typically left-wing, compassionate, and trustworthy. Roosters are inherently conservative individuals who believe in the system, adhere to society’s fundamental principles, and cling to traditional ways. This couple’s home life is a constant tug-of-war of political unrest. The Dog desires revolution. The Rooster devoutly wishes for the status quo. The Dog believes mismatched china and a floor pallet will suffice. The Rooster wants fine porcelain or Limoges china set with crystal glasses on an heirloom table. The Dog wants to spend money on causes. The Rooster wants to keep his money in the bank. The Rooster demands more frequent and varied sexual activity than the Dog is willing to provide. The Rooster needs to inflate his ego and preen his feathers. The Dog couldn’t care less about his appearance in bed; he experiences sex rather than performing it. Besides, Dogs are slightly puritanical; they do not believe one should overindulge in pleasure. It is best to leave the Rooster/Dog romantic relationship alone.",
        "Dog": "Gloom and worry could dim the light between two Dogs aiming to team up. Sure, they get each other on missions, wrongs, fairness, and people’s needs. But their rough Dog traits and constant sharp jabs might make hurt the daily norm. Still, there’s lots of give-and-take here. After all, Dogs come in many types. One Dog will always aid the other with stuff like food runs or big plans. There’s little fuss over who’s guy or gal and what jobs suit each. Both honor the other’s time and get their mate’s push to matter out there. Trouble pops up in this bond due to an old foe—dullness. Both Dogs will be super strict, always edgy, guarded, doubting, sour, picky, and short on fun and ease. Life by the Dog den might be a downer town. Stiff rules will rule over free ways. Rightness will pile high. But… if one Dog’s a playful type and the other’s a guard—maybe a barking order sets in, and the two Dogs can pull it off. There’s not much natural sizzle between Dog-born folks, so love acts will be healthy but plain. Closeness spooks Dogs; they doubt nearness. A second Dog sniffing for a quick roll in the yard is about all this pair can hope for in bed.",
        "Pig": "Closeness between Dog and Pig folks promises big, lasting love, honor, and fire. The Dog and Pig click in mind and heart. They both trust in people’s core goodness. They both adore green lands and stick to clear-headed living. Mind you, some basic gaps need work: Pigs crave fancy stuff while Dogs don’t care for frills. Pigs lean steady; Dogs lean free. Pigs love earthy tales—nothing beats a juicy yarn—while Dogs tilt prim. But all these diffs get sorted between Pig and Dog cause they’re each ready to respect and even cheer the other’s tastes and picks. Dog loves the snug safety Pig brings, and Pig sees Dog’s active pals as ideal guests. He stuffs them full. Pig might first be thrown by Dog’s seeming coolness in romance. But Pigs have smart (sometimes sly) tricks to grab notice and will always find a path to their Doggie’s heart. Pigs wait forever. They know how to hold off and nudge till they snag what they want and need from their grumpy but sweet Dog mate. If they grow and guard their shared knack for kindness, this pair will stay joyfully happy for a real long haul."
    },
    futures: {
        "2025": { "year": "Snake", "element": "Wood", "prediction": "Power tiffs and even clashes or fights spark up in Snake years. If the mess might lead to fairness for all, you won’t mind what’s happening. But when push is just for show, you’ll strongly dislike it and might start your own fight against what’s up. The Snake won’t block your quests and drives for betterment, but you won’t find heaps of cash gifts under the Snake’s watch. Snakes love splashing coins on fun, treats, and extras. They don’t feel great funding must-haves. Paying the light bill irks Snakes. So don’t bark for cash to hire fighters for your causes this year. You won’t find eager givers. You might, though, get some sharp advice. Snakes think deep. They grasp what’s brewing under even the wildest scenes. So skip begging for handouts, but do hear all the Snake’s talks. They often ring true. Focus more on your close life. Your sweetie needs your support and comfort. When you dive into your plans and plots, you tend to vanish in body and mind, cutting off ties and sometimes straying from the love nest. If your honey finds out, dear Pup, you’ll land in the dog pen." },
        "2026": { "year": "Horse", "element": "Fire", "prediction": "Oh, lucky you! Horses can’t get enough Dog pals. They’re high-energy folks who never stop working, building, painting, writing, or twirling. Horses are a bit wild. Your calm soothes the Horse. You’re a soul of sense, order, and clear thought. Your thinking wows the Horse and might nudge them to tweak big parts of their days. When you spot waste or overdo, you don’t hold back saying it. You Dogs can be harsh nags. But you can also nag to help a pal avoid a big slip. The Horse (who rarely takes tips from anyone) will heed your words and thank you for being sharper than them. On the flip side, when the Horse rules, the air’s tense and full of loose worry. This vibe isn’t your favorite. Why? Because you’re born edgy and tense, so you don’t need extra reasons to fret. Try shaking off jitters with quiet time or stretches. Or, if calm ways don’t grab you, scrub your floor, wash the ride, or dash around the block a heap of times." },
        "2027": { "year": "Goat", "element": "Fire", "prediction": "This year, shaky vibes tint everything. The Goat means no harm to you Dogs. Really, Goat folks click smoothly with their Dog buds. Dogs love pals of all kinds too. But they extra love the open ears of Goat folks who soak up their gripes about everything from folks’ harshness to unfairness and slants against the broke and rough. So the Dog’s fights and trusts won’t be undone in this Goat year. You might pull off stuff you didn’t think you could swing. Still, you’re cozier not hauling more than your own load. You’re not flaky, but you don’t want to be leaned on. The Goat lives to lean. So in this Goat year, you feel heard but might also feel weighed on. Watch out for lending your ear to sob on too much, ending up with someone banking on you for aid and saves forever. Your job this year is to dodge cling-ons. Steer clear of moochers and zip past critters who fancy crashing at your pad, eating your grub, and hogging your screen till they’re back on track. If you let them in, they might linger into the Monkey year and beyond." },
        "2028": { "year": "Monkey", "element": "Earth", "prediction": "Monkey years can be sly. This one won’t differ. Monkeys know all the tricks and will use them to climb over others as much as possible. As bright as you Dog folks are, you rarely trick just to pull one over. You want right and aim to do things fair. But in this twisty year, you might take a big leap and start a fresh gig or dare something bold. Why not aim to hit it big? Instead of riding back, you can lead, dreaming up plans to stack cash. It’s time you saw coin wins and could ease off wearing your soft heart out front. The kin scene in the Monkey year will be cheerier than lately. You might be more in the spotlight than you like. Take it easy. Call your folks, in-laws, and young ones for eats outside, grill days, road jaunts, and sun play. You’re always good to kin, but that hasn’t always swung back. Savor it while it lasts. While all’s rolling smoothly, get check-ins. See your healer for a full look-over. Hit an eye doc or other pro for odd signs, and don’t skip the tooth doc every half year. Nothing seems off, but better safe than sad." },
        "2029": { "year": "Rooster", "element": "Earth", "prediction": "This year has clear old-school tones. Because of this, if you try to topple rules or push the rich to ditch their boats to house the lost, you’ll take big hits. Instead of fighting the way, keep last year’s cash-chase track. It’s the only path to keep scoring. No push will make the Rooster grin at your drives for more aid to the broke, better open learning, or health cover for all. It’s not the slot for that kind of good-doing. So roll with it and aim for more personal stash. If you dig in and pile up cash in this Rooster year, you’ll have more to splash on quests next year, which is The Dog year! Romance keeps dodging your grip in this Rooster year. Dogs aren’t happy pups without love play. The cash chase might not thrill, but being a work nut keeps you off the lanes. Don’t overdo fancy eat-outs. If you’re not careful, your middle could go wide." },
        "2030": { "year": "Dog", "element": "Metal", "prediction": "Whew! This twelve-year stretch has been a rough pull for you Doggies. Hats off for making it with tails up. As promised, you now hold way more coin than past years. In this Dog year, nothing blocks your wins in all you try. No point dropping the gig you smartly kicked off a couple years back. But do ease up. No use trading your wellness for cash piles. You’re not that into stuff by birth. You could live fine in a one-room spot with a lone mug (no plate) and a fist of food call numbers. You’re not quite a bare-bones type, but darn near. So if you’re worn from shining at cash-making, take a break to sip some old brew from your solo cup and flip through good reads. Don’t forget, per Chinese star tales, in your year you must sit and map the next twelve years of your days. Where do you want to land in 2042? What’ll you be up to and with who? Jot each year and line up your musts. If you want kids and don’t have ‘em, start mulling now. Do you ache to build a fresh pad, trek the globe, scale a tough peak, or wed the dream king or queen? Plan to fill all gaps to steer your fate." },
        "2031": { "year": "Pig", "element": "Metal", "prediction": "Dogs always gain from the Pig’s kind sway. The Pig craves fancy, but not to grab more baubles, own flash rides, or hang with “the in crowd.” The Pig hunts realness first. If he stacks big cash, he might sink it all in one art piece he’ll prize and hold dear—even if it sits solo on his wood shack’s wall. If a Pig picks a mate, you can bet they’re a soul of worth with a heart set right. Gems? Same deal. Only the best. Even if she’s got one stud—the Pig will nab an old 18-karat pink gold gem from a top sale spot in a grand city. So in this Pig year, old ways and worth top the list. Make it your job, Doggie, to use this lucky time to push your fights and roll out quests. The Pig adores you and cheers what you stand for. You can bank on him to lift your spirit and name. Love, waiting quietly offstage, steps your way in Pig years. Feel free to fall deep in love and even tie the knot this year. It’s a full-on, fun-packed year of pure joy for Dogs." },
        "2032": { "year": "Rat", "element": "Water", "prediction": "This Rat year won’t be your top for doing stuff. You’re totally unlike the Rat. Dog folks lean to dreams over stuff. It’s flipped with Rats. Rats hunt clout (and coins) in every scene. Dogs like some clout too, but for different whys. Dogs chase power only if it hands them pull to spark fair change. Dog leaders or pack heads want to see right done. They lead to fix the world their way—not to boss folks. Rats lead to lead. So in Drivers in this Rat year, you can yap as loud as you like, but no matter how hard you bark, you won’t get past your yard’s edge. The Rat doesn’t care what you want. Your home life needs close watch as a kin’s double-cross is brewing. This sneak stab might tie to cash or land. It could be a young grown kid set to ditch school or home. Stop this early by talking it out and giving fair options. Else, though you won’t feel you’re moving up, you’re holding steady. In Rat years, that’s all a Dog can ask." },
        "2033": { "year": "Ox", "element": "Water", "prediction": "Though Dogs and Oxen aren’t tight pals, you mesh okay if you keep clear of each other’s path. Hush your big change ideas and don’t stir trouble this year. Your shot at wins won’t get blocked by the Ox’s sway. He’s not your foe or rival. He just finds your push for fixes young and silly. If an Ox aimed to topple a rule, he’d grab it with force and set up as top dog. The Ox is the one who must be followed. No one bucks a set Ox and walks away fine. So plans to shift your world by calm, vote-based ways must wait till next year. Meanwhile, your kin scene clears up in the Ox year. Folks plotting sneaky moves got talked out of wrecking home peace. Love sneaks back in too. Real, cozy, sweet, lasting love pops up near year’s end in a funny mask. A dull work pal or old school mate shows up odd when you least think it. Open your arms to this surprise charmer. You’ve earned it." },
        "2034": { "year": "Tiger", "element": "Wood", "prediction": "You Dog folks glow in Tiger years. Your cash luck shines, the sun beams on your kin, and your heart beats fast. Tigers and Dogs are kin under the fur. You agree on so much it’s hard to list it all. What stands out most is you both itch to fix the world. The Tiger blasts through walls and waves flags high while you fret that the law might win the fight and maybe hurt or zap someone. You’re the worrier; Tiger’s the fighter. Tigers fear zip. They grab change, chase it, then roll in it like shedding their stripes. But you can’t do that. You’re too scared something bad will hit. This year, put yourself in the Tiger’s bold, fearless grip. You’ll bloom, and so will your dear ones. For their help, fret for the Tiger. As the rash Tiger pulls you into the fray, whisper as his true sidekick that it’s not smart to step out bare without tough vests. Tigers might hear your tip. Or not. Watch your born knack for over-worry." },
        "2035": { "year": "Rabbit", "element": "Wood", "prediction": "At first, you might dread this year feeling real off. But unease fades when, after weeks, you see the Cat/Rabbit is kind to Dogs—helpful and soothing. In Chinese star tales, Cats and Dogs get on pretty well. The Cat/Rabbit might not join your battle charge but won’t block your path and might (if nudged soft) pitch in for your kinder goals. You’ll be shocked in the Cat/Rabbit year by how the year’s vibe lifts your mushy side. The one you adore and wish would take your vow might say yes. There’s proof of sticking now. Time to plan a life as one. If you miss the right steps at the right beat, you could skip the love ride in this Cat/Rabbit year. Keep ears perked for clues your sweetie’s set. They might not yell a wish to settle. Peek between words and catch sighs for hints of okay. Cash rolls freer into your stash mid-year. Tuck some away for a big trip or save it for a kid’s room gear." },
        "2036": { "year": "Dragon", "element": "Fire", "prediction": "You’ll find this year edgy due to the loud fuss and show tagging every Dragon’s rule. They can’t sit still. They need a willing, awed crowd. You Dog folks don’t gush much. You give a “ruff” of okay and move on. For Dragons, your shrugging “ruffs” don’t cut it. So the Dragon hollers, struts, and cheers louder. You won’t hush his flash. Roll with it and keep grinning. If you meet the Dragon with a nod and (fake it if you must) some wow, he’ll hand you top-notch tips. Tune in. Dragons are bosses you can glean big plans from to wage your fight on wrong. Don’t show your itch with the Dragon’s flair. Let the noise roll. What’s it to you? You’re there to soak up know-how. Home stuff might make you look bad this year. You’ll likely spark the slip yourself. Your sharp quips can land you in hot soup. Don’t tell your kin’s mate her hair’s like dry straw or shake the family meet-up by saying whoever cooked the spud mix needs a redo class. Grace, Doggie. Grace." }
    }
}

  