export const horse = {
    introduction: `Distinguished Horse, high style is your style. Self-possessed and proud, you dream of forging your own unique path through life, moving mountains, and transforming the existing order. You are active and energetic. Yet, unless you feel inclined, you may stubbornly refuse to do anything at all. Nobody can make you budge an inch. You are not lazy; you simply do precisely as you please. Nonetheless, Horse individuals are doers. You are a resolute achiever who cherishes your goals. You fear failure and will labor tirelessly to safeguard your career. Money is important to you, and you never let sentimentality impede your progress. You are even willing to step over a few obstacles to achieve what you desire from life.

Passion is the only emotion that can melt your ruthlessness into tenderness. It may even cause you to surrender the keys to your innermost soul, turn your back on family, abandon friends, and erase your past for the sake of pursuing an idyllic future with the object of your affection. Beware! Such exclusive devotion can be the ruin of an otherwise hardy and practical Horse.

Beneath a facade of near dandyism, you are oddly conservative. Your standard-striped ties may feature a shocking pink background, but they are still standard-striped ties. Your basic black dress may boast a sexy off-the-shoulder neckline, but it is still basic black. You perceive yourself as a reliable, straightforward individual. But verbally, you are outrageous, outspoken, and often inappropriate. To belong (and despite your rebellious streak, you yearn to belong), you will spend much of your life learning to control your outbursts. You are irritable and arrogant when provoked—and you are frequently provoked.

Childhood is easy for you; children are expected to be spirited and turbulent. Young adulthood will be a stormy, reluctant period. Although fitting in appeals to you, responsibility dampens your high spirits. Maturity arrives late for Horses. But once it has its common sense under control, the Horse progresses smoothly. Here's a piece of advice: do not break rules. Crime is not your strong suit. Your happiness lies in your work.`,
    elements: {
        Wood: `Perhaps the most opinionated of all Horses, the Wood Horse, although a sociable, convivial person, gives little quarter to weakness, either in others or in himself. This Horse, governed by the verdant Wood element, has a tendency to judge others by his own standards, making him intolerant, harsh, and, at times, impossible to get along with.

Although he can hardly be considered as giving as Mother Theresa or as self-sacrificing as Albert Schweitzer, the Wood Horse is capable of great altruism. He is often known for his generosity towards those less fortunate—but only those he deems worthy of his gifts. He thrives on influencing others and enjoys watching people pull themselves up by their bootstraps to finally take charge of their lives. The Wood Horse will gladly help the strong grow stronger but is not apt to sponsor fragile souls who want to depend on him for life. So the Wood Horse is charitable, but not philanthropic.

Wood Horses may suffer from the blinding light of their own brilliance. From birth, they feel different and special. At home and then at school, they are applauded for their fine intelligence and hailed by teachers as more willing to take chances than the other kids. Once out in the world, the Wood Horse, a sociable and likeable person, is again encouraged by the praise of bosses and superiors. He seems to know instinctively how to rise to the top without half trying.

As a born over-achiever, the Wood Horse may arrive at the age of thirty holding three doctorates and a master's degree in four different subjects. Being the type to try anything once, he may suddenly decide that what he really wants is to become a writer, singer, actor, painter, or dancer! He may reject job offers, close his ears to worn-out accolades, and take up residence in a freezing cold garret where he will sculpt until he gets really good at it. Then he may grow bored and decide to further his study of nuclear medicine.

If he is not careful to manage his talents, focus on his aims at an early age, and find his social niche before he reaches thirty-five, this Horse may find himself burnt-out by age forty, a jack of all trades and master of none. There are worse fates than being forty and knowing how to fly airplanes, do brain surgery, and tap dance, but it is wise to have some idea of who one is and where one is going before the onset of middle age. This is the Wood Horse's toughest challenge. Not only is he so good at everything, so adventurous, and such a hearty risk-taker that he feels tempted to have it all, but he is also highly susceptible to praise and greedy for the thunderous applause all this achievement brings him. It’s difficult for him to get off his own roller-coaster.

Wood Horses hate authority and refuse to yield to those who claim to rule them from a position of hierarchy. If the Wood Horse feels that the person telling him what to do is not equal to him in brains and brawn, he will walk away, leaving the boss to listen to his own ratings. He is bold and, at times, foolhardy. Important jobs will be awarded to him because of his excellent academic record and affable personality, but sometimes he loses them or is demoted because he refuses to be dominated by fools.

The Wood Horse is an excellent self-promoter. He knows every trick to get himself noticed. He usually sports a very pleasant demeanor. He is, for example, gifted in holding the attention of an audience and has good luck in careers where public speaking or performing are prerequisites. Wood Horses can excel at politics, as they are both bright and persuasive. They are also very funny, with a sharp, biting sense of humor. Unfortunately, they don't usually know how to laugh at themselves; their jokes almost always poke fun at others. Male Horses can be extremely sarcastic.

The Wood Horse is not only intolerant of those he considers less clever than himself, he is envious of those who are better established or more successful. Jealousy is a terrible curse, and its presence in the life of this otherwise sunny soul gnaws away at his nervous system, eats at his equilibrium, and causes him both emotional and physical distress. Ordinarily he looks before he leaps, but in an attempt to eliminate anguish, the envious Wood Horse is capable of making rash moves and committing foolish, warlike errors which may cause him to lose both ground and face with those who hitherto respected him for his wisdom.

On the surface, the Wood Horse is easy to get along with, charming, and friendly. He loves novelty and is attracted by new ways of approaching old problems. He is a jolly companion who longs to be the center of attention. In love, Wood Horses make fun-loving sexual partners who enjoy the game of seduction. They are good-looking, innovative, and never boring in bed. Wood Horses, though, do tend to be a shade on the selfish side; they may seek their pleasure first and, if there's time, will then consider that of their partner.

In general, Wood Horses try to be cooperative. They may be head and shoulders above the crowd, but they still want to fit in. Yet compromise is not their strongest suit. They bridle at the notion of keeping their opinions quiet, as they like to think of themselves as authorities on many matters. If consulted, they may swell with pride, make grandiose pronouncements, give untimely or overbearing advice, and even become meddlesome with friends and family.

There exists in this creature a lack of intuitive perception. If you have dealings with a Wood Horse, no matter how his aura of genius impresses you, remember that exceptional intelligence does not compensate for a lack of feeling and insight. He is smart, elegant, glib, and fun-loving. He is witty and multi-talented. He can talk the pants off anyone who will listen and is afraid of no trick. But this Horse has about as much second sight as an earthworm. If the Wood Horse is wise, he will try to learn the trick of true human understanding by trying to learn (through the gentler hearts of those he trusts) to feel and intuit more effectively.`,
        Fire: `Oh, la la! The most challenging sign of all to define. Before I attempt to describe the Fire Horse's character, let me state that whatever I have previously mentioned about Horses in general (brilliant, rebellious, attractive, stubborn, self-centered, socially obsessed, etc.) can now be multiplied tenfold in intensity and applied directly to this mystifyingly irritable and lovable personality.

Fire Horses do not do anything by halves. Every Fire Horse is a walking magnifying glass for ordinary experience. In the mind's eye of a Fire Horse, every tiny gesture is a world-class event, every sigh a howl, every friendly kiss a meaningful experience. Fire Horses transform every tear into an ocean of sorrow and convert every titter into an uproarious belly laugh.

In dealing with Fire Horses, you cannot win for losing. If you make any attempt to get close to this adorable monster of temperamental behavior, you will end up confused and bewildered, wondering what you have said or done that could cause such an unmanageably inappropriate reaction in what, two minutes before, seemed a normally balanced human being.

When it comes to discussing himself, the Fire Horse is a sealed tomb. He is a master at deterring interlocutors with sullen glares and sarcastic remarks. He obstructs all probing conversation and stops progress before it begins. The Fire Horse is unable to engage in normal discussion or argument, dares not exchange a few sociable remarks, or indulge in verbal sparring with friends. Life itself is amplified for the Fire Horse. Whatever happens, he almost always over-reacts. He might get so angry that he could hurt someone or blurt out a cutting remark that will end a friendship.

Wise Fire Horses learn early how to stop the battle before the first shot is fired. They simply take the initiative and eliminate their adversary. Conversing with these volatile Fire individuals is dangerous to one's self-image. So, if you are planning an affair with a fascinating Fire Horse, prepare for a constant volley of rapid-fire put-downs—and do not say I did not warn you. Fire Horses are formidable individuals.

Yet even at their most smoldering, Fire Horses are among the most endearingly genuine souls on Earth. All of their antics and exaggerated behavior make them extraordinarily interesting to be around. They are oddly naive and, at the same time, amazingly sophisticated. They can kiss you one minute and try to annihilate you the next. They may taunt or tease you into striking out at them and then be deeply sorry and claim that they wish they were dead because they hurt your feelings. They are deliciously funny and playful, too. Their incisiveness is remarkable, and their talents are myriad. To know a Fire Horse is to love a Fire Horse—or else!

But, like the fickle element that governs them, Fire Horses get so swiftly out of control as to be in constant danger of setting their own precarious world on fire. These are rebellious, difficult, hard-working people. It is impossible for most normal mortals to comprehend what Fire Horses are really doing because: (1) they are not natural sharers of private or emotional information; (2) they prefer only to project vibes about what pertains directly to them and their own ambitions, hopes, and dreams; (3) they have practically no capacity for compassion; (4) they have little sense of family or loyalty to it; (5) they are excessive and unstable; (6) they are ruthless, selfish, and proud.

Fire Horses have some dreadful faults, but they also possess a multitude of good qualities: (1) Fire Horses are splendid to look at; (2) they are exciting; (3) they are creative geniuses; (4) they have limitless energy for achievement; (5) they are solid citizens; (6) they are ingenious; (7) they are exceptionally clever; (8) they love with burning intensity.

The Fire Horse lives with a volcano inside him, which threatens to erupt if he opens his mouth even slightly. At an early age, he becomes aware that his reactions are considered excessive. He cries louder than other babies, laughs harder, and eats more. Soon, his parents begin to perceive him as a perilous pot of simmering milk about to boil over. They handle him gingerly, as though he might explode. Yet, despite the inner volcano, our subject is, first and foremost, a Horse. He wants to fit into a group or social unit. He desires popular acceptance and needs to be cared for and about by his peers and family. But if he cannot discipline his explosiveness, the Fire Horse can remain misunderstood and may end up a social outcast.

The young Fire Horse's life is a series of attempts by himself, his peers, and his entourage to control the flames, to stay close to the warmth without being scorched, and to keep the home fires burning without having to call the fire department. This sensitive lifestyle is hardly conducive to stability. In this atmosphere, the young Fire Horse often grows more and more remote, rigid, and unapproachable. His own family feels left out. His friends find him impenetrably sulky and withdrawn. But the Fire Horse suffers most from his unbreakable spirit. He encounters many obstacles to controlling his own rage and tempering his fervor. He finds normal expression pale and even dull when compared to what he truly feels inside. He even begins to think of himself as a misfit.

Usually, feeling ill at ease among his wary friends and overly deferential relatives, he rebels and leaves home early to make his own way in his own time. As a result of this departure, the Fire Horse directly confronts his extravagant self in the real world of work and moneymaking, spending, and responsibility. The new challenge is enormous and more to his liking. He may feel burdened when asked about his headaches in the confining intimacy of his home; but competing to become a first-rate opera singer in New York does not deter him for a second. He believes in his own capacity for greatness.

Fire Horses try to bring about change through sheer force of will. They push hard until the obstacle yields or walk away in a huff and go it alone. They do not have patience with long-term solutions or power games, refusing to willingly engage in either.

The life of a Fire Horse is never simple. He struggles uphill against his own internal resistance, suffers from envy, and seeks revenge against his enemies. He is enormously talented, and his gifts are usually recognized early by teachers and specialists alike. But he lacks perseverance, refuses authority, and often abandons a brilliant future in favor of solitude and independence.

Virtually all Fire Horses have difficulty with personal relationships. They want to believe that others are as perfect as they imagine themselves to be. When things do not turn out as they hope, they are stricken with disappointment and despair. Many Fire Horses suffer from depression and may have nervous breakdowns. They grieve over losses that less dramatic souls would consider moderate; they languish in netherworlds of silent rage where they feel lost and lonely but from which they are unable (and sometimes unwilling) to escape. Then again, they may suddenly feel wonderful, wake up on the right side of the bed for years at a stretch, and dwell for a period in euphoric happiness. During these good spells, Fire Horses often make positive things happen. "Genius" is not too strong a word to describe their creative talent. Even in love, Fire Horses are rapacious and abstinent, greedy and generous, selfless and selfish. Commit yourself to one of these volatile characters, and you will never experience a moment’s boredom.`,
        Earth: `In the Horse born in an Earth year, we encounter a better-natured and more easy-going Horse than the rest. The Earth provides a solid base to the otherwise skittish and nervous Horse individual. He is less impulsive, more level-headed than his counterparts. The Earth Horse is a straightforward person with sound ideas that he puts into practice either alone or under the guidance of some serious superiors. He works well in groups and is able to add an element of fantasy to even the most mundane work situations.

For a Horse, he accepts authority graciously. As an employee, he instinctively knows how to be innovative and competitive without committing immature acts of insubordination. Although he may be excitable, and even inconsistent, generally his work style is positive. Just as he is willing to take orders, he is also able to give them. He handles people well, is never too bossy or critical, and, as he has a congenial nature, he is usually well-liked. The Earth Horse has fewer problems with relationships than his fellow Horses, as he is perhaps the most compassionate and altruistic of them.

The Earth Horse is often an artistically talented person whose special gifts preclude the necessity for routine jobs. He would much prefer to be a film director than vice president of a bank. He'd rather perform cabaret than work in an office. He is far more gifted for singing or acting or dancing than he is for practicing medicine or reading law. The Earth Horse knows how to take a back seat and put his ego aside. Compromise and diplomacy come easily to him. His financial picture is generally healthy too. Thanks to his reputation as a competent budget manager, the Earth-born Horse is frequently called upon to restore failing businesses to profitability, to resolve messes created by incompetent individuals in the building trade, or even to troubleshoot in the military.

Although he can be excitable and excessive, the Earth Horse is capable of toning down his extravagance. He is a fighter and will go to the front for what he believes in. But he is a born advocate of the adage, "He who fights and runs away, lives to fight another day." The Earth Horse will only struggle to a certain point. If he can foresee that a battle might deplete his resources, he will turn tail and race back to the safety of the stable. The Earth Horse doesn't mind losing face by losing a single battle, as his true aim is to win the war.

Less self-involved than other Horses, the Earth Horse often engages in activities that seek to remedy society's ills: feminist politics, adopting orphans, helping the elderly claim their rights, cleaning up messes after natural catastrophes.

Even though he rarely appears timid or acts like a shrinking violet, the Earth Horse is hypersensitive. He may weep at the slightest provocation—sob at a stranger's wedding or sniffle through an entire movie. This hypersensitivity may cause him to be grouchy or at least testy. He loves growing flowers and tending to animals and may even perform delicate handiwork such as building furniture or quilting.

The Earth Horse loves the countryside. His mood is often deeply affected by feeling confined in an urban environment. Running wild and breathing fresh country air fuels his artistic bent and frees up inhibitions. His best choices for a career are in art or art-related fields. Painting or any graphic art will suit the Earth Horse. He can be outstandingly successful in all areas involving the theater and cinema. He is a creative person whose ideas are not merely new and exciting but, because he is a Horse, practical—and, as an Earth Horse, even his grandest projects are always grounded, sensible, and safe.

Writing is a less obvious profession for this Horse because he doesn't enjoy sitting still for long—he needs activity and movement to be happy. If he likes to write, he might want to try journalism or copywriting, where he can remain active. This talented character can also flourish in music. He can become a maestro in almost any field where a musical inclination is required. He might be a producer or an instrumentalist, a singer, conductor, or composer. The Earth Horse has a special musical gift. Even if he doesn't opt for music as a profession, he can always take it up as a hobby.

The Earth Horse, like all the other Horses, falls in love intensely. Once he has found the person he feels is right for him, he is likely to stay where he landed for the rest of his life. The Earth Horse is faithful and traditional: he enjoys family life—especially if he is the parent who manages everything—and insists on well-behaved, happy children. He has intense and long-lasting friendships that he cultivates as carefully as his garden. If, however, he is betrayed by someone he cares about and trusts, he will seek revenge and demand retribution. When wronged, he can be vindictive and blind to his own faults. Nonetheless, he's a saner, more reflective, and certainly more commonsensical Horse than most.`,
        Metal: `Outstanding talent and a knack for basking in the spotlight without developing an inflated ego are two of the Metal Horse's special qualities. It is adroit, forceful, and combative in its driving ambition to achieve success in life. People usually perceive this individual as a true "fighter," someone who is definitely assertive, ready for action, and armed with a strong personal sense of self-belief. Though not truly pugnacious, the Metal Horse prefers to remain vigilant and rarely lowers its guard. Metal Horses carry themselves with confidence, which deters others who might try to obstruct their path.

You might assume that this bravura is merely a defense to conceal sensitivity or a lack of confidence, but it is not. The Metal Horse maintains strict control over its emotions. It must hold itself in check to sustain a dignified and respectable public image. It is always well-dressed in a conservative, tasteful manner. It lives in the "right" neighborhoods, buying or renting in the most proper suburbs or keeping a stylish temporary residence in the more exclusive areas of all the best cities worldwide. The Metal Horse is careful to engage in acceptable, noble sports activities: tennis, golf, sailing, or fencing. It usually marries individuals from "good" families, joins the most prestigious clubs, sends its children to the "right" schools, and dines at the "in" restaurants recommended by the "best" critics.

Yes, our Metal Horse is somewhat of a snob. But it has a solid reason to disdain poor quality and common sports. The Metal Horse thrives on material comfort, which it knows it can only secure for itself and its family if it associates with the right circles, pursues the most lucrative jobs, and is perceived as better-mannered, educated, and dressed than its rivals. The Metal Horse is more ambitious than intelligent, more self-driven than a scud missile... and tougher than tungsten.

It is not entirely fair or accurate to condemn this eager individual so hastily, recklessly categorizing it as a thoughtless, blindly ambitious go-getter. The Metal Horse is nobody's fool. It is unusually quick-witted, bright, and agile. It likes to stay within the boundaries set by society, pays its taxes on time, and rarely cheats. It is always punctual, well-dressed, and often has perfect teeth. Its children never use drugs, and its dog does not bite the postman. You must know at least one Metal Horse; it is that infuriatingly well-put-together person who lives in the lovely flat on the second floor of your building, about whom nobody ever knows anything except that it appears to do everything correctly.

Obviously, the Metal Horse is far from perfect. It has faults, but it conceals them. It has troubles, but keeps them to itself. It has a heart, but it's kept under wraps. The Metal Horse guards its secrets carefully because it fears both pain and the guilt of shame. It's skittish of messy emotional situations and flees every intimate discussion. Its cupboards are in perfect order and its kitchen sink shines. It is wary of what others may think. Its dinner parties are timed to the last toothpick and its car never breaks down. It is determined to appear to be in control in the eyes of its peers. The Metal Horse is also terrified of disorder and even avoids spontaneity. If everything isn't planned in advance—something might go wrong. When the dishes are washed and the sink is scrubbed and the fire's laid then (and only then) the Metal Horse will allow his compulsive little head to lay itself upon the pillow for a well-earned snooze.

This Horse is inherently clumsy. It is constantly tripping over things and almost drowning in its own bathtub. The result? From an early age, it starts polishing its image, planning its time slots, and setting up calm facades to hide its inadequacies. It is a walking time-bomb of potential mistakes and a master of camouflage.

The Metal Horse is a rather robust lover. Though its technical skills may be excellent, it never seems to be doing much more than performing a task well. It's not cold or without physical passion, but it never completely lets go. As its sensitivities must remain hidden, it eschews tenderness and recoils from gentle caressing. If you love one of these effective, ambitious creatures, you will be forced to employ cunning to keep him in bed after lovemaking. No post-coital cuddling or spooning for this individual. The Metal Horse is more likely to make love, then leap up to do the laundry, make a phone call, or turn on the TV.

Of course, it is a serious worker. All professions requiring good social skills, group dynamics, and team integration are perfectly suited for the Metal Horse. It can be an efficient boss or a junior employee, but the Metal Horse will not stay an underling for long. It loves hierarchies and thrives on the challenges of climbing the sturdy ladder to success. It adores material wealth and has an obsession with acquisition. Quality items with pedigrees and historical references line the walls of its house. You never eat from cheap dishes in the Metal Horse's home, and the flowers are always fresh too.

Paradoxically, this Horse deplores routine and dislikes confinement. It is a restless soul who requires change and movement. I do not advise it to take any job that does not require travel. Action is its best friend. The more it does, the healthier and happier the Metal Horse will be. Its need for motion can sometimes hinder the Metal Horse’s enjoyment of a family life. It can make a commitment—but not to anything that doesn't readily evolve. If it feels trapped in a static relationship or family situation where there’s no room for improvement or change, it may bolt. The Metal Horse would prefer to live alone than feel trapped in a no-win marriage or love affair. Some turn to drink when struggling in bad marriages or relationships. For this Horse, divorce is preferable to drugs, gambling, or lifelong depression.

The wise Metal Horse will try yoga and meditation to temper its fever-pitch existence. Otherwise, the stress it generates by living through one of its packed days might push its delicate nervous system over the edge. Emotional collapse is not uncommon in the Metal Horse. Vitamins and a steady diet of grains and vegetables are recommended to aid its sometimes acidic stomach and sluggish digestion. It usually chooses to remain fit, as it adores sport and exercises obsessively.

When at its best, this Horse is productive and active. It is even thrilled by adversity, considering setbacks mere hurdles. Then, when the moment is just right and the multiple endeavors it is pursuing are all ready, the Metal Horse will leap all obstacles with grace and style…and it always lands smoothly and elegantly victorious from its Herculean efforts.

Lastly, this Horse is very kindly—even charitable, dedicating its time and money for communal and group events. Often these activities are Church-oriented, but they might also have to do with philanthropic or philosophical movements. Unusual for a Horse, the Metal Horse can be spiritual. It is attracted not only to religion but capable of expanding its mind in search of philosophical truth. It can succeed in even the most obscure metaphysical realms as a clergyman, teacher, or physician.`,
        Water: `Here we have the most generous of Horses, who dotes unconditionally, bestows fabulous gifts, and showers loved ones with old-fashioned practical favors. It is hospitable, full of sound, practical advice, and brimming with energetic attention. It is superbly intelligent and talented. But the Water Horse is different—mellower, calmer, and more socially inclined than the others. It likes to belong, but it doesn't care if it belongs to the country club and can settle for belonging to its family, or to a group of good friends. Because its days are incredibly busy, it has neither time nor talent for brooding or analysis. Thanks to the Water element, this Horse is not as neurotic, self-involved, nor as angry as other Horses.

In fact, this Horse is a real winner. Every young Horse is drawn toward adulthood by a beacon of ambition. Early awareness of the desire to stand out and rise above its environment, spurs it to leave its family to make its own way. The Water Horse is slightly modified.

Like other Horses, Water Horses also leave home early, but they tend to return before the age of thirty, bearing the fruits of their adventures, to share their good fortune with the family they left behind. A Water Horse may always need to keep a safe distance from its home turf because it doesn't function well when encumbered by standards which are not its own. But it will always be there for its parents, ready to pick up the pieces for siblings in distress or rescue a struggling cousin. Water Horses feel the suffering of others intensely and are not afraid to show their devotion in practical ways.

The Water Horse is gregarious and loves to be surrounded. It likes having many children, enjoys working in groups, and having admirers who watch and applaud while it performs its wondrous tricks of bravura and brilliance. It might get together a tasty dinner for a troop of tired girl scouts or pile everybody into the car for a swim in the nearest waterfall or belt out a few jazz ditties on stage at Carnegie Hall, but whatever it does, the Water Horse is happiest when performing for an adoring audience. It needs to feel wanted and loved—which is what he is really all about. APPLAUSE. APPROVAL. ADORATION.

It would be pleasant if these Horses were duly rewarded for their generosity and compensated for their affability, but that is often not the case. Mostly, the Water Horse goes on giving while his entourage receives but does not completely return the favors. People do not rush about telling each other how selfless their Water Horse friends, parents, or colleagues are. They may be impressed that a Water Horse took on the baking so that twelve hundred schoolchildren could have cake on their picnic. But they are usually baffled when it comes to knowing how to approach the Water Horse with gratitude.

Why? The Water Horse emanates a hard-edged aura of competence and self-confidence which puts people off. Once we have watched him in action and applauded, we would like to throw our arms around the Water Horse's neck and kiss him to death. But something about his demeanour discourages us. He’s a bit standoffish. He makes us feel small. Or are we afraid of disturbing him? Maybe he would rather we applaud and then go home and leave him alone.

As kind, giving, and generous as the Water Horse can be, he is distant and doesn't take kindly to gushing gestures of affection or tenderness. He is (like most Horses) afraid of intimacy. He wants to be admired but hates admitting it. He craves adulation but doesn't believe he deserves it. He goes out of his way to do giant love favors for people and has difficulty accepting a hug for his trouble. He needs to maintain distance from those he helps out. I suspect that the Water Horse is locked inside himself in typical Horse fashion and cannot allow himself the luxury of receiving his share of tenderness. Perhaps he fears he will look silly.

If you love a Water Horse, this aloofness may throw you off your feed. You may feel rejected, unloved and obliged to perform some fancy tricks to get close to this character. Not to worry. The seduction, the ruses and emotional slaloming that the Water Horse demands are worth any self-doubt you may feel. Once you are allowed into the cozy sweet heart of a big old Water Horse, you will feel safely loved back forever ... plus, you will have gained the best friend you could want—for life.

The Water Horse is not introspective. He is practical and is not drawn to the metaphysical. He hates abstraction. He thinks intellectuals are idlers who get paid for doing nothing. He cannot abide laziness—either in himself or in others. He likes his life (and the lives of those who surround him) to be lived on the surface. He enjoys material things and is happy working with his hands, making curtains or re-covering a sofa, building an attic room or driving around the countryside hunting down antique glass or ceramic figurines in obscure little shops. He doesn't require luxury but he likes his comforts to be more than adequate.

The Water Horse is funny too: his jokes are always acute and, when it comes to sarcasm and satire, his comments are right on the button. He has usually mastered the art of seeing through artifice. If you want an opinion on good taste or authenticity, whether with regard to a person or an object you found at a flea market, consult a Water Horse. These folk have impeccable taste and a flair for everything visual from decorating to evaluating old paintings.

Water Horses were born to be bosses. Holding down mundane jobs is a problem for the over-achieving Water Horse. He cannot be subjugated to anyone for long and is especially sensitive to taking orders from bosses he doesn’t respect. He comes off beautifully in any job interview so he gets the job right away. But although he may remain polite and answer dumb requests courteously for the first few weeks, he will soon commit an act of blatant insubordination which usually ends in his early resignation. Job choices for this creature are simple—he can be the boss of anything. Independent careers are what he excels at and he is good at everything from medicine to cuisine, from real estate to accounting, from law to photography, acting, singing or film making. Musicians abound among Water Horses, as do graphic artists and writers. He will certainly be artistic and might even be a genius.

Luckily for him, the Water Horse is among the most adaptable of the zodiac's creatures. When he's down he doesn't lie there for long before getting up and starting to run again towards goals of his own making, leaping hurdle after hurdle and finally making it. Project after project may fail but, one day, because of his strong belief in self and remarkable ability to zero in on his goals and stick to routine, the Water Horse will triumph. Because he likes change and rarely uses the same tactic more than once, he may be exhausted by the time he reaches his goal but whatever gain or joy he derives from his major success will be richly deserved.`
    },
    compatibilities: {
        Rat: `Do not expect any miracles to appear on your path in this relationship. Rats and Horses are well-known adversaries. There will be an initial attraction, a brief honeymoon period, and then a swift descent into bickering and eventual separation. Rats desire power; Horses dislike being told what to do. Rats need to surround themselves with people they can feel protective of, look after, and guide. There is nothing worse for Horses than to feel smothered by some meddling outsider who interferes in everything the Horse does. Horses value freedom and independence; they do not wish to be held accountable. So, in this relationship, Horses had better relax and remain in the background. Do not attempt any grand stunts or public displays of your talents. Of course, you probably will not follow this advice any more than you would follow the Rat’s instructions. Horses can be led to water, but no amount of coaxing, blackmail, or guilt trips will make them ingest a drop if they do not want to.`,
        Ox: `Things are looking up in this partnership. Oxen admire the Horse’s stamina and ability to undertake hard labor without a complaint or a grumble. No interference. No meddling in your business. No directives. However, this relationship is not brilliant for the Horse’s romantic life. The Horse may indeed fall in love, and when they fall, they crash—thunderously. But the more passion the Horse directs towards their chosen Ox, the less the Ox seems to want to become intimate. The Horse can avoid being disappointed in love by simply leaving emotions aside and pursuing goals independently. The professional outlook in this pairing promises nothing but success. As long as the Horse applies consistent effort and demonstrates persistence, the Ox will not only stay out of the way but will applaud, encourage, and, when possible, highly recommend the Horse to any influential people needed to advance their career.`,
        Tiger: `Horses and Tigers are the best of companions. In this relationship, the Horse will feel free to be entirely themselves—the real, headstrong, spirited, talented, outspoken self. Tigers do not mind the Horse’s playfulness and strong will. They, in fact, approve of how Horses manage their lives and are themselves ultimately independent and free-spirited. What the Horse must watch out for is being drawn into crazy schemes, urged to take eccentric trips to far-flung destinations, or dragged into nutty real estate projects without a backward (or forward) glance. The Horse should be cautious of feeling too unrestrained and avoid departing for some fantastical place from which they will not be welcomed upon return. They might instead be severely criticized for being irresponsible, as Tigers tend to encourage eccentric behavior. Discreetly observing their own surroundings, the Horse may be pleasantly surprised to find that a surprising romantic interest lurks in their immediate vicinity. Someone they have known for a while may suddenly take a liking to them. The Horse should not retreat; this could be The One.`,
        "Rabbit": `The Horse is favored by the Cat/Rabbit, who never wants to get in their way. The Horse is all action and brisk movement, always rushing headlong into projects both new and old. The Cat/Rabbit is a more deliberate, reflective sort who, contrary to the Horse, does little to draw attention to themselves. Provided the Horse demonstrates their usual ability for hard work and dedication, the Cat/Rabbit will stay completely out of their way. This relationship is good for the Horse to expand their business, open franchises, buy land, or refurbish or renovate a property or two. The Horse should devote some free time to their art as well—drawing, painting, singing, dancing, filmmaking, photography, sculpture, or ceramics. Any and all artistic pursuits will thrive under the influence of the refined Cat/Rabbit. One small blemish in this otherwise pristine relationship is that the Horse may lose confidence in themselves, possibly due to boredom. This pairing may lack excitement—no great new romance or high living, just work and art. But the Horse should consider themselves lucky because those are the two things they do best.`,
        Dragon: `Dragons maintain a hands-off policy regarding Horses. If the Horse has the good sense never to attempt to steal the spotlight, they will be surprised how positive this relationship can be. There is a hint of marriage—or at least a long-term live-in relationship—in the offing for Horses. Horses are not usually inclined to live full-time with anyone, but when they fall for somebody, they fall hard, and this pairing is favorable for just that kind of passionate abandon. Dragons are famous for celebrations and festivities, and one of those gatherings might just be the Horse’s wedding or, at the very least, their engagement party. Before getting too involved, however, the Horse must ensure that their significant other or future spouse is aware of their penchant for trotting off from time to time into their own realm or even into the ethereal. The Horse should marry someone whose independence quotient harmonizes with their own: a Tiger or a Dog would be best.`,
        Snake: `These two are strongly attracted to each other. The Horse admires the Snake’s natural ease with people and appreciates its considerate, charitable nature. The Snake, on the other hand, likes and respects the Horse’s spiritedness and innate enthusiasm. Their social life will be rich and full. Trouble begins when the Horse realizes that its adored Snake mate is "running around." Promiscuity does not sit well with the straightforward, faithful, devoted Horse. So, the Horse shifts into a mode of recrimination, which forces the Snake to conceal any extracurricular activities more cleverly—but not necessarily to abandon them. The Horse does not handle duplicity well, and storms ensue. The Snake has a generous heart. The Horse is more conservative with money. This disparity will cause some significant arguments. It is best to let the Horse manage the finances and dispense money to the Snake for trivialities. But do not expect the money-loving Snake to accept that arrangement; it wants to spend! The Horse may bolt. Almost everyone is happy with a sensual Snake person in their bed. Horses have little confidence in their sexuality, but Snakes have more than enough to share. They make good, considerate teachers. The match can work if the Horse can learn not to fall apart when the Snake embarks on sensual, romantic interludes, and the Snake can learn to curb its inclination for minor indiscretions.`,
        Horse: `This relationship is a whirlwind of energy, ambition, and mutual admiration, but it can also be a battleground of egos. Two Horses together create a dynamic, action-packed partnership filled with passion and drive. Both are spirited, independent, and determined to carve their own paths, which can lead to a vibrant and exciting life together. They understand each other’s need for freedom, love of action, and fear of failure, making them natural allies in pursuing shared goals. However, the very traits that draw them together can also pull them apart. Both Horses are headstrong and stubborn, refusing to budge when their wills clash. Their shared desire to be in control can lead to power struggles, as neither wants to take a back seat. Their outspoken and sometimes inappropriate verbal exchanges can escalate into heated arguments, especially when both are provoked—and Horses are easily provoked. The relationship can become a rollercoaster of highs and lows, with each Horse’s fiery temperament amplifying the other’s. Financially, this pairing can be a challenge. Both Horses value money and success, but their tendency to act impulsively can lead to reckless spending or risky investments. They need to agree on a clear financial plan to avoid disputes over resources. Romantically, their passion is intense, and their shared love for adventure keeps the spark alive. However, their mutual need for independence can make it hard to maintain intimacy, as both may prioritize personal goals over the relationship. For this match to work, both Horses must learn to compromise—a skill that doesn’t come naturally to them. They should channel their competitive energy into collaborative projects, where their combined talents can shine. If they can temper their arrogance and practice patience, this duo can gallop toward a successful and fulfilling partnership. Without mutual respect and a willingness to rein in their stubbornness, however, they risk running in opposite directions.`,
        Goat: `Charming and graceful, this pair of artistic, creative people can have the world eating out of their hands. The Goat’s inherent beauty and seductive appeal, when combined with the Horse’s elegance and sensuality, form an enviably synergistic couple. Theirs will be a delightful complicity. Unfortunately, neither of these gloriously attractive people is very adept with a calculator. They are both equally improvident, luxury-loving, and even extravagant with spending. Unpaid bills will accumulate, and each will accuse the other of being a spendthrift, leading to a stalemate. Do not expect the Goat to find solutions. Horses may overspend, but they also provide. Goats are determined to be dependent and provided for. The Horse will only tolerate so much of the Goat’s indolence and will soon find the poor Goat a high-paying job and compel it to arrive at the office on time and perform its duties well until death do them part. Once again, the Horse’s incurable need for independence enters the equation. Goats tend to be fickle too. But, even though the Horse understands the Goat’s occasional need for a fling, the more stubborn Goat dislikes sharing its possessions and will react strongly to the Horse's need for freedom. But never mind; arguments are a part of these people’s lives: both are addicted to passionate drama. Romantically, this couple is sound. But when the harsh, overhead light of reality penetrates the veneer of their relationship, the cracks and flaws may prove too numerous for its survival.`,
        Monkey: `Auspicious beginnings encourage these individuals to unite and operate as a team. The versatile Monkey finds wisdom and consideration in the Horse’s personality. The Horse enjoys the Monkey’s charm and energetic spirit. They are truly a complementary pair. After a time, however, they will realize that all they have in common is a desire to help others, a charitable inclination that binds them ever so loosely together. The Horse, of course, always craves action and movement. The Monkey? Well, the Monkey could not care less about staying active: if opportunities arise, so much the better. If not, it can take them or leave them alone. Horses value elegance and desire their lives to be carefully accessorized. Monkeys are bored by the very idea of accessorizing anything and prefer casual attire to dressing up. Monkeys are spontaneous; Horses are deliberate. The Horse is romantic, the Monkey logical. The Horse is sophisticated, the Monkey bohemian and carefree. Monkeys love to converse, but dialogue becomes difficult because Horses find it hard to reveal their inner feelings. A breakdown in communication might be the demise of this relationship. Their sex life usually compensates for much of the strife between them. Although sexual intimacy is not always the Monkey’s strongest suit, Horses succeed in exciting them greatly. The complicity of elaborate sexual games may provide a foundation for this pair to strengthen their union—despite their essential differences.`,
        Rooster: `If there is one thing the Horse hates more than anything, it’s being held back or restrained in any way. The Horse is a doer, an active person with more irons in the fire than a roomful of blacksmiths. They are a runner, a worker, and a striver. Nobody should ever attempt to hold them down. Yet, in this relationship, the Horse must live with the Rooster’s firm grip on their pocketbook and disapproval of their wildest dreams. Roosters are serious, single-minded individuals; they cling to conservative ideas and prefer the traditional to the outlandish in life. The atmosphere of this pairing inclines both to adhere to rules, be thrifty, and stick to tried and true methods. The Horse might be tempted to travel afar to visit tombs and museums, churches, temples, and monuments, as the Rooster doesn’t usually disapprove of travel—especially if the journey leads to somewhere instructional and is not just for "fun." Major purchases (houses, cars, boats, buildings, farms, etc.) are not advisable in this relationship, as money will be generally tight and interest rates quite high. The Horse’s favorite outspoken and outrageous extreme behaviors should be curbed. Romantic indiscretions are also not advisable for Horse people with Roosters.`,
        Dog: `Horses and Dogs belong together. They gallop gaily about the countryside along with scads of children and cats and chickens and ducks. They have a natural affinity, and although of different breeds and species, they could easily be thought of as siblings. This relationship is gracious for Horses. However, the Horse will be called upon to demonstrate a side of themselves that is not frequently seen. The Dog requires involvement in world issues, wanting justice and willing to do almost anything to see it done. They care about the future of the human race. As being engaged in political goings-on has never appealed to the Horse’s free-wheeling, outspoken character, the Horse will be hard-pressed to show that they care who gets to be president or leader of the entire planet. Horses believe all politics is corrupt and want no part of corruption in their straightforward existence. The advice for this pairing is for the Horse to try to care for the Dog’s sake, being more generous of heart and giving to others. The rule in this benevolent relationship is: you get out what you put in.`,
        Pig: `Pig relationships are not among the Horse’s favorites. Horses insist on working long and hard and being visible about it, wanting to be seen as industrious, good, honest, and forthright. Pigs are not slovenly or lazy; they also work, sometimes extremely hard. But Pigs like a good time, enjoying inviting people for meals, drinking a bit too much, and eating delicious culinary concoctions (often of their own making). The Horse does not mind a good time but is not one to waste hours lounging about at the table over a final glass of wine or two and some scrumptious cheeses or dessert. The atmosphere of conviviality in this relationship might irritate the Horse’s restless nerves, as they want action. Doing, going, working, and being busy keeps their mind off more ponderous, irritating, soulful matters. The Horse needs to slow down and relax in this pairing, perhaps taking a lengthy journey in a new sailboat or buying an old barn to renovate in the country. Be busy, but relaxed as well. Watch out for symptoms of depression or other illnesses caused by stress, as the Horse has needed to ease off the accelerator for too long. Enjoy some of the good, clean fun associated with Pigs.`
    },
    futures: {
        "2025": { "year": "Snake", "element": "Wood", "prediction": `This is not the easiest year for Horses. Your new family (read: in-laws) demands much more from you than you are willing to give. Their needs will create dissension and, if you are not careful, could lead to a nasty breakup of your relationship. The Snake’s influence can be laden with half-truths and even fantasies that do not quite align with reality. The Snake longs to believe only its own vision of a given situation and is often reluctant to surrender to reality. So, you may encounter some real obstacles this year in your attempt to get your marriage or long-term live-in relationship off the ground. New beginnings usually sweep clean, but as they age, some of the dirt begins to be swept under the rug or even altogether neglected. The same holds true for a new relationship. Whatever messes are troubling you or your partner must be resolved. And first, they have to be brought out into the open. Sit yourselves down—alone or with a marriage counselor or therapist—and discuss things thoroughly. You will both need to decide where your loyalties lie this year, and it had better not be with the in-laws. A couple is a couple; no intruders are necessary, thank you.` },
        "2026": { "year": "Horse", "element": "Fire", "prediction": `According to Chinese legend, the Horse year is not an excellent one for Horses. Most other signs benefit from their own years, but not the Horse. This will be a troubled and sometimes even dangerous year for you Horse individuals. The perils are not your fault; they are simply present, like bad luck. The best way for you to handle this situation, of course, is to exercise caution in all your activities. Opt out of risky business deals. Do not go trekking in the Himalayas. Cancel your subscription to the Bungee Cord Club and renege on all plans for ski holidays in avalanche season in the Andes. In other words, keep it simple. Stay around home a lot. Busy yourself with domestic projects like baking Christmas cookies or working in the garden—and even then, watch out for household accidents. You could pierce your palm with a tomato stake or dent someone’s car on the way to the market to buy flour and chocolate for cookies. Just be careful; you are walking on eggshells this year. Now, please do not go sulk somewhere and not emerge until this year is over. Do understand that the reason for such a difficult time in your life is so you will learn new lessons; it’s all about helping you to see what it’s like to be a Horse of a different color.` },
        "2027": { "year": "Goat", "element": "Fire", "prediction": `It is about time you received a break from learning new ways to behave and stopped having to be so cautious all the time. Goat years are a breeze for Horses. They bring sunshine into your previously dreary life and encourage you towards ever more intriguing acts and ambitious endeavors. Goats do not demand much from Horses—except that you be strong enough to provide them with a generous back to ride on. You do not mind supporting others; you can handle being depended upon by someone vaguely artistic or too brilliant to be simply idle. The Goat spends its life seeking a pot of gold at the end of the rainbow. He or she knows that you might just be the vehicle to transport them there. This is your chance to go to extremes again. Time to embark on that hike in the Himalayas. Or why not try out several different gambling casinos around the world? Or marry your Cousin Charlie? Do something outrageous. One way or another, under the Goat’s Horse-friendly influence, everything will work out for the best. Even your health will be excellent—as long as you maintain your fitness routine and stick to lean meats, fish, vegetables, and of course… OATS.` },
        "2028": { "year": "Monkey", "element": "Earth", "prediction": `Being of a pragmatic nature, you are not often drawn into shady schemes or led down winding paths where outcomes are not clearly visible. But Monkeys are agile individuals; they are nimble of foot and mind. If you are ever tempted to get involved in anything that deviates from the straight and narrow, it is likely to happen this year. Watch your step. Horses need to work hard to make progress and achieve success. Horses usually do not take kindly to shortcuts. Therefore, should you be tempted away from your usual strict adherence to the rules of striving and toil, you may indeed fail—miserably. When presented with attractive "quick fix" plans to avoid taxes by sheltering your yacht in Panama or opening an offshore bank account, just say NO. There are no free lunches for the hard-driving Horse. Monkey years also threaten your waistline. These nimble-minded creatures cannot keep their hands off food, and if you are not extra careful about monitoring your diet, this year can expand your girth to twice its normal size. In fact, the general message for Horses in Monkey years is: Stick to routine and keep your nose clean.` },
        "2029": { "year": "Rooster", "element": "Earth", "prediction": `If there is one thing you hate more than anything, it’s being held back or restrained in any way. You are a doer, an active person with more irons in the fire than a roomful of blacksmiths. You are a runner, a worker, and a striver. Nobody should ever attempt to hold you down. Yet, you do have to live through this Rooster year where we all feel somewhat constrained by the Rooster’s firm grip on his pocketbook and his disapproval of our wildest dreams. Roosters are serious, single-minded individuals; they cling to conservative ideas and prefer the traditional to the outlandish in life. The atmosphere this year, then, inclines us all to adhere to rules, be thrifty, and stick to tried and true methods. You might, however, be tempted this Rooster year to travel afar to visit tombs and museums, churches, temples, and monuments. The Rooster doesn’t usually disapprove of travel—especially if the journey leads to somewhere instructional and is not just for "fun." I wouldn’t advise you to make any major purchases this year (houses, cars, boats, buildings, farms, etc.) because money will be generally tight and interest rates quite high. All your favorite outspoken and outrageous extreme behaviors should be curbed. Do not try dabbling in clandestine love affairs either. Romantic indiscretions are simply not advisable for Horse people in Rooster years.` },
        "2030": { "year": "Dog", "element": "Metal", "prediction": `Horses and Dogs belong together. You gallop gaily about the countryside along with scads of children and cats and chickens and ducks. You two have a natural affinity, and although of different breeds and species, you could easily be thought of as siblings. This year, then, will be a gracious year for Horses. You will, however, be called upon to demonstrate a side of yourself that we do not frequently see. The Dog requires that we involve ourselves in world issues. Dogs want justice and will do almost anything to see that justice is done. They care about the future of the human race. As being engaged in political goings-on has never appealed to the Horse’s free-wheeling, outspoken character, you Horse individuals will be hard-pressed to show that you care who gets to be president or, for that matter, leader of the entire Planet. Why? Because you do not care a fig. You know in your heart that all politics is corrupt, and you want no part of corruption anywhere in your straightforward existence. My advice for you this year is to attempt to try to care. Just do it for your pal, the Dog’s, sake. Be more generous of heart, more giving, and loving to others. Remember, you get out what you put in. That’s the rule in the benevolent Dog year.` },
        "2031": { "year": "Pig", "element": "Metal", "prediction": `Pig years are not among your favorites. Horses insist on working long and hard and being visible about it. You want to be seen as industrious. You need us to know what a good person you are—and how honest and forthright as well. Pigs are not slovenly or lazy; they also work, and sometimes they work extremely hard. But Pigs like a good time. They enjoy inviting people in for a meal, drinking a bit too much, and eating delicious culinary concoctions (often of their own making). You do not mind a good time, but you are not one to waste hours lounging about at table over a final glass of wine or two and some scrumptious cheeses or dessert. The atmosphere of conviviality prevalent in the Pig year, then, might irritate your restless nerves. You want action. Doing, going, working, and being busy keeps your mind off more ponderous, irritating, soulful matters. So this year, you need to slow down and relax. Take a lengthy journey in your new sailboat or buy yourself an old barn to renovate in the country. Be busy, but be relaxed as well. Watch out this year for symptoms of depression or other illnesses caused by stress. You have needed to ease off the accelerator for too long. Take a break and enjoy some of the good, clean fun associated with all Pig years.` },
        "2032": { "year": "Rat", "element": "Water", "prediction": `Do not expect any miracles to appear on your path this year. Rats and Horses are well-known adversaries. There will be an initial attraction, a brief honeymoon period, and then a swift descent into bickering and eventual separation. Rats desire power; you dislike being told what to do. Do you understand the dynamic? Rats need to surround themselves with people they can feel protective of, look after, and guide. There is nothing worse for Horses than to feel smothered by some meddling outsider who interferes in everything the Horse does. Horses value freedom and independence; they do not wish to be held accountable. So, in this Rat year, you Horse individuals had better relax. Remain in the background. Do not attempt any grand stunts or public displays of your talents. Of course, you probably will not follow my advice any more than you would follow the Rat’s instructions. Horses can be led to water, but we cannot make them take even a tiny sip if they do not want to. No amount of coaxing, blackmail, or guilt trips will make them ingest a drop. So, Horses… this Rat year will be a struggle. You would be better off retreating to the countryside for the duration. But as you will not heed my good counsel… as they say for good luck in the theater, "Break a leg."` },
        "2033": { "year": "Ox", "element": "Water", "prediction": `Things are looking up. Oxen admire your stamina and ability to undertake hard labor without a complaint or a grumble. This then should be a terrific year for Horses. No interference. No meddling in your business. No directives. However, Ox years are not brilliant for the Horse’s romantic life. You may indeed fall in love this year. And when you fall, you crash—thunderously. But this year, the more passion you direct towards your chosen significant other, the less that person seems to want to become intimate with you. You can avoid being disappointed in love by simply leaving your emotions aside and pursuing your goals independently. Your professional outlook promises nothing but success. As long as you apply consistent effort and demonstrate persistence, the Ox will not only stay out of your way but will applaud you, encourage you, and when it can, will highly recommend you to any influential people you may need to know to advance your career. Health? Nothing serious or life-threatening is imminent. But you really ought to look after yourself better. Horses tend to think they are invincible and rarely, if ever, bother consulting doctors or visiting other health practitioners. Avoiding the symptoms you have been experiencing for far too long without a medical opinion or two could lead to a chronic illness that will remain with you for at least the next twelve Chinese years.` },
        "2034": { "year": "Tiger", "element": "Wood", "prediction": `You are in for some major alterations in everything from your romantic situation to your actual lifestyle. Tigers require change; it’s in their genes. Horses and Tigers are the best of companions. In the Tiger year, you will feel free to be entirely yourself—the real you: the headstrong, spirited, talented, outspoken you. You see, Tigers do not mind your playfulness and strong will. They, in fact, approve of how Horses manage their lives and are themselves ultimately independent and free-spirited. What you do have to watch out for in Tiger years is being drawn into crazy schemes, urged to take eccentric trips to far-flung destinations, or dragged into nutty real estate projects without a backward (or forward) glance. Be cautious of feeling too unrestrained. Avoid departing for some fantastical place from which you will not be welcomed upon your return. You might instead be severely criticized for being irresponsible, as Tigers tend to encourage eccentric behavior. Discreetly observe your own surroundings this year. If you do, you will be pleasantly surprised to find that a surprising romantic interest lurks in your immediate vicinity. Someone you have known for a while will suddenly take a liking to you. Do not retreat; this could be The One.` },
        "2035": { "year": "Rabbit", "element": "Wood", "prediction": `You are favored by the Cat/Rabbit who never wants to get in your way. You are all action and brisk movement, always rushing headlong into projects both new and old. The Cat/Rabbit is a more deliberate, reflective sort who, contrary to you, does little to draw attention to him or herself. Provided you demonstrate your usual ability for hard work and dedication to it, the Cat/Rabbit will stay completely out of your way. This is a good year for you to expand your business, open some franchises, buy land, refurbish or renovate a property or two. Devote some of your free time to your art as well. Drawing and painting. Singing and dancing. Filmmaking or photography or sculpture or ceramics… any and all artistic pursuits will thrive under the influence of the refined Cat/Rabbit. One small blemish on the otherwise pristine face of this Cat/Rabbit year… you may lose confidence in yourself. This sudden slide into melancholy or self-doubt could be caused by boredom. This is not an exciting year. No great new romance. No terminal illnesses. Not much high living. Just work and art. But consider yourself lucky because those are the two things you do best.` },
        "2036": { "year": "Dragon", "element": "Fire", "prediction": `Here is yet another year in which the ruler maintains a hands-off policy regarding you. Dragons do not meddle much with Horses. If you have the good sense never to attempt to steal the spotlight this year, you will be surprised how positive this twelve-month period will turn out to be. First of all, there is a hint of marriage—or at least a long-term live-in relationship—in the offing for Horses. You are not usually inclined to live full-time with anyone. But when you fall for somebody, you fall hard, and this year is favorable for just that kind of passionate abandon. Dragon years are famous for celebrations and festivities. One of those gatherings might just be your wedding or, at the very least, your engagement party. Before you get too involved, however, I must warn you that part of the Horse’s problem with intimacy stems from the fact that you cannot be happily confined for long. Make absolutely certain that your significant other or future spouse is aware of your penchant for trotting off from time to time into your own realm or even into the ethereal. Marry someone whose independence quotient harmonizes with your own: a Tiger or a Dog would be best. Second best? Who wants second best?` }
    }
};
