
export const tiger = {
    introduction: `Honorable Tiger, noble and fearless, you are respected for your courage and simultaneously feared for your ferocity and persistent lack of moderation. Like a raging river, you constantly overflow your boundaries. Where are you rushing to with such haste? Can you not take just one tiny glance before you pounce? Try to slow down; practice a little restraint. Stop being so devastatingly attractive; it is exhausting.

Of course, some individuals find you so daring and spirited that they wish to join you and experience the adventure. But you, dear Tiger, are a daring solitary individual. The top is the only place you desire to be. You actively seek danger. The more formidable the adversary, the more dramatic and catastrophic the situation, the broader your Tigerish grin becomes. Your unpredictability, disregard for rules, self-sufficiency, and carefree swagger could ultimately be your downfall.

In matters of the heart, you are excessively demanding. However, you are certainly not dull. You get along best with devoted Dogs, independent Horses, and complicit Dragons also find loving you quite delightful. Monkeys admire you, but remember—Monkeys can be cunning. Whatever you do, do not become involved with a tempestuous Tiger like yourself; you are lucky, but not that fortunate.

You will navigate your youth with ease. But by the age of thirty-five, the excesses of half a lifetime may begin to catch up with you. Bring yourself to order by forty, and by the time you reach fifty, you will feel revitalized, prepared for a productive old age. A piece of advice? Go ahead and accept the position as a five-star general, but select your lieutenants wisely—you will require much loyal counsel.`,
    elements: {
        Wood: `Energetic and resilient, the Wood Tiger is a hyper-creative innovator who bounds around like a frenzied dervish, leaping unharmed in and out of monumental vats of scalding hot water. This Tiger lacks the cunning and stealth of more subtle Tigers. It is sociable, direct, and constantly yearns to undertake the most ambitious projects and publicly express its extraordinary views, both of the world and of itself!

There is a positive aspect to the Wood Tiger's impulsive behavior. With so many endeavors in progress simultaneously, it is perpetually busy juggling, planning, and strategizing. It is never bored. The Wood Tiger is delighted when its alarm rings in the morning, as it can almost anticipate the diverse possibilities for expansion and immediate involvement in new deals that each new day offers.

All Tigers enjoy change, but this one is addicted to it. The mere thought of purchasing a loaf of bread from a new shop or taking a different route to the hardware store sends shivers of anticipation down its striped spine. You will never find it philosophizing or languidly daydreaming. The Wood Tiger has an extremely difficult time sitting still. It is also amiable and quite easy to get along with, but it is proud and resents it when others attempt to direct or advise it.

This individual is not an intellectual, but it thinks brilliantly on its feet. It is impatient with lofty idealism and theoretical discussions. It prefers to get straight to the task at hand and complete it—the faster, the better.

It believes it can accomplish everything—and enjoys seeing it done well. Furthermore, it thinks you should not only follow it and believe in it, but to demonstrate your loyalty, you should not hesitate to invest your money in its ventures. The Wood Tiger is a world-beater but often feels frustrated because it cannot find allies as fearless as itself. Its perception of the world is highly personal, sometimes incisive, and often witty. Part of the charm of this magnetic Tiger lies in its never taking itself or anyone else very seriously.

The Wood Tiger's devil-may-care approach does not align with its earnest desire to find a life's work or a true vocation that genuinely suits it. It is constantly torn between settling down and rampaging about, activating its charm and dispensing unsolicited advice to its devoted admirers. The Wood Tiger cannot resist even the slightest hint of an opportunity to shine, to captivate, and to convince others that it is correct.

It is quick to anger and just as swift to calm down. It is a charming, fortunate person who can be taken anywhere at all levels of society without causing embarrassment. It loves all types of people and is tolerant and democratic in its choice of friends and partners, making it a wonderful addition to any social gathering. It always has many clever things to say and a multitude of obscure ideas to contribute to any conversation. The Wood Tiger is generous and will shower its loved ones with comforts. But it is also selfish and, in all human interactions, demands the role of Top Tiger.

What this Tiger requires is a strong, interesting, and stable mate who can hold its attention and compel it to focus diligently. If the home life of the Wood Tiger is sufficiently loving, cozy—and disciplined—it can achieve great things.

The best way to deal with this willful yet lovable, elusive individual is, regrettably, to manipulate it. Telling a Wood Tiger directly what you think of its grandiose delusions or criticizing its ill-conceived plans head-on may result in little more than a black eye or, at best, a wounded ego.

Flatter this daring character, and it will follow you anywhere—at least until something more enticing comes along.`,
        Fire: `The Fire Tiger is a charismatic, highly dramatic, and sensual leader. Fire imbues the vibrantly impressive Tiger with even more dynamism and vigor. It is as energetic, if not more so, than its Tiger siblings. However, its power often outpaces its good judgment. It is recklessly extravagant with its strengths and overdoes and over-achieves everything it undertakes. The Fire Tiger simply refuses to conserve its own vitality. It pushes, strains, and forces itself through the most challenging obstacles for the sake of its brave ideals, exhausting itself to give form to projects in which it believes almost too fervently.

Sleepless nights are the norm rather than the exception. Erratic dietary habits and excessive sexual escapades are the fuel that powers this powerhouse's constantly revving engine.

From the age of fifty onwards (if it lives that long), the Fire Tiger would be well advised to slow down, take things easy, stabilize its private life, and engage in a consistent program of healthy diet and exercise or yoga. After fifty, it should content itself with delegating authority and managing its vast empires from behind the scenes. It should cultivate hobbies and/or take up meditation. To lead a full and healthy life in its later years, it must narrow its scope of action and find ways to calm its overactive mind. Otherwise, it will be taking a great risk: its nerves may suddenly give out, its heart may suffer an attack, or a stroke may cripple it. I do not even want to contemplate the extreme irritability of a bedridden Fire Tiger.

The Fire Tiger is also a revolutionary. It desires change and is not afraid to initiate it, manage it, and promote it to the public. Consider what Hugh Hefner accomplished in America with the Playboy philosophy. Not only did he establish a magazine, he transformed people's views on many aspects of their sex lives. The same applies to someone like Edouard Leclerc in France. He built a supermarket empire, defied government rules and regulations, undercut and outsold everyone else, and never ceased to be outspoken about it. Then there is Martin Gray, the man who survived the Warsaw Ghetto and wrote a book about it. Afterward, he lost his wife and three children in a forest fire in the South of France and established a foundation to preserve forests. At well over sixty, Martin Gray headed a foundation for global preservation and unity. The Fire Tiger expresses itself freely and openly and is unmoved by disapproving critics who would see it sanctioned for its outrageous ideas. The Fire Tiger is a resilient individual. It devises grand plans effortlessly and can execute them better than almost any other Tiger. Most Fire Tigers either make a world-class impact or perish in the attempt.

Imprudent as this Fire Tiger may be, and as often as it finds itself embroiled in difficulties, it is remarkably resilient. It is almost as if adversity recharges the Fire Tiger's energy. Not only does it desire to be the first and the best, it is always ready to re-enter the arena after being repeatedly defeated. The Fire Tiger possesses immense courage.

The home life of the Fire Tiger will be disrupted by its constant movement. These individuals do not typically marry young. For the sensual, passionate Fire Tiger lover, marriage is an inevitable part of plan B—the period of slowing down. Its sexually liberal youth represents an immature approach to sex, and the element of conquest remains with the Fire Tiger longer than with most. Perhaps in youth, it is too preoccupied with world-altering projects to dedicate sufficient time to long-lasting and profound emotional exchange, or perhaps it is a classic late bloomer. Whatever the reason, do not be surprised if you encounter a sixty-year-old Fire Tiger with a couple of children still in strollers.

The Fire Tiger values honesty and wishes to be regarded as fair and just. However, if provoked, it is capable of deception and even ruthlessness. It does not tolerate foolishness and will swiftly leave any detractors behind without a backward glance. It believes that the ends invariably justify the means. The Fire Tiger knows that its schemes and ideas will improve humanity's condition and never questions its motives or allows self-doubt to hinder its progress.`,
        Earth: `We twentieth-century Earth Tigers have a grim history of premature death resulting from sudden and tragic events—suicides, accidents, and even murder. In China, the Earth Tiger is known as the thinking person's Tiger. It is believed to be less restless, more determined, and wiser than its counterparts. Earth Tigers make excellent political leaders or top business executives. The desire to lead is strong, as is the desire to occupy a respected position in society. The spirit here is independent, self-reliant, and fiercely individualistic. Despite the calming influence of the Earth element, this Tiger is impulsive and headstrong. It devises scheme after scheme and rushes around, flashing its engaging smile and captivating everyone. However, it generally avoids complete ruin because it seeks advice before acting on its rash impulses. It consults its friends, its lawyer, doctor, and even the neighbors before making significant decisions.

Another distinctive quality about this Tiger is its un-Tiger-like ability to relax and do nothing. Most Tigers find it difficult to sit still, but Earth Tigers can gaze into the distance for hours, contemplating and dreaming of greater moments. They are the most relaxed and temperate of all Tigers.

The Earth Tiger enjoys learning new disciplines and formulating logical plans for the betterment of its own life and the lives of others. Because of this, it is sometimes perceived as meddlesome and overly interfering in the lives of those it cherishes.

Earth Tigers are pillars of strength and champions of justice. They cannot tolerate unfair practices and will fight against social injustice and combat ethical wrongdoing. Like a combination of a terrier and an elephant, the Earth Tiger seizes an idea and holds onto it indefinitely if necessary, because it never forgets. Vengeance will not leave its mind until justice has been served. Nothing brings the Earth Tiger greater satisfaction than demanding and receiving payment for a long-overdue moral debt.

The Earth Tiger is wildly passionate in love. It adores both seducing and being seduced. It is a playful individual who knows how to indulge its mate in imaginative love games. It is relatively faithful and true and prefers not to be informed of its mate's infidelities, as it dislikes being made a fool of. If mistreated, an Earth Tiger can bound away from a negative relationship without even a flicker of regret. It requires total reciprocity in love and rarely allows its heart to rule its head. Unrequited love? It seems like a shameful waste of its precious time.

The health pattern of most Earth Tigers is inconsistent and uneven, but they are fundamentally strong. Although danger befalls them in surprising and terrifying ways, they can survive astonishing ordeals and tend to land safely on all four paws. They assume leadership with ease, enjoy having a good time, and do not give much quarter to self-pity or whining. The Earth Tiger is dutiful and will pay dearly to uphold its beliefs and ideals. But, when wronged, it can also be ruthless and callously cruel. It is purposeful and unyieldingly independent. This last quality can indeed be a flaw, as in its resolute way, the Earth Tiger often ends up stubbornly adhering to its views and feelings without giving space to others, whose fervent desire to love it can never be as grand as its desire to remain aloof.`,
        Metal: `The Metal Tiger is principled, straightforward, conservative, and energetic, yet it retains its Tiger charm and powerful drive. It is a powerhouse of energy and a performer of grand deeds. But it is somehow more serious than most Tigers. It is not one to leave projects unfinished. It is a bulldozer with the engine of a tank and the scope of at least sixteen aircraft carriers.

The Metal Tiger has a reputation for making the right decisions at the opportune moment and will patiently wait for the precise instant to strike. This behavior can sometimes appear to be procrastination, but its hesitation is a form of strategy. It lies in wait, occasionally raising an eyelid to survey the scene. Then it rises, yawns, stretches its limbs, tenses its muscles, and acts decisively!

On the other hand, if the Metal Tiger has to wait for someone to appear or for something to happen, it becomes frantic. It desires what it wants when it wants it and struggles to understand why others might not wish to adhere to its schedule. It dislikes obeying, yet insists on obedience from others.

This Tiger also possesses a somber inclination. From a young age, it may be fascinated by weapons and intrigued by death and symbols of mortality. It faces a lifelong struggle to suppress this tendency. The Metal Tiger needs to surround itself with optimistic people who keep its mind focused on the positive aspects of life. Otherwise, a predisposition for self-destruction, blind heroism, and a taste for danger can lead it into serious—even fatal—accidents.

The Metal-born Tiger child should be raised in harmonious surroundings, taught to love peace and cherish its fellow human beings. Wise adult choices should lead to harmony and a close-knit family life. Tensions within the family or a tumultuous marriage could disrupt its mental stability. Divorce would be preferable to a stressful marriage.

On the surface, the Metal Tiger appears optimistic, cheerful, and full of humanity. And, on a grand scale, it is. Yet it is not always compassionate in one-to-one situations. You cannot persuade it to sit down and express its thoughts or discuss its feelings. Other people's needs and the complexities of emotional situations seem to escape this Tiger's notice. It can be callous and heartless in love and in family relationships. Yet if its cold-heartedness is remarked upon or criticized, it simply dismisses it with a laugh, pretending it does not exist. There is no remedy for the Metal Tiger's emotional shortcomings. My advice is to adapt to it. Do not take its sharp comments and lack of empathy too seriously, and the Metal Tiger will never seek your sympathy—it sees no use for it.

This Tiger is a creature of legendary magnetism—not classically handsome or even overtly sexy, but more like a charismatic Pied Piper who instinctively knows how to convince its audience and enlist the minds of others in its pursuit of superiority. It is no surprise that de Gaulle was a Metal Tiger. This is a formidable leader who stops at nothing to achieve its objectives. It knows precisely where to strike at the most vulnerable point.

The Metal Tiger desires to improve the world. It will not accept advice or listen to any condemnation of its often unreasonable methods to achieve its goals. For the Metal Tiger, any deception or manipulation is acceptable in the pursuit of victory. And for it, the conflict is always ongoing: right versus wrong, good versus evil, them versus him. It is right, and they are wrong.`,
        Water: `Water Tigers exhibit smooth, refined manners and appear to lead a charmed life. Great personal success, often achieved early in life, characterizes their existence. This Tiger is a lovable and loving creature, whose strength of will and determination to gain both respect and power are admirable. People honor and esteem the Water Tiger. It is more stable and leads a more balanced life than many of its fellow Tigers. It is often artistically inclined and capable of performing in public. Water Tigers tend to be musical and know how to imitate accents and speech patterns with remarkable accuracy. Possessing a good ear makes them natural linguists. Travel appeals to their preference for effortless adventure; they prefer to journey first class.

Long-term discipline is not always a Tiger's strong suit, but the Water Tiger is capable of sustained diligence in the accomplishment of work projects. It also boasts a socially pleasing personality and enjoys being with groups, telling jokes, and displaying its seductive talents. As this Tiger loves company, it desires to be a family-oriented person. It is reliable and takes responsibility for its relatives and looks after its home.

The Water Tiger is known for its sense of fairness. Unlike some Tigers who cannot tolerate advice or criticism, it is able to view its own shortcomings objectively. Its open-minded approach to difficult issues might lead it to pursue the study of law. It would make an excellent magistrate; its judgments would be unbiased and humane.

Water Tigers are not as intensely vain or ambitious as other Tigers. Scholarly pursuits such as philosophy, languages, and comparative literature are possible, but it is the entertainment professions—especially those concerned with music and communication—which will ensure both the Water Tiger's career stability and bring it joy. Failing success on the stage or screen, it might choose to be a professor, a literary agent, or even a promoter of concerts or other spectacles.

Although they make excellent performers, these Tigers do not crave to be constantly in the spotlight during every waking moment of their lives. They can work contentedly behind the scenes, creating, inventing, and planning. An eager, clear-thinking Water Tiger is a welcome addition to any group effort.

This Tiger is mostly a virtuous creature whose greatest flaw is its rare but terrifying rage. The Tiger cannot tolerate betrayal and will react impulsively when it falls victim to it. The Water Tiger appears calm and unruffled, affecting a smooth, cheerful exterior. It is everyone's friend—until it is wronged. The bitter anger that follows is ruthless and leads to a long-term quest for revenge—a dangerous trait!

Cultivate the friendship of this Tiger. Enjoy its love and bask in its charming company. Accept its proposal to collaborate. But do not try to harm it—or it will turn you into a puree and spread you on its toast for breakfast.`
    },
    compatibilities: {
        "Rat": "Upon their initial meeting, these two immediately charm each other. The Rat finds the Tiger captivating and would love to show it off, while the confident Tiger is amused by the Rat's lively conversation and vibrant sense of humor. However, friction is likely to develop in the long term. After the initial spark of love, these two will begin to find faults with each other. The boisterous, adventurous Tiger will constantly seek excitement—venturing on safari to Kenya, then moving on to San Francisco to experience the next earthquake. The more domestic Rat will eventually grow to despise the sight of suitcases. The Tiger pursues instability, drawn by danger and the prospect of having a new job every year. Everything presents a challenge to this aggressive creature. The Rat will not always find the Tiger's inconsistencies appealing and will be plagued by worry. The Rat's mental stability largely depends on material security, and with the Tiger constantly changing jobs, the Rat will fret over finances. For their relationship to endure, both must remember the initial reasons that drew them together. They have much to discuss and agree on many subjects. If the Rat can recall how the Tiger captivatingly entered his or her life, and the Tiger can continue to appreciate the Rat's powers of seduction, there is hope for an exciting, long-lasting marriage.",
        "Ox": "This pairing is disastrous. No matter how you analyze it, this combination is destined for a tumultuous journey. Both possess an unyielding will, supported by the capacity to exert it. Equally self-possessed and determined, the stubborn Ox and the temperamental Tiger are better known as adversaries than as collaborators. Frankly, this quarrelsome duo is best suited for entanglement within a boxing ring. Often, the Tiger disrupts the Ox's tranquil day by instigating trouble. The stoical Ox desires only to remain close to home and continue its steady work. It must exercise considerable patience with the boisterous Tiger, and the Ox finds that exhausting. The rebellious Tiger roars off to a trade union demonstration, complaining bitterly about the mundane, dreary Ox, while the Ox intimidates the Tiger, accusing it of everything from incurable restlessness to outright insanity. If a third round of conflict occurs in the bedroom, there is hope for reconciliation. The Tiger's raw sensuality melts the Ox's icy resistance. With the Tiger, the inhibited Ox feels liberated. Twenty-four-hour truces may result. Even so, this union is best suited for friendship or a business partnership, where dual strong wills can achieve genuine progress. The Tiger/Ox emotional match is a constant struggle. It is not romantically promising.",
        "Tiger": "Two Tigers? Prepare for disappointment! Tigers fervently believe in love at first sight and may enthusiastically pounce on each other. Yes, a Tiger pairing is filled with immediate excitement, quick solutions, and clever strategies. But there is a fundamental issue: while both Tigers are out transforming the world, who is managing the household? Candlelight dinners, vibrant, witty foreplay, banter, and excitement. Decisions like 'My place or yours?' are rapidly made. Groans, sighs, the sound of zippers, and tearing clothes—twin Tigers are so aroused they never make it to the bed. They consume each other. Afterward, they will sip champagne and discuss the fate of the world. Their intense embraces transform into passionate arguments. Perpetually in conflict, the Tiger twins are messily content. Come morning, two Tigers retreat to their respective lairs, refresh themselves, and dash off to work. No time is wasted, and no extra romantic conversation clouds the clear purpose of a busy day. Tigers are inveterate meddlers, always inserting themselves where they should refrain. Two Tigers will contradict and wrongly advise each other constantly, leaving no alternative but to endure perpetual conflict. Help! Perhaps they should forgo marriage. A love affair will unfold in fast-forward mode and promises to be exceptionally dynamic. But this marriage is unlikely to be peaceful, long-lasting, or productive. And... God help the Tiger cubs. The insecurity! The ever-changing residences and decor. Ugh!",
        "Rabbit": "This is a clash of styles. This couple might very possibly enter into a so-called 'marriage of convenience,' but underneath, a silent tension boils, screaming, 'Get me out of here!' In a Tiger/Cat union, it is the Tiger who is silently screaming. What then? The Cat usually possesses the money, and the Tiger, who married the Cat for financial gain, is busy experiencing a nervous breakdown. Tigers live for change and victory. Cats dream only of peace and quiet. Do you understand the situation? There is no common ground. Attempting to outwit each other, these two felines stealthily compete for dominance in the household. The Tiger approaches this with characteristic self-serving vengeance, and the Cat skulks around the house seeking opportunities to trap the Tiger. Imagine two cunning cats under the same roof; they merely tolerate each other. An occasional playful interlude can devolve into a scratching, hissing brawl. Cats require security and construct their nests with refinement and taste. The Tiger might enjoy these surroundings but, unlike the Cat, the Tiger craves change and prefers a more bohemian lifestyle. The seductive Tiger might be tempted to seize some of the Cat's money and dash off to the Amazon, leaving only a deep skid mark outside the Swiss bank. Even in bed, this pair is unlikely to be compatible. The Tiger is aggressive, possessing such a raw, frank, and forceful sexuality that the Cat's delicate sensuality is overwhelmed. Cats require gentle persuasion, seductive, slow-moving lovers, and Tigers are ill-suited to satisfy this need. I perceive the Cat/Tiger match as either an intense summer romance or perhaps a long-lived 'loving friendship' in which they occasionally engage intimately for old times' sake. Marriage? Only if the Cat has a private income and protects it from the Tiger's extravagant tendencies.",
        "Dragon": "This relationship is highly sexual! The Tiger/Dragon romantic connection warrants serious consideration. Combined, their strength is almost excessive, and their energy is enough to power several large generating stations. There is an abundance of EGO prominently displayed in red neon around this couple. Both overbearing and self-driven, they are each a bit too much. But as a pair, they can achieve great success. Despite an excess of assertive power, this combination coexists peacefully. Mutual respect and admiration counterbalance the anticipated conflicts. The dashing Dragon craves constant flattery and applause. However, the strong-minded Tiger finds the pontificating Dragon tiresome and subtly diverts the spotlight. The Tiger is undaunted by fire-breathing theatrics; in fact, the intrepid Tiger enjoys a good shouting match and respects a worthy opponent. The generous Dragon is amused by and tolerates the Tiger's love of danger and impulsive behavior. In short, these two get along well. The Tiger with Dragon is not merely a sensual match. They carry themselves with boldness and flair. An air of wildness permeates everything they do. People flock to their home to bask in their aura and partake in the exhilaration of their adventurous love. Not afraid to share power, they take turns occupying the dominant position, with collaboration taking precedence over their individual roles. This relationship is suitable for marriage. Battles will be fought, but ultimately, the force of their attraction ensures they will remain lovers for life. Entwined in their own whirlwind of passion and intense sexual intimacy, this couple understands the path to ecstasy. The Dragon ignites the spirited Tiger, and the voracious Tiger consumes the dashing Dragon's scorching fire. Enjoy!",
        "Snake": "The elusive Snake and the tempestuous Tiger are irresistibly drawn to each other, but this union is not advisable. A Tiger/Snake pairing can be a disastrous alliance. As different as black and white, yin and yang, the Tiger/Snake combination simply does not blend. Should either of you be unfortunate enough to fall for the other, a preliminary restraining order could save you from catastrophes. If not, here is what to expect: The slow-moving Snake will inflict tremendous frustration upon the energetic Tiger's psyche. Initially, the jungle predator mistakenly perceives the enchanting serpent as quiet and submissive, and attempts to dominate. But reptiles do not respond well to bullying; they retaliate. Snakes are aloof, independent-minded, and strategic masterminds. Haughty indifference and disdain are among their sharpest weapons. They are also prone to repeated instances of infidelity, which will certainly shatter a Tiger mate's considerable ego. The impressive tantrums of the Tiger can make the Snake's calm, reflective, philosophical life miserable. Equally magnetic, Snakes and Tigers compete for attention. The Tiger does so aggressively, and the Snake slyly bewitches. At their own cocktail party, Tiger/Snake hosts may appear quarrelsome. The Tiger recounts stories about its days in the Sinai desert. The Snake subtly encroaches on the Tiger's territory, captivating the company with the Dance of the Seven Veils, learned (coincidentally) in the Sinai desert. Outmaneuvered, the Tiger loudly outdoes the Snake, recounting further desert expeditions. Subdued, the Snake joins the applause, but adds, in a cultivated, soft-spoken voice, that everything the Tiger knows about deserts was learned from the Snake. Tigers are fast and alert, while Snakes are quiet and deliberate thinkers. Tigers are impulsive and may act heedlessly. Snakes rely almost solely on intuition and take things slowly. These creatures may cohabit for sensual pleasure, but they do not see eye to eye. Sexual intimacy? The Snake's need for beautiful, romantic foreplay is denied by an aggressive Tiger, who simply gets down to business. It is best to abstain!",
        "Horse": "This pairing is auspicious, to say the least. Both individuals possess unruly natures. Individually, they are independent. They might clash, but the attraction between them is strong, as is their mutual respect. In love, they transform into delicate passion flowers of vulnerability. As a loving couple, their passion knows few limits. The Tiger and the Horse are equally inventive and creative. In family matters, the Horse's conservatism curbs the Tiger's impulsiveness. They work diligently together to raise a fine family in a proper manner, yet, thanks to the Tiger's rebellious spirit, the children will receive some relief from the seriousness of the Horse's approach. Both are optimistic and strong. Typically, if one experiences a period of low spirits, the Horse is cheerful and the Tiger is down, or vice versa. And there is no boredom here either. These two are active, passionate individuals who embrace life. Unless one learns to be practical with money, they may face financial crises. Both know how to earn, and both love to spend. The initial sexual attraction is intense, and they are both imaginative and faithful enough to keep intimacy exciting over the long term. This relationship can endure.",
        "Goat": "This union is among the worst possible known to Chinese astrologers. Although the couple may have a fabulous start (in bed), from that point onward, it is entirely downhill. The practical aspects simply do not work out. The Goat is charming, beautifully seductive, and loving. The Tiger embodies passion and courage. But who will provide for the household? In this family, no one desires that responsibility. No concessions are made. The Goat remains relaxed while the ambitious Tiger creates a commotion. What began as a great passion ends in lifelong misunderstanding and bitterness. Affairs? Yes. Marriage? Abstinence is advised.",
        "Monkey": "These two make eager lovers. Initially, they will frequently engage in passionate encounters, achieving astonishing feats of extreme intimacy, but in the long run, the ardor may naturally diminish, because Tigers dislike being clung to—and inherently neurotic Monkeys do not know how not to cling. The strong intellectual connection between Tigers and Monkeys frequently keeps them together, regardless. The Tiger admires the Monkey’s keen strategic insight, and the Monkey enjoys and applauds the Tiger’s spirited wit and audacity. The Monkey gives the Tiger many presents and accolades. The Tiger gives the Monkey courage and encouragement. These two share an easy common perspective and, even if they cannot keep the romantic flame burning, will go far together as lifelong companions. Except… the Chinese say that the Tiger should be cautious. Traditionally, the Monkey is the Tiger’s natural adversary. I do not advise marriage.",
        "Rooster": "I do not recommend this pair for marriage. Both individuals are aggressive and opinionated; neither will yield easily. The atmosphere will be tense, and most arguments will be one-sided. Conflicts and clashes are guaranteed to impede the harmonious progress of this couple. Tigers recover quickly and forget every harsh word that was spoken. But Roosters harbor grudges and cannot forget how poorly they were treated by a Tiger during their last disagreement. Stalemates are common. In bed, there may be some quite exciting passion, as the Rooster is imaginative and energetic enough to keep the demanding Tiger interested. They are both impulsive and uninhibited lovers capable of grand gestures and profound intensity. Unless the disagreements of the day extend into the bedroom, this couple is well-suited for a long, healthy sexual relationship—without marriage.",
        "Dog": "This is harmony personified. Dogs and Tigers simply get along well. They share common causes and common philosophies. However, they are very different. The Tiger is excessively optimistic, while the Dog is pessimistic. Each helps the other to understand these fundamental character differences. The Chinese describe this pairing as a happy alliance of strength and compassion. The Tiger possesses the power to convey the Dog’s ideals to the public. The anxious Dog remains vigilant and prevents the Tiger from impulsively engaging in the wrong conflicts. They are, quite simply, a wonderful couple. Harmony prevails from the very beginning. And because the Dog and Tiger respect each other’s deepest convictions, mutual admiration binds them together like super glue. In bed, the Tiger typically takes the lead, which is beneficial for the tense, nervous Dog, who often needs to be relaxed before engaging in any intense intimacy. With time, this couple learns to blend eroticism with affection to achieve physical fulfillment. It is rare for such a marriage to end in divorce.",
        "Pig": "The fundamental characteristics here are vastly different. Pigs are scrupulous and peace-loving. Tigers strategize every move and champion their own noisy causes. Yet, with the appropriate amount of gentle understanding from the Pig and the kind of generous reasonableness for which Tigers are renowned, the pair can make a genuine success of marriage. The Pig admires the Tiger’s forceful courage, and the Tiger respects the Pig’s sincerity and purity of spirit. Pigs are mostly even-tempered and good-natured, while Tigers are pathologically unpredictable. Pigs find Tigers too restless, but they do not mind staying at home and maintaining the household while the Tiger rushes about being self-important. Instead of clashing, these two complement one another. Their physical relationship is filled with tenderness and mutual understanding. The Pig is sensual, adores pleasure, and is lavishly generous. Tigers require a great deal of affection and cherish the kind of warmth and domesticity the Pig offers their restless nature. Intense cuddling sessions are abundant in the Pig/Tiger household."
    },
    futures: {
        "2025": {"year": "Snake", "element": "Wood", "prediction": "As you undoubtedly already know, the Snake consistently desires influence. In relationships, in business, or in government, the Snake aims to dominate. Now, for you Tigers, this particular Snake characteristic is both unsettling and extremely irritating. You do not necessarily wish to be in control of many things; answering phone calls and emails in an office all day, waiting for people to attend tedious meetings, would bore you immensely. However, the Snake does not necessarily understand this about you. You appear so strong and self-assured that the cautious Snake feels threatened. Consequently, your life in the Snake year may prove to be less than delightful. The Snake might attempt to obstruct even your most innocent desires for leadership, belittle your most ingenious ideas, and may even sabotage your plans. You see, the Snake not only desires power; it also seeks security and is a meticulous accumulator and saver. You are the more extravagant, carefree individual who believes that money is abundant and that if you keep seeking new opportunities, there will always be more available to you. Conflict will arise between your spending habits and the Snake's desire to accumulate. My advice? Plan to travel this year and remain out of public sight. If you do not threaten the Snake in any way, it will do you the favor of completely ignoring you."},
        "2026": {"year": "Ox", "element": "Fire", "prediction": "I must caution you against attempting to earn a significant amount of money or securing the prestigious job you desire in an Ox year. Why? It is not merely because the Ox does not wish for your success, but also because your rapid, opportunistic methods exasperate the Ox. As a long-term planner, the Ox becomes disoriented simply observing your quick acceleration and swift movements. Ox individuals possess great talent for leadership; they often become autocratic figures. However, they are not particularly quick on their feet, and they are even slower in their intellectual processing. Their minds operate in an unhurried fashion. Do they linger and adopt a leisurely approach to managing their year or their domain? Absolutely not. But they persevere steadily, and you act impulsively. Therefore, in an Ox year, it is advisable to preemptively temper your intensity so as not to appear threatening or to bewilder the deliberate, task-oriented Ox. You will not need to humble yourself to advance. However, you will need to agree with those in positions of authority. Since you detest being anyone's subordinate, you may experience digestive issues, migraines, and other stress-related ailments as a consequence. Maintain the well-being of your romantic life by making a special effort to perform loving acts of kindness and deference towards your beloved or spouse (or both) in this rather challenging, unaccommodating Ox year. You need all the approval and affection you can gather from those who cherish and admire your spirited demeanor."},
        "2027": {"year": "Tiger", "element": "Fire", "prediction": "After a few slow, but not ruinous, years, you will take flight and oversee everything within your purview. I have noted repeatedly that Oxen often assume dictatorial roles, but surprisingly, so do Tigers. While their methods differ, their objective remains the same. Tigers envision themselves as the saviors of a people for a cause, whereas Oxen might simply seize control because they desire it. Therefore, this is your year to govern. You will undoubtedly relish the authority, but you likely will not misuse it, as you will employ your elevated position to advance an ideal—something you are proud of and wish to share with others. If, however, you allow the concept of power for its own sake to dominate, you will experience a terrible Tiger year. Also, remember that this year you must plan the next twelve years of your life. Do not let the months pass without finding a quiet place (such as the countryside, a retreat, or a mountaintop) to sit down and deeply consider where you wish to be in twelve years. Then, determine how you need to behave to achieve that objective. A decade and two years may seem like a long duration, but life is shorter than we perceive, and those who plan well in advance and adhere to their schedules tend to live the longest and happiest lives."},
        "2028": {"year": "Rabbit", "element": "Wood", "prediction": "Cat/Rabbit years are characterized by elegance, a strong focus on security, and a cautious approach to conflict. Your naturally hurried style and ingrained preference for change do not always align well with the Cat/Rabbit's appreciation for refinement, which means you may encounter opposition if you attempt to force your way into anything. My advice? In the Cat/Rabbit year, keep your assertiveness in check. Do not rush into new adventures without engaging in serious planning and strategizing beforehand. Even your most carefully laid plans must be infused with a good deal of strategy and cunning, as the Cat/Rabbit may try to slow you down in various clever (and possibly even deceptive) ways. If you experience a setback in this challenging year, do not despair. Pick yourself up and begin anew. Diligence is highly valued in Cat/Rabbit years. Romance with a capital 'R' will present itself a few times this year. The one thing the Cat/Rabbit cannot diminish is your inimitable Tiger charm. Love will blossom in unexpected places and at unexpected times. No matter how diligently you try to remain composed and collected, that inherent Tiger passion will surge, and you will feel overwhelmed somewhere, sometime—a few times—during this (for you) rather subdued Cat/Rabbit year."},
        "2029": {"year": "Dragon", "element": "Earth", "prediction": "This is not the Tiger's year to shine. Instead, you should adopt a supportive role during these chaotic and festive twelve months. Allow the Dragon to take the lead, and do not entertain any notions of backseat driving. Dragons are affectionately self-absorbed; they desire the spotlight, and if you do not concede it, they will simply extinguish the main lights and continue by candlelight. Tigers are admired by Dragons and are even perceived as allies and companions. However, both of you consistently wish to take the lead. My advice? Remain out of sight. Do not compete. Ponder your next strategic move. Devise new and astonishing plans to implement next year when the agile Snake is in charge. Snakes never need to seize the limelight; it illuminates them regardless. Late in the Dragon year, you may lose something significant—a document, a piece of jewelry, or even a dear friend. Do not worry or fret over the disappearance of this element from your life. As time passes, you will realize that it was not as crucial as you initially imagined. Take advantage of the Dragon's willingness to manage the show while you rest your weary body at some exotic spa or peaceful retreat."},
        "2030": {"year": "Snake", "element": "Metal", "prediction": "A year of love and romance awaits Tigers when the captivating Snake is in charge. It is better for you, Tiger, to be comfortably nestled under the covers with a beloved, attractive individual than to be rushing about at your usual breakneck pace. Snakes dislike hurrying, and they are not amused by your natural inclination for living life in the fast lane. Money will not flood into your bank account this year, but you will have significantly more time and good fortune when implementing projects and arranging business deals. Everything related to luxury is favored now. Assess your own valuable possessions and heed the wise counsel of your subordinates regarding how best to manage them. There is much to be learned and advantage to be gained from the Snake's wisdom. Pause. Observe. And listen to the lessons that this year has in store for you. If possible, slow down to a crawl and do not appear overly busy. Snakes work diligently, then they recline in a warm place and contemplate the universe. Emulate them this year... especially when your new romantic partner is in town."},
        "2031": {"year": "Horse", "element": "Metal", "prediction": "In Horse years, Tigers are not always as fortunate as usual. The Horse genuinely cherishes you and approves of your eccentric energy. But sometimes—only occasionally—misfortune befalls Tigers in Horse years. Do not panic; this bad luck is not life-threatening. However, it does mean you will have to labor harder under somewhat adverse conditions to reach the levels of success for which you are so renowned. I do not mean to imply that you will lack sufficient funds or that you or a beloved family member will fall ill and pass away. But minor events will arise as obstacles and may cause you grievances. More specifically, this Horse year can negatively impact your natural good health. In this period, because good fortune is not always readily available in Horse years, you will have to work harder to maintain fitness, avoid sugars and starches to stay slender, and intensify your workouts at the gym. If you happen to be married or in a long-term relationship now, take your loved one on an exciting journey somewhere new and educational. In Horse years, you will enjoy immersing yourselves in a completely new culture together, bringing back souvenirs, taking photos, and perhaps even forming new friendships. The atmosphere will be cheerful this year, but the work may prove challenging."},
        "2032": {"year": "Goat", "element": "Water", "prediction": "Tigers generally fare better under the Goat’s influence this year; however, they also have to strive harder to achieve their desires. The Goat and you do not perceive life in the same manner. Fundamentally, Goats enjoy being confined to fertile areas where they can exercise their creative abilities without the concern of having to exert themselves independently. You are quite the opposite; you are inherently independent. You do not enjoy being restricted anywhere, ever. As a consequence of this significant difference in approach, in Goat years, you often feel disapproved of. Not that you care in the slightest whether or not you are liked or accepted by the Goat. But you do wish it would not try to curtail your style. Ideally, in these years, you will engage in more travel for both business and pleasure. You will enjoy the wandering. Meeting some new like-minded individuals will help keep your energy levels high for the twelve rather unhurried months ahead. The financial deities are on your side in Goat years. This may not signify that millions will be bestowed upon you, but it does indicate that you are doing something correctly, that is, traveling!"},
        "2033": {"year": "Monkey", "element": "Earth", "prediction": "No frivolous behavior! These next twelve months will offer you a burst of activity, precisely to your liking. Multitasking, numerous meetings, and multiple proposals for work, cultural, and sports experiences. Accept the Monkey's invitations for all these propositions. You, more than any other sign, are certainly capable of managing such a diverse array of ongoing activities. Where other people might feel overwhelmed by such an abundance of new things to learn and do, you revel in the novelty of it all. A change in your work environment is also forthcoming this year. You are an individual whose enthusiasms require alteration as frequently as you change your shirt. So, start diligently searching for that unusual job immediately this year. You will not regret doing so. Love life? Medium rare. I say that because the romantic situation you have been in for so long is, by this time, well done. Overdone, in fact. Hence, it is time to make significant changes. Now, briefly pursue new romantic interests. See how it feels to enjoy the thrill of seduction again. Change is the central theme of the Monkey year for Tigers. P.S. Your current partner will most likely be overjoyed to see you depart."},
        "2034": {"year": "Rooster", "element": "Fire", "prediction": "Allow the Rooster to manage the proceedings. Or at least give him or her the impression that they are in a position of leadership. Roosters prefer to act swiftly, enjoy themselves, and (unlike yourself) prefer not to leave a trail of casualties behind. As you probably have a new romantic interest by this time, you will be busy devising new strategies to retain this prize. However, you need to apply yourself diligently to work this year. Roosters expect people to be actively engaged in their various projects and are not amused by idlers. So, maintain a prominent presence. When you are laboring under the hot sun or mining coal deep underground, groan frequently and sweat profusely to convey to your superiors just how demanding a Tiger's life can be. Otherwise, if you are not attempting to overshadow him, the Rooster will leave you to your countless independent pursuits. Travel and visits to relatives in distant cities are favored now. There is a family member you have been avoiding. Make it your priority to pay them respect. It is in your financial interest to be kind to them now and make amends for any past neglect."},
        "2035": {"year": "Dog", "element": "Earth", "prediction": "Phew! There is relatively little that can go utterly wrong for a Tiger in Dog years. You and Dogs get along well together because you share similar beliefs and adopt a global perspective on even the most minor events. Differences of opinion arise when you sense the Dog's inherent paranoia surfacing unexpectedly. Dogs possess a unique understanding of Murphy's Law; they instinctively know that if something can go wrong, it will, and they are more than willing to announce it beforehand. Hence, in Dog years, an atmosphere of pervasive anxiety lingers, which drives Tigers to distraction. My advice to Tigers in this otherwise somewhat challenging year is to enjoy the goodwill that the Dog offers you as its protective companion. Relax a bit. Ease off the accelerator at work. Spend some enriching downtime simply socializing with friends or family—or both. In Dog years, you can also enjoy engaging in cultural excursions. Take tours of exotic lands you have always promised yourself you would visit. Go see the Pyramids or visit Niagara Falls. Do something wonderful for yourself, but leave the Dog and its paranoia at home."},
        "2036": {"year": "Pig", "element": "Metal", "prediction": "Pigs admit to a certain wide-eyed admiration when confronted by you restless Tiger individuals. Pigs are strong, knowledgeable, and culturally adept people. But they do not comprehend your exaggerated need for change. You are constantly bustling about, never settling long enough to accumulate capital, amass riches, collect art, or acquire luxurious homes—whatever it is the Pig considers wealth. Nevertheless, the Pig and you can be close companions. You admire the Pig's purity and authenticity of spirit. What it does not understand about you is what will hinder you this year. The atmosphere of abundance will lead you to assume you can spend, give, and squander your money, and so—in a word or two—you overspend. If you are not more careful about where your money is going in the first part of this Pig year, by September, you will find yourself in a difficult financial situation. So, tighten your resolve, Tiger. Control your desire to be overly generous to those you love or those you feel are in need. Hold onto your financial reserves and do not sell the family jewels to acquire a fancy new car to impress your beloved. Put yourself on a budget. Give your love freely, but take fewer financial risks. Slow down. Sit still. Read. Knit. Go to the countryside. Sit under a tree and reflect."}
    }
};

  