// src/lib/new-astrology/virgo.ts

export const virgo = {
  "Virgo/Rat": {
    description: `A peppy, analytical person will be born of these two strong signs. Without the bulldozer punch of some of the other forceful New Astrological signs, the Virgo/Rat goes about his business craftily and with both system and industry. The Rat’s aggressiveness is tempered here by Virgo’s methodical intelligence. Virgo/Rats are neither hotheaded nor foolish—except in love. The thing about Virgo/Rats that sets them above the madding crowd is their total independence of pressure from without. They do what is necessary when they feel it propitious and will not suffer to be hurried or cornered by associates or adversaries. “Wait.” The Virgo/Rat will hold up his hand in an important meeting. “Let me think.” And reflect he will—for as long as it takes to dredge what information he needs out of his own head. This character works best alone and needs no straight men or canned laughter to propel him to perform.

As Virgo/Rats deal so resolutely from within their own sphere of influence, it is sometimes difficult for them to listen or heed advice or opinions from others. They seem to absorb information perfectly while it is being spewed at them. Then, surprise! They have not assimilated the facts as they were emitted. They have instead fed some facts into the data bank in their own inner world in their personal, private, meticulously exact language. In doing so, the Virgo/Rat is capable of sapping all the emotional punch from another person’s idea before the idea has a chance to take its first breath. Of course this coin has a reverse side. Overly windy and impulsive people can be skillfully assisted by the likes of Virgo/Rats. The staid and sinuous thought processes of the Virgo born in a Rat year can sort the feeling from the fact in seconds flat. Go crying and weeping to a nice Virgo/Rat person sometime and watch his style. “Now sit down. Calm yourself. Collect your thoughts. What was it again?” they may say cannily. By the time you look up from your sopping handkerchief, the Virgo/Rat is on the telephone. It usually turns out he had begun calling your enemy’s number before you got through your first gasp. He doesn’t need to hear all the gory details. He sifts through rapidly, and click, he’s got the fellow on the line.

There is something of a Popeye quality in this deep-thinking dynamo, too. The idea of rescuing people in distress is tempting and so easy for the Virgo/Rat that he doesn’t see why he shouldn’t just pop a can of spinach and dive into the fray. I have Virgo/Rat friends who seem to prosper on the trouble that others can cause for them. They marry problems, they hatch problems and they fall in love with their problems’ problems. Virgo/Rats’ upheavals have upheavals. But they just keep going ahead at their own mild-mannered pace, getting to their office on time, calling the psychiatrist for their daughter’s husband, and then getting the firemen on the phone about their cousin the arsonist’s most recent caper, and after that they write a letter to the police about their wife or husband’s little knife incident. You’d think they would explode from the complexities of other people’s lives. But no. They find it perfectly normal that their forty-five-year-old sister-in-law just found out she was illegitimate and had a nervous breakdown in Macy’s. They dash out to buy another straitjacket. Virgos and Rats both take kinship and friendship very seriously. They never forget an old pal, and would literally give you the shirt off their backs if you needed it. If someone they care about deprives a Virgo/Rat of his friendship for any reason whatsoever, he is stunned and shocked. As a benefactor, he cannot understand why people he has helped and admired would jilt him. Trouble is, he can sometimes be so blindly preoccupied with his bevy of pet nutcases that it exasperates his friends. This he cannot understand. And it wounds his spirit deeply.`,
    love: `Where hearts are concerned, lucidity is not the Virgo/Rat’s strong suit. Although he may be a genius at scrutinizing a contract for a pal who just got a role in a film and is worried he’ll be ripped off, Virgo/Rat cannot be even slightly objective about his personal life. He loves people with irrational passion. And I am sorry to say that he idealizes them too. As Virgo/Rat is such a straight-up guy, he thinks everybody else is just as direct-dealing and fair as he is. Of course Virgo/Rats have the most devastatingly bad luck in love affairs because they cannot see the forest for the trees. People pull more wool over Virgo/Rat’s eyes in love affairs than is produced in all of Australia.

Yet, the Virgo/Rat needs love desperately and will travel far and wide to locate just the right person to fall in love with. I know a Virgo/Rat woman who, at forty, left her wealthy Protestant minister husband in a gossipy small town in the South, took her five children under the age of twelve and moved to India to follow the love of her life. India? “Why not?” says the impassioned Virgo/Rat. “I loved him, didn’t I?”

If you love a Virgo/Rat, do him or her a favor: Don’t make life easy for them. Be complicated. Make scenes and cause rows and burn down the living room once in a while. But—and this is the big but with Virgo/Rats— always be sweet. Virgo/Rats are always a bit stiff. They are bowled over by sweetness and docility. They like nice people, and really don’t care how you act as long as you stay as sweet as you are.`,
    compatibilities: `I can see you felicitous next to an Ox, a Monkey or a Dragon of the Taurus, Cancer, Scorpio or Capricorn schools. I’m not quite so sure about those Scorpio/Dragons, however. They are fairly dashing and dauntless and you usually prefer to do the dashing and daunting. If I were you I would avoid Gemini, Libra, Sagittarius and Pisces born in either Cat years. Please don’t marry a Horse or any color, shape or size whatsoever. Horses and Rats are initially attracted to each other, but long term the two signs do battle and someone—usually the Rat—gets hurt. Rats are sentimental and homeloving, protective and caring. Yet, it’s no secret, they want the power in relationships. Horses can be loving and caring too. But they are more pragmatic and proud and do not give up power without a fight. Result? Constant wrangling.`,
    homeAndFamily: `A model of family responsibility, the Virgo/Rat likes to take care of others, give them everything he has and allow them whimsy and fantasy galore. But oddly, with all of this apparent indulgence, Virgo/Rats want the rules to be obeyed. They are not like cops. Virgo/Rats don’t go goose-stepping around laying down the law. But they themselves respect the rights of others and behave in a mannerly and orderly fashion. They would never be able to comprehend a child or spouse or even a parent who did not do as much. The Golden Rule describes the way Virgo/Rats treat their families. Some kids take advantage of this good-natured fair play attitude and walk all over their Virgo/Rat parents by not playing the game. I’m not mentioning any names but some kids need a good boot in the bottom. The Rat/Virgo’s home will be a haven for everybody he loves to come and visit, sit around the fire, chat and gas and natter on till all hours. As he is a sensualist and appreciates fine wines and foods, he will share them with you as though there were no tomorrow. “Here. Try this Ro-manee-Conti. No? You’d rather have Gevrey-Chambertin? Hang on, I’ve got just the bottle for you.” You’ll never see such sumptuousness laid on anywhere but in the festive Virgo/Rat’s dining room. Too, as he is both a careful Virgo and a hoarding Rat, this character will be the best friend you want to know during food shortages. This person stocks up on everything. You should see my Virgo/Rat friend Irma’s pantry. She never buys one of anything in the supermarket. Dog food for years to come. The dog will be dead by the time she uses it all up.

Virgo/Rat children may seem too quiet and reserved to be healthy. But it isn’t so. Virgo/Rats enjoy behaving well. You cannot keep them still for long, though, as they need to move about a lot and are curious about all matters. But they can be taught almost any skill with their hands, and usually enjoy refined tastes in everything from food to music at a young age. These children need a neat place to grow in. Try not to force them to share with a messy sibling. It won’t teach them anything and will only further fray their fragile little nerve endings.`,
    profession: `This person is a gifted analyst. His talents lie in areas requiring research and a systematic approach. He is able to act quickly but does not like to make rapid or ill-considered decisions. Virgo/Rats are especially talented in fields where they have the opportunity to help other people achieve their ends. They enjoy being privy to the inside dope in any situation and can keep secrets—except about their personal lives.

Virgo/Rats are not terribly flexible people. They are often disquieted and restless. All careers that require dealing with the public are wise choices. But Virgo/Rats will probably not take well to vapid or empty-headed jobs. They don’t mind doing menial or routine jobs and are capable of enormous patience for poring over accounts and densely worded documents. As a boss, a Virgo/Rat would be ideal for a hard-working, cheerful employee. But if he has to use a cattle prod to get his workers moving, he’ll simply fire them. Virgo/Rats do not suffer inefficiency in themselves or anybody else. Virgo/Rats make fabulous employees themselves. They may be just a bit on the rigid side in their outlook. But better rigidity than sloppiness, n’est-ce pas?

Career opportunities for Virgo/Rats will be found in these fields: psychoanalysis, agenting (all sorts), real estate development, business administration, medicine, entertainment`,
  },
  "Virgo/Ox": {
    description: `“Nothing worthwhile ever comes easily,” says the plodding model of human rectitude who is Virgo and Ox. An air of the ascetic emanates from this stolid character. He is deliberate. He is careful. He is meticulous. He is diligent, classical, traditionalist and sincere. And he never hangs out with anyone who is not at least some of the above. Virgo/Ox needs to rule his life single-handedly. He asks help of no one but his own people. These he has either hatched himself or chosen as friends and colleagues after much sorting and weeding out over the years.

All variety of criticism can be directed at this subject. He is such a caricature of his stodgy self that we could spend paragraphs on his foibles. But that would be too easy. You can see for yourself that of all the characteristics of both the Virgo and Ox signs, there are only a couple of really feathery qualities. This person is at best both courteous and innovative—that’s it for the jolly side, folks. As for solemnity, this person is a past master.

What saves this character from sinking under his own natural weight is his sense of lucidity and of course his unbeatable eloquence. This person is well spoken and makes a near religion out of fastidiousness in manner and in deed. He doesn’t believe in doing things the easy way or in using shortcut methods. The Virgo/Ox firmly espouses the idea that what is right is inalienably and immutably right. Black is black and white, white. Do not attempt to clutter up his mind with nuance.

You can trust this person with your house, your life, your husband, wife, children and pets. Virgo/Oxen pride themselves on their respectability. They are reliable and efficient. They are also, in a sort of severe and crisp way, loving. They are loyal and honest. They can be tempted by ruses, although this is rare, and involvement in any crooked scheme will be their undoing. They cannot live with a bad conscience. These folks need to keep a clean slate inside their heads. With them it’s all or nothing. If they got caught with their hand in the kitty, they’d probably commit hari-kari.

Virgo/Oxen are better at achieving success through hard work than almost anybody else. They are some of the world’s most addicted workaholics. Virgo/Oxen are not interested in airy cocktail conversation and they eschew small talk. Some people think they are rather too unsociable. But it’s their way. They will talk if they want to tell you a story and they’ll do so brilliantly. Then they clam up. In other words, Virgo/Oxen are not funny off the set.

The Virgo/Ox resists change. If tasks are done one way, and have been done like that for a long, long time, and he or she has learned the skill of handling said task with characteristic artisanal perfection, then this person sees no reason to alter his way. He may innovate and develop something that turns out to be foolproof. But he will test it for ten years before he’ll attempt to commercialize his scheme. He’s conservative and thrives on both zeal and exertion. When it comes to endurance, to perseverance and steady toiling, the Virgo/Ox wins the race.`,
    love: `Constancy is the Virgo/Ox’s middle name. He is essentially a practical sort and so usually falls in love with someone who will be useful as well as, say, decorative or sexy or brilliant. One of the Virgo/Ox’s most out-standing traits is his discrimination. These people are mighty choosy about whom they frequent, and seek, above all, a sense of probity and industry in friendship. Ephemeral passionate love affairs are too messy for straightarrow Virgo/Oxen.

If you find yourself attracted to this hulking nit-picker with the full pocketbook, show him your calloused hands and tell him how you had to milk the cows all by yourself in the cold barn when you were five years old. Give him plenty to admire you for. Then try to resign yourself to being just as dutifully hard-working as he for the rest of your days. Virgo/Oxen don’t want just a pretty face as a mate. Industriousness, they feel, is about the best quality a spouse can offer.`,
    compatibilities: `Harmony can be found, especially if you go looking for it, among Taurus, Cancer, Scorpio or Capricorn people. In Taurus you will particularly enjoy the company of Snakes and Dragons. The Cancers in your life will probably be Horses and Dogs. Same goes for Scorpios and Capricorns—Horses and Dogs all the way. Don’t go marrying any Gemini/Dragons, Horses or Sheep. Refrain from associating with Sagittarius/Sheep and Tigers. And whatever you do, don’t take up with Pisces of the last two animal categories. Too wishy washy new-agey oogah boogah spiritual for your down-to-earth workaday tastes.`,
    homeAndFamily: `This person’s surroundings will be traditional and comfortable to a point. He is not one to buy plush squishy armchairs or pouts made of satins and silks. He wants things to be both practical and sturdily handsome. Above all, he likes his environment to be efficient for family living. Luxuries? Well, they can come later. I know a Virgo/Ox who is building his wife her first new kitchen in fifty years of marriage. She’s been patient, he tells me.

If your mother or father is a Virgo/Ox, you know by now that when you grew up you were supposed to be either exactly what they were or, at the very outside eccentricity, a doctor or lawyer. Virgo/Oxen sacrifice materially for their families. In return they expect Junior and little Sukey to toe the mark and follow in their footsteps. In families, the Virgo/Ox runs the show, wears the pants and holds the purse strings.

The Virgo/Ox child will be a stubborn and deliberate sort. There is no jollying him or her along. Just make sure they learn how to perform some skill or enter some serious line of work that challenges their enormous capacity for effort. Tire them out daily with sports and chores and homework. This kid is basically structure-oriented and cannot tolerate inactivity for long.`,
    profession: `This subject favors quiet environments without benefit of the city’s clanging or rush. He or she is talented in the countryside’s demands. Remnants of the gentleman farmer or the elegant provincial wife live very near the surface of Virgo/Ox’s soul. He’s thorough and accurate, conscientious and aboveboard. Moreover, the Virgo/Ox is endowed with a sharp intelligence that will ensure that whatever job he chooses gets done right.

As a boss, this person is terrific. Virgo/Oxen can and do dictate, make rules and see that they are carried out. They know how to delegate workloads and are not afraid of disciplinary measures. They are often good businesspeople and they know how to live economically. The same holds true if this person is employed. He is not afraid of discipline, nor is he too proud to obey when necessary. The natural Virgo/Ox authority is not ego-based. This person can take orders as well as give them.

Some suitable professions for the Virgo born Ox are: market analyst, artisan, dog trainer, athlete, cattle rancher, farmer.`,
  },
  "Virgo/Tiger": {
    description: `The Virgo/Tiger is a tough cookie with a heart of gold. Virgo/Tigers don’t let anything get past them. They notice and calculate and tot up and plan and analyze and then... they pounce. It’s an unbeatable combination for the person himself to live with, but maybe it’s a little bit on the cranky, know-it-all side for those who have to live with him. Redeeming qualities? Plenty. Virgo as an added ingredient to Tiger restricts the Tiger’s impetuousness, turns the Tiger’s tongue around three times before letting him blurt out his foolhardy schemes, and truly molds the Tiger’s normally sprawling, messy existence into something quite wonderful.

First of all, the Virgo/Tiger is a dutiful slave. No amount of work daunts this unflinchingly industrious person. Whatever the task, no matter how many there will be for lunch or dinner, or how many stops he has to make along the way to let Junior out to pee or give sister some air, the Virgo/Tiger performs admirably.

Now all of this unstinting driving and cooking and cleaning and welcoming and more driving and cooking and cleaning are not done without complaint. The Virgo/Tiger may be a slave. But he is not a willing slave. Rather, he is bound by duty, imprisoned by his sense of obligation and tied down by his fervent belief in what is right. He will go to that goddamned office every morning on foot and without a sigh for thirty years if need be, without ever missing a day. But woe unto the dependent who doesn’t appreciate what that sensible Virgo/Tiger goes through for his sake. Virgo/Tigers make wonderful allies. And they make indomitable enemies as well. They never forgive.

You see, normally Virgos don’t mind being serious. It’s part of their lot. But here, the Tiger comes loping along with that silly grin pasted on his chops and entices the darkest side of Virgo, summons him to prankishness and movement. If the Virgo/Tiger is sensible and doesn’t go off the Tiger’s deep end, he may have a terrific life. Tigers are not at all like Virgos. But they do understand them. So, properly handled, the Tiger lends a bouncy note or je ne sais quoi to what could be a stodgy Virgo life.

There will be a definite streak of charity here, and the ability to perceive the problems of others as his own. Virgo/Tigers are good advisers. They are strappingly sensible and wise. Too, they can be meddlesome and don’t hesitate to upbraid their friends for peccadilloes the size of your pinkie nail. They’re meticulous and fussy about what they eat, and with whom they spend time, and whether or not those items are up to their rather exaggerated standards. Virgo/Tigers are not quite bossy. They’re pushy. But not authoritarian.

You often find Virgo/Tigers in conservative places. They are fond of museums and warm to the mystery of archeological digs. They move a lot and don’t mind wandering and travel. But they like to make the most of whatever they are doing and therefore tend not to be mobile just for the sake of being mobile.

This variety of Tiger will be a snob. Tigers already have a pretty high opinion of self. Virgos are lucid about their own limitations, but they like to feel they know the “right” people. It can become annoying to be constantly reminded by a Virgo/Tiger host who so-and-so is rather than just being allowed to get to know him or her. Yet this name-dropping habit is native to the Virgo/Tiger, who sometimes seems more concerned about who people are in society than who they really are in their hearts.

The Virgo/Tiger boasts a fine bearing and, although not classically beautiful, seems to know how to make the best of whatever looks he was born with. Here again, it pays to be objective about one’s appearance. Objectivity is the Virgo/Tiger’s specialty. He may try to fool you. But he never fools himself about anything.

There is a lot of innate cheer in the Virgo/Tiger, too. They like to have fun, make others laugh, cut up and play. They are often good at sports and are dead serious about their tennis or golf or squash. Virgo/Tigers put a lot of effort into making their lives swell places to live in. They share well and truly enjoy providing others with joy. They won’t ask for much applause, either. They’re just doing their best, which is always impressively better than the best of other, less dutiful souls.`,
    love: `A more honorable life partner, upstanding in the extreme and a reliable organizer of everything—including sentiment—one could not even dream of. But don’t count on the Virgo/Tiger for lascivious roll-in-the-hay voluptuousness. Virgo/Tigers enjoy lovemaking and throw themselves into it as vigorously as they do their cooking and driving and jogging. But the trouble is, while they are engaged in the lustier pleasures, Virgo/Tigers may give you the eerie impression that they are worried about that cake they slipped into the oven just before the wooing began, Is it falling or rising? Virgo/Tigers can’t help it. They just have to be useful.

If you love a Virgo/Tiger and want to please him or her, I suggest you make every effort to be a respectable and even hugely important person in society. Virgo/Tigers are interested in position. They are turned on by people they can admire and look up to. Lazy or just so-so achievers bring out the picky Virgo side of Virgo/Tigers. They may become lifelong grumps, embittered by association with someone they love but don’t respect. And although the Virgo/Tiger will do anything to keep up appearances, you will be able to tell if the respect is evaporating when you and your favorite Virgo/Tiger are finally nose to nose between the sheets. For this character it’s all or nothing. No maybes.`,
    compatibilities: `You are attracted to Capricorns. There’s something similar in your dry, dense approach to the way Capricorn/Horses and Dogs behave. You will get on. Taurus, Cancer and Scorpio/Horses and Dogs make excellent choices for you as well. You’re too fiery for the stolid Aries/Ox and you are not laid back enough for old Gemini/Sheep. Gemini, Sagittarius and Pisces/Snakes and Monkeys will not do.`,
    homeAndFamily: `The Virgo/Tiger’s home will favor a traditional decorating scheme. As this person cleaves to whatever is stable and real, he generally enjoys surrounding himself with antiques and treasures of veritable value and status. In choosing colors, he tends toward yellows and turquoises. Virgo/Tigers like to liven up their environment with comfortable prettiness. Flowers will be part of their weekly budget, and exotic teas and jams will please them.

Family, if the busy Virgo/Tiger ever gets around to having one, holds the paramount place in this subject’s life. Lots of children are probably not in the cards. Noisy brats crashing about the Virgo/Tigers’ cushioned salons and bashing into their flower vases do not fit into their ideal picture of family bliss. Yet, if they do have a child or two, they will be devoted and special parents whose every action is intended to ensure the happiness and future of little Junior or Missy. As for their parents, Virgo/Tigers are responsible about calling Mother on her birthday and taking Dad to the doctor for a checkup, but they will not allow meddling in their own lives and practically never actually cohabit with their parents after they reach maturity.

Virgo/Tiger children make wonderful house pets. They can be counted on to keep their rooms clean and run errands and wash dishes. They may, however, display picky nervousness and be mildly cranky at times. They will probably study well, but not for long. The establishment of a home and family at an early age is the natural outgrowth of this person’s serious and self-reliant nature. He likes to establish himself on his own and free himself from dependence.`,
    profession: `The Virgo/Tiger’s earthy, energetic self will lend itself to any career requiring both mobility and responsibility. It will not do, however, to expose this security-conscious soul to excesses of free enterprise or unplanned projects. Virgo/Tigers are a bit on the hotheaded side and can be impetuous. But they will probably reserve their impulsivity for sound, sane actions within an established framework. You won’t find many Virgo/Tigers rushing off to become mercenaries or saving lepers in Africa, either. They enjoy comfort and ease and do not mind creating and maintaining it for themselves and loved ones.

The Virgo/Tiger is not uncharitable, and might be happy as a church or Red Cross volunteer. Also, you will find Virgo/Tigers among solid business professionals such as controllers and investment bankers. Too, as the Virgo/Tiger treasures his neat little nest and cares about his social image, he will make a fine houseperson whose daily job it is to see that those who live with him evolve successfully. Virgo/Tigers usually like staying home and preparing elegant dinner parties too. The creativity of this person is often applied in areas related to decoration or style.

Careers suitable to the Virgo/Tiger are: politician, theatrical or film director, judge, stockbroker, entrepreneur, athlete.`,
  },
  "Virgo/Rabbit": {
    description: `Virgo/Cat is the picture of caution. His first portrait can only be painted after many years of slow and deliberate development. You will never hear him complain, nor will you notice him creeping up on you. This person is sagaciously circumspect, stays out of the way of danger and will even throw away what is most important to him just to keep the peace and dodge conflict.

With all of this, the Cat born Virgo is often obliged to be alone. He likes his home, feet up next to the hearth, books to read, dense silence to keep him company. This image is only possible if the door is armored, the windows equipped with alarm systems and the wall around the property ten feet thick. Cats born Virgo don’t want nobody messing’ with them. These people have difficulty communicating. They would rather work or build or restore or putter with a project than just sit around shooting the breeze. Small talk not only bores them, it positively frightens them. Chitchat all seems so glassy and insubstantial. Those petty remarks and gossipings that people find amusing make Virgo/Cat feel uneasy. Why aren’t these folks busy with some more edifying pursuit? he asks himself.

I’m not suggesting that Cats born Virgo are goody-goodies or Polyannas. Not a bit. These people do not parade themselves as models of good behavior. Their exemplary deportment comes quite naturally to them. They are not obliged to force themselves to be virtuous, nor do they scoff at those who aren’t. Virgo/Cats are supremely tolerant of others and know how to put up with their eccentricities and faults.

The Virgo/Cat is genuinely preoccupied with advancement and, in his or her own quiet way, seeks only to achieve progress and find the ideal environment that he knows intrinsically is right for him. Virgo/Cats are motivated by duty and spurred forward by the search for an ideal world wherein everyone would leave the noble Virgo/Cat to his own devices. He will pull with the masses, so long as the end result includes his own peace of mind.

Because of an innate difficulty with human contact, this person may seem aloof and even tyrannical. He or she will require feats of performance from associates. The Virgo/Cat asks as much, if not more, of himself. Why then shouldn’t his colleagues strive to match his efforts?

The Virgo/Cat is often accused of social climbing. This stems from his desire for refinement and his need to cleave to what is traditional. He is fussy about manners and frets over social faux pas. He prefers not to take big risks and yet, when called upon to act in an emergency, can prove heroically courageous. Routine doesn’t annoy the Virgo/Cat. Nor does a certain subjugation, so long as said slavery protects him or her from accident. Virgo/Cats deplore unforeseen occurrences and balk at change.`,
    love: `This person’s love life will have two very distinct parts. In his or her youth, the Virgo/Cat will probably get involved with kinky or zany types. In youth this character likes to wallow in a bit of human mud. During this time of experimentation he may well fall madly in love with some oddball. But this “nut’ love period is, I fear, very short-lived. What this person is ultimately looking for is not a laugh a minute or a glamorous life in the spotlight. Before age thirty, Virgo/Cats usually dive for cover from early romantic errors. They often surface years later as the wife of some oil magnate or the very safety married owner of a shoe store in Topeka.

They do, however, have a soft spot for the unfortunate. Virgo/Cats sometimes get their virtue mixed up with their sense of sacrifice. Then they may fall prey to relationships that turn them into unwilling slaves for the rest of their lives. If you care about a Virgo/Cat, do yourself and him or her a big favor—learn to leave him in peace. Don’t talk to this character unless it is absolutely necessary. Don’t hover around your Virgo/Cat’s chair or buzz in his ear. Turn the TV off forever and go to your room and read until dinnertime. For this delicately strung human instrument, heaven is tranquility.`,
    compatibilities: `Oh how you get on with Taurus, Cancer, Scorpio and Capricorn/Pigs! All of these hearth-dwellers to the manor born are capable of giving you happiness. You are also welcome to try Taurus, Scorpio and Capricorn/Sheep and Dogs. You get on especially well with Taurus/Cats, too. I don’t advise Gemini, Sagittarius or Pisces/Roosters for you. They are far too elastic to fit into your cautious lifestyle. Gemini and Sagittarius/Rats are out, as are Pisces/Dragons.`,
    homeAndFamily: `In addition to all the locks and bolts and alarm systems, this person’s home will be discreetly furnished with antique objets d’art designed to grow gracefully older along with their owner. Virgo/Cats like beige and old gold. They are attracted to ivories and off-whites in their decor. They cling to culture and tradition in everything from soup to nuts—including the kitchen sink.

This person will make an intellectually responsible parent. He or she will surely spend time trotting Jason and Sarah to museums and seeing to it they are taught old nursery rhymes. Of course Virgo/Cats provide. They are superlative wage-earners and believe in the nuclear family as the salvation of the future. I wouldn’t mind being this person’s child at all. It would certainly be comfy and safe.

This child will be fearful and squeamish. Virgo/Cats are born with a ponderous respect for danger and must be cajoled into acts of daring. They don’t take kindly to change, so try not to have a Virgo/Cat child if you plan a divorce. This kid needs order and routine more than almost any other sign.`,
    profession: `As Virgo/Cats require security and seek to set their wealth safely aside forever, they are good at all jobs that earn them a decent, steady income. Of course, Virgo/Cats don’t always achieve fame or even succeed at amassing the fortune they covet because they are scaredy-cats. As we all know, the jackpot lands most often in the lap of the one who dares take a chance. Virgo/Cats can’t. They will work and even slave efficiently and earnestly. But they will never venture out on a limb.

In positions of authority these people tend toward rigor and severity infused with a kind of unspoken understanding of their own superiority. They are, in fact, paragons of patronizingness. They like to think they are caring for their employees, providing for their families and financing their whims. It’s annoying. But effective.

The Virgo/Cat employee is a model worker. He is so virtuous and honorable that he never gets fired—much to his detriment, I fear. These folks have been known to stay in the same dumb, slavish, steady job all their lives for sheer terror of not finding another.

Careers suitable to the Virgo/Cat are: museum curator, librarian, archivist, market analyst, travel agent, diplomat, gardener, decorator, musician.`,
  },
  "Virgo/Dragon": {
    description: `The Virgo/Dragon couples Virgo decorum with Dragon sizzle. This Dragon is hard-edged. He has enough spunk and perseverance to take a dare to walk across Australia – solo! He always maintains a coy Virgo reserve in order to keep Dragonish taste for fresh blood under dignified wraps. If you’re looking for performance, it’s a hard to beat combination. The fiery Dragonesque soul is tempered by Virgo’s taste for social grace. Virgo/Dragon is ambitious and has a mind like a platinum bear trap. In this discriminating character there is not as much braggadocio and volubility as in other Dragons. Yet, when this person is angry (which is frequently), fireworks invariably occur. The marriage of Dragon to Virgo, with all of their possible complementary traits, is just a shade too self-interested to be called harmonious. Virgo/Dragons are picky and strong-willed. They carry a harsh and vituperative tongue around in their heads. The general atmosphere is not exactly cozy.

Although this person starts out life bursting with sentimentality and tenderheartedness, adulthood brings disenchantment. The result is a jaded, blasé and sometimes even dangerous grownup.

Driving volition is an important Dragon/Virgo personality trait. This person goes at life with a burning zeal that borders on fanaticism. There is, of course, much success out there for such determined people. But there are also a lot of dead bodies in their wakes. What Dragon/Virgo wants, Dragon/Virgo gets.

These subjects can be thoroughly attractive. They carry themselves with a certain arrogance and they know how to dress. They are born with good health and stay in shape to preserve that state. This person wants to “make it” in life, to beat out his competition, to take the world title in his field, and nothing will stand in his way. Except his terrible temper.

Virgo/Dragons are stompers and fumers and fussers and screamers. They are furious about one-third of the time—at their families, at their bosses and at themselves. They despise failure, and even hate themselves for a tiny booboo or goof such as hitting their finger with a hammer. Such tempestuous behavior, of course, repels people who might be able to really care for this alluring demon. Virgo/Dragons are their own worst enemies. They are sassy and they don’t know how to remain invisible. There isn’t much room for small talk with this resolute soul. He or she will prefer getting immediately to the nitty-gritty. Poetry is hardly the Virgo/Dragon’s favorite entertainment. He likes competition sports and war, business deals and starring roles. Forget the gingerbread. Just give him a hunk of raw meat to chew on.

Seriously, this person is lucky to possess inordinate self-confidence. He will always keep a clear head. He can be counted on to finish what he starts and he is not often a disappointment to colleagues and partners. Virgo/Dragons demand their share in life, and they most often get it.`,
    love: `The personal lives of Virgo/Dragons don’t prove so felicitous. Of course, this person is constantly pursued by members of the opposite gender because he or she will reek of sex appeal and mystique. But unfortunately this person is more fascinated by his career and his social effect than by intimacy with one person.

If you love one of these feisty creatures, you’ll have to enjoy standing on the sidelines, smiling and cheering your Virgo/Dragon to victory. He or she will insist on your cooperation in their act. Life with a Virgo/ Dragon is never a two-way street. In short, there is much to admire and not all that much to hug.`,
    compatibilities: `In general you favor Rats, but Taurus and Capricorn/Rats are your most vulnerable targets for romance. Taurus and Cancer/Roosters keep you quite busy too, as do Taurus, Cancer and Capricorn/Monkeys. You will be floored by the sexy Scorpio/Snake. Gemini, Sagittarius and Pisces/Dogs, with their constant hesitations and doubts, irritate you. Oxen both Sagittarius and Pisces, are your most notorious foes. Steer a wide berth.`,
    homeAndFamily: `The decor will be stark and striking. The whole scheme of things in the Virgo/Dragon’s environment is severe and in excellent taste. His choice of furniture is generally conservative in line and not too comfortable. One must not lie down nor lean too far into idleness. You are welcome but don’t linger, is the Virgo/Dragon’s motto.

It takes the Virgo/Dragon quite a while to get around to having a family. Often he will decide on children later rather than sooner in married life. Virgo/Dragons make responsible yet demanding and disciplinary parents. When they pass middle age, they tend to revert to their original sentimentality, too. Dragons born in Virgo are the kind of people who mellow with age. They make indulgent grandparents, compensating for all the rigidity of their middle years.

The Virgo/Dragon child will toe the mark in school. Here is the president-of-the-class type who has an eye for the glittering prizes in store. He may be vulnerable, too, and easily hurt. Don’t worry, he’ll toughen up as he goes along. But as a little person the Virgo/Dragon needs a lot of attentive protection. You will certainly have reason to be proud of your baby Virgo/Dragon. But if you are not, don’t worry. He’ll be proud enough for both of you.`,
    profession: `The Dragon born Virgo is happiest and most fulfilled by his or her work. This person is talented in every type of career that permits personal promotion and an eventual rise to the top of the heap. Virgo/Dragons are more restrained than most Dragons. This person’s eye never strays from the ball and when he connects, it’s home-run time. Virgo/Dragons make peppy, fire-eating bosses. They will attempt to be fair so long as you don’t get in their way. Then—well, they feel “all’s fair in love and war,” and will act accordingly. These people make very competent employees, whose main concern is getting praise for getting the job done. This can be exciting and a relief for an overworked employer. However, the Virgo/Dragon will always try to leapfrog his superiors and in some way or other scramble his or her way to the best job in the house.

Careers suitable to the Virgo/Dragon are: politician, theatrical or film director, judge, stockbroker, entrepreneur, athlete.`,
  },
  "Virgo/Snake": {
    description: `Analysis and intuition are two essential elements in the personality of a Virgo/Snake. This Virgo is both emotional and attractive. He is endowed with wisdom and depth of understanding. He may appear serious and even grave. The tongue, you will notice, however, is conveniently stored inside the cheek. This person’s strength is that he is not really of the world. Virgo/Snakes exist outside of the mundane and always wear a secret smile. Nothing is too technically complex for this subject’s intellect and perception. Nor are metaphysical problems beyond his reach. We are dealing here with a monster of attraction and appeal whose flat-out—almost cold—sensuality will warm the blood of even the most reserved observer. Virgo/Snakes are calculating. They always need to know where they are headed. Before they undertake a project they want every element worked out in minute detail. Virgo/Snakes are capable of magnificent insincerity. I’d say that the Virgo/Snake is introverted yet avidly interested in others. His motive behind this gregariousness is simply his need for admirers. Of these he always has more than his share. He is a long-lasting friend with the ability to listen and to cheer. It’s not that Virgo/Snakes are innately funny. They have crinkly-eyed charm that is irresistibly amusing.

This person is remarkably combative for a Snake character. He’s quite a scrapper when crossed, and involves himself in monumental tongue-lashings and verbal conflict to spare his pride. Virgo/Snake simply does not tolerate being toyed with. He is dignified and insists on remaining thus. If, however, he sees that the joke is irrevocably on him, this person is capable of laughing at himself. A breakthrough for the sometimes too proud Snake. These natives seem oblivious to aging and stress. They slither through their daily rounds with a rare sort of detachment from almost every problem encountered. They insist on stability and expect to maintain equilibrium in their personal lives. They never make useless trouble.

Laziness is the Virgo/Snake’s enemy. Yes. Even the efficient Virgo can be tempted by the Snake’s tendency to sloth. From time to time his analytical side will assess the situation and you’ll marvel to see him rise like a spinning top from his sagging sofa and shift into whirlwind activity. This is a capable soul. But if the sun is shining and the livin’ is easy, he can grow sluggish. Gourmet food will tempt him too. Virgo/Snakes should avoid waist-expanding foods and keep up a steady exercise routine.

Most striking of all the Virgo/Snake’s characteristics is his open-mindedness. This person is always ready for new experiences. He is willing to try anything once, and makes a good companion for someone who likes adventure. There is a critical side to this subject as well. But since Snake people are disposed to sagacity and they intuit rather than puzzle things out with logic, Virgo nit-picking and fault-finding is kept to a minimum. Gossip, however, pleases the Virgo/Snake, and although he is discreet and never meddles in the affairs of others unless invited, he can frequently be caught in merry derision of the garish color of his neighbor’s new car.

Virgo/Snakes are also bossy. Or rather, they rule. Period. Their methods of expressing authority consist of silent pressures and the application of well-defined rules without excessive rant. They care a lot about those they dominate, and can usually convince themselves that their despotism is benevolent. Don’t count on getting the best of this class-act person. He’s got it all figured out and he knows precisely how to keep it that way.`,
    love: `The Virgo/Snake’s love picture is a tiny bit smudgy. You see, Snakes tend to slink in and out of a variety of love affairs throughout their lives. Virgos are rather more constant, yet they are sensuous as well. The tendency is toward slip-sliding away. Virgo/Snake makes the transition from passion to camaraderie smoothly. He remains friends with his “exes.” If you love a Virgo/Snake, you will be so mad for him or her that the very idea of “handling” will not occur to you. But the way to deal with this person, happily, is simply not to try. Don’t manipulate him. He doesn’t take kindly to machinations behind his back. Don’t make fun of him. He’ll take offense. Respect him and accept the dense soul that belongs to all natives of this sign. Admire the intellect but don’t, for heaven’s sake, fawn!`,
    compatibilities: `You are turned on by Oxen and Roosters. If I were you I would stick with those born in Taurus, Scorpio and Capricorn. Don’t shed your skin over Gemini, Sagittarius or Pisces/Tigers. Take no for an answer from a Gemini/Monkey. Whatever you do, don’t get tangled up in a plot to marry a Pig. It could be detrimental to your health and will certainly be disastrous to the Pig’s.`,
    homeAndFamily: `Virgo/Snakes tend to enjoy their freedom and covet being unencumbered. Their surroundings are not of much importance to them, as they are so often on the road. They do like comfort, so you’ll see a few easy chairs scattered about and there’ll be plenty of good vittles in the larder. But Virgo/Snakes are not homebody types.

If this person does become a parent, he or she will probably indulge the children in whims of all sorts, letting well enough alone and hoping for the best. The Virgo/Snake is autocratic but he’s not domineering or interested in policing lives. This parent will have fun with his kids, as he likes a good laugh and can readily join a group of any age for a few giggles. The Virgo/Snake child will be beautiful to look at and carries himself with that dignified coldness I spoke of earlier. He will probably like parties and astonish you and his teachers with his intellectual skill. There is not much you can do to spoil such a child, as his very presence will demand just the amount of attention he feels he deserves. There is no place in this child’s life for parental sarcasm. It enrages him.`,
    profession: `Mostly industrious, the Virgo/Snake only occasionally slides into a laziness rut. He’s gifted in things technical from childhood and will know how to build models and fiddle with handiwork projects requiring great attention to detail. This, coupled with his exceptional native intelligence, gives Virgo/Snake a definite edge in all scientific areas and in careers requiring mathematical skill. Cultural activities also attract the Virgo born in a Snake year. The arts, in general, will be tempting as a profession.

As a boss, Virgo/Snake will personify the expression “noblesse oblige.” He’s so naturally ahead of the game that to question his authority would be silly. He’s probably fair and just because he is particularly altruistic. In any case, efficiency will be the rule. This person makes a dutiful and happy addition to any work group. Virgo/Snake employees are both responsible and capable of handling delegated work. They are also able to work alone at jobs requiring precision and application of self-discipline. Virgo/Snakes usually work to live and not the opposite. They like to spend money, so they work for it. But they are not driven by any Protestant work ethic. They adore tropical vacation spots where their chilly nature can absorb the Sun’s healing rays.

Careers that suit this subject are: computer programmer, research scientist, economist, copy editor, engineer, architect, auditor.`,
  },
  "Virgo/Horse": {
    description: `The marriage of Virgo and Horse is one both lofty and elegant. Horses are self-motivated strivers, doers of grand deeds and sometimes—with all of their parading—a mite foolish and overly passionate. The Virgo, as we all know by now, is reserved. He takes care never to go outside the lines in the coloring book of life. Virgo is tasteful and a bit of a nit-picker to boot. Do you begin to see what I see? Here you have all the talent and prance of the Horse character, tempered just so by Virgo’s reticence and discrimination. And in the other direction we get, perhaps even more glaringly, a Virgo whose reserve is peeled away just far enough so that he knows precisely how to reach the masses. You see, some Virgos really suffer from their retiring natures. They are often unable to suffer contact with just anybody. We say they are discriminating. Some might more callously remark that they are fussy and persnickety, choosy and difficult. Horse comes along in this sign and gives the fusty old Virgo a kick in his bony derriere—just what the Virgo needed to feel good about himself again. A healthy measure of that Horsey self-possession and the Virgo born Horse is off and running.

Normally Horses are accused of selfishness and are known to be excessive in their dress. But the Virgo/Horse person is drier, more metallic than most, and for that reason more conservatively got up. Your Virgo/Horse will be heartbreakingly attractive to look at. This person has the kind of stately charm that appeals to everybody from grandma to the pooch. The Virgo/Horse is immensely talented, too. Imagination here is tamed but not smothered. Creativity is controlled. Rebelliousness is quelled by Virgo’s sense of duty and social decorum. The merits of Virgo/Horse are many. He can drive himself. He can innovate. He can teach. And this character can perform brilliantly.

One or two small details: Virgo/Horses tend to be conceited. The Horse personality already suffers from inflated self-image. Virgo’s snobbery doesn’t help. This person is a social climber who canters rather than climbs. Secondly, the Virgo born Horse is rankly pragmatic. Whatever serves to move this person from one point to the next will be acceptable behavior as far as he’s concerned, even if he has to trample an underling or two on the way to the executive lavatory. Virgo/Horses are fairly unscrupulous about gain and achievement. They are thorough and damn good workers. But they like to hog the spotlight.

With this, the Virgo born Horse is also charitable. He is an espouser of causes and enjoys being seen as a person who cares about others. All in all, the Virgo/Horse is well balanced and understands his role in life, knows how to keep his nose clean and doesn’t throw his weight around. This person is affable. People honestly enjoy his or her company and respect his opinions. In short, this subject is a solid entity and declares as much without false modesty. He’s enthusiastic and deserving of admiration.`,
    love: `Sex appeal is hardly a sufficient term to attribute to the Virgo/Horse’s seductive self. People virtually fall at this character’s discreetly shod feet. Naturally, he knows how amiably appealing he is. The Virgo/Horse is gifted for romance and is remarkably creative sexually. In fact, this person appears dignified and a mite dry. But in bed, he or she is sweetness personified. If you love one of these characters you might as well know right away that you are not alone in your passion. Virgo/Horses tend to flirt and are given to “running around”. They want and even need a sound and serious homey relationship in the background, but when they go on those little trips alone well, who could resist? Certainly not the beautiful Virgo/Horse.`,
    compatibilities: `The Virgo in you inclines most naturally to Taurus, Cancer, Scorpio and Capricorn subjects. From among their ranks don’t hesitate to choose Dogs or Tigers. Your emotions dovetail perfectly with both Scorpio and Cancer/Sheep. You won’t find easy harmony with Gemini, Sagittarius or Pisces/Rats. Nor will it be a snap to reach an understanding with Pisces/Monkey persons. Stick to liking people who like you back.`,
    homeAndFamily: `The Virgo/Horse is definitely a shade on the bourgeois side. He or she will want a home with perfect proportions and the finest furnishings. If he can afford them, the Virgo/Horse will have servants. But he will be friendly with his slaves. And the parties and fêtes he throws promise to be written up in (at least) Vogue.

The Virgo/Horse is an enthusiastic parent who enjoys doing things with his or her kids. This parent will insist that his or her children stay in line and especially that they show good performance in school. As this character is glaringly attractive, kids will sort of “fall in love” with a Virgo/Horse parent and admire her almost too adoringly. The Virgo/Horse mother or father should be careful never to condescend to the children.

As a kid, this person is a joy to parents. Virgo/Horse kids demand a lot of attention. But they are so cute that not even the cruelest wicked stepmother or father can resist their wiles. Early on in the Virgo/Horse’s life his talents should be assessed and catered to. This youngster is special and will need training and discipline to help him or her toward a successful starring role in adult life.`,
    profession: `Virgo/Horses are gifted for public life. They have the innate ability to charm thousands and can think of new methods of keeping their audience spellbound every three seconds. Virgo/Horse is also creative and is able to slave long hours over an artistic project. Whatever this character chooses to do, he will make it his business to do it better than other people. He has no time for failure, which, should it befall him, he knows he could not easily survive.

As a boss, this person is demanding and strict. He wants things done right. But he is also able to accomplish any chore, no matter how lowly, by himself. This means that his employees will either work hard and respect him or they will have to quit. As an employee, the Virgo/Horse is serious and driving. He wants to get ahead and knows that by hook or by crook he will. He’s able to accept servitude so long as he sees a light at the end of the tunnel and knows he will excel on the other end.

Careers suitable to this subject are: public relations, TV or entertainment personality, artist, realtor, publisher, politician, composer, journalist.`,
  },
  "Virgo/Goat": {
    description: `The Virgo/Goat is a quaint sort of a person. He’s both shy and retiring and yet, at the same time, rather anxious to be noticed. This character is a bundle of contradictions. He wants to be left alone, but he’d rather like it if you would please pay a lot of attention to him while you are ignoring him. The Virgo/Goat is a fusser and a worrier. He’s a perfectionist who loves beauty and appreciates art. He’s a dreamer who can be mightily impractical about everyday matters such as paying the bills and keeping the car filled with gas. Yet, this same person is often a stickler for applying the letter of the law in situations where a bit of leniency might be more appropriate.

This person is endowed with a colossal sense of duty. He or she will perform brilliantly at any job that requires both artistic flair and precision. The Virgo/Goat is a bit of a snob, too. He likes to frequent “the right” people and be seen in all the proper places. He’s not a social climber, mind you. It’s more a question of needing to be reassured that his surroundings and his pals are of a certain reliable ilk. Virgo/Goat is not so much interested in wealth as he is in prestige. He’s attracted to power and even to powerful people. But he doesn’t really want to wield the power himself. He’s quite content to stand just behind the throne and pull a string or two to make the king’s eyes blink.

The Virgo/Goat is dependent emotionally. He needs the constant approbation of his public. He’s a performer of one sort or another and doesn’t take kindly to being asked to relinquish his limelight. Yet, in his own mind, this person is modest to a fault. He sees himself as a simple soul, pure and untainted by crass ambition. This penchant for self-delusion is one of the Goat’s most outstanding characteristics. He simply cannot see himself as others see him. And others see him as a bit of a poseur, a person who affects attitudes and strikes poses to gain attention.

The Virgo/Goat’s behavior is often quite childish. He is given to tantrums and scenes. He’s a sulker, too. If he doesn’t get his way, he can be found sitting in a corner somewhere muttering and glowering at the injustice of it all. He’s ultrasensitive to criticism, yet he’s often very critical of others. He doesn’t take well to being teased, either. This person needs to be taken seriously. He’s easily hurt and takes a long time to forgive an injustice. The Goat born Virgo is a fragile soul whose resilience is his best attribute. He always bounces back.`,
    love: `In sentimental affairs the Virgo/Goat is a bit of a butterfly. He flits from flower to flower, sipping here and tasting there, never quite sure where he wants to alight for good. He’s a romantic and can be very giving to those he loves. But he’s also very touchy. If you love a Virgo/Goat, you will have to watch your step. Don’t tread on his dreams. Don’t mock his projects or scoff at his plans. Virgo/Goats are serious about their lives and want you to respect their endeavors. They like to be coddled and even spoiled. If you want to keep your Virgo/Goat happy, don’t hesitate to bring him or her breakfast in bed.`,
    compatibilities: `You get on well with Cats, Pigs and Horses. Those born in Taurus, Cancer, Scorpio and Capricorn are particularly suited to your dependent nature. Avoid all Oxen, but especially those born in Aries, Gemini, Libra and Aquarius. They are far too plodding for your capricious and artistic soul.`,
    homeAndFamily: `The Virgo/Goat’s home will reflect his artistic nature. It will be filled with beautiful objects and probably lean toward the cluttered side. This person is a collector. He or she likes to keep things. The decor will be soft and comfortable, with lots of cushions and cozy corners. The Virgo/Goat is a homebody and loves to entertain. He or she will be a gracious host, making sure everyone is comfortable and well-fed.

As a parent, the Virgo/Goat is loving but not terribly strict. He or she will want the children to be happy and will encourage their artistic and creative bents. Discipline may be a problem, as this parent is not fond of saying no. The Virgo/Goat child will be sensitive and dreamy. He or she will need a lot of encouragement and support to feel secure. This child is likely to be artistic and should be given plenty of opportunities to express his or her creativity.`,
    profession: `The Virgo/Goat is happiest in careers that allow for creativity and self-expression. He or she is not suited to jobs that require a lot of routine or strict adherence to rules. This person needs freedom to create and to dream. The Virgo/Goat is a perfectionist, so any work he or she does will be of high quality. This person is also good at working with others, as long as he or she feels appreciated.

As a boss, the Virgo/Goat can be demanding but fair. He or she will expect a lot from employees but will also be generous with praise and rewards. As an employee, the Virgo/Goat is diligent and creative but may have trouble with deadlines and routine tasks.

Careers suitable to the Virgo/Goat are: artist, designer, writer, musician, actor, interior decorator, art dealer.`,
  },
  "Virgo/Monkey": {
    description: `The Virgo/Monkey is a busybody. He’s a schemer and a plotter, a conniver whose agile mind is always three steps ahead of even the shrewdest among us. This person is a master of ruse and deception. He’s not dishonest, mind you. It’s just that he’s so clever at getting what he wants that sometimes he has to resort to some pretty fancy footwork to keep all of his balls in the air. The Virgo/Monkey is a talker. He loves to discuss and debate and argue. He’s a natural-born entertainer who can keep a crowd amused for hours with his wit and charm.

This person is also very practical. The Virgo influence gives him a love of order and efficiency. He’s not one to let the grass grow under his feet. If there’s a job to be done, the Virgo/Monkey will do it—and do it well. He’s a perfectionist who takes pride in his work. But he’s also a bit of a show-off. He likes to be noticed and appreciated for his efforts.

The Virgo/Monkey is stable in his own way. He’s not one to take big risks or make sudden changes. He prefers to plan and plot his way to success. But he’s also an opportunist. If he sees a chance to get ahead, he’ll take it, even if it means bending the rules a little. This person is not above using his charm and wit to get what he wants.

The downside of the Virgo/Monkey is his tendency toward selfishness. He’s so focused on his own goals and desires that he sometimes forgets about the needs of others. He can also be a bit manipulative, using his cunning to get his way. But he’s not malicious. He just wants to win.`,
    love: `In love, the Virgo/Monkey is a charmer. He’s witty and fun, and he knows how to make his partner feel special. But he’s also a bit of a flirt. He enjoys the chase and may not be ready to settle down right away. If you love a Virgo/Monkey, you’ll need to keep him entertained. He gets bored easily and needs a partner who can keep up with his quick mind and lively spirit. Be prepared for a lot of conversation and a bit of friendly debate. This person loves to talk and will expect you to keep up.`,
    compatibilities: `You get on well with Dragons and Rats, particularly those born in Taurus, Cancer, Scorpio and Capricorn. Avoid Snakes and Tigers, especially those born in Gemini, Sagittarius and Pisces. They’re too serious for your playful nature.`,
    homeAndFamily: `The Virgo/Monkey’s home will be a lively place, full of activity and conversation. He’s not one for quiet evenings at home. He likes to entertain and will often have friends over for dinner or drinks. His home will be well-organized but not fussy. He likes things to be neat but not sterile.

As a parent, the Virgo/Monkey is fun and engaging but not terribly strict. He’ll want his children to be clever and quick like him, and he’ll encourage their intellectual pursuits. He may have trouble with discipline, as he’s more interested in being a friend than a parent. The Virgo/Monkey child will be bright and curious, always asking questions and getting into mischief. He’ll need a lot of stimulation and activity to keep him out of trouble.`,
    profession: `The Virgo/Monkey is suited to careers that require quick thinking and a lot of interaction with others. He’s a natural salesman and a great communicator. He’s also good at problem-solving and can think on his feet. This person is happiest in a fast-paced environment where he can use his wit and charm to get ahead.

As a boss, the Virgo/Monkey is demanding but charismatic. He’ll expect a lot from his employees but will also know how to motivate them. As an employee, he’s hardworking and efficient but may have trouble following orders if he thinks he has a better idea.

Careers suitable to the Virgo/Monkey are: salesperson, advertising executive, public relations, journalist, lawyer, entrepreneur, comedian.`,
  },
  "Virgo/Rooster": {
    description: `The Virgo/Rooster is a strutter. He’s a preener and a prancer, a person who loves to show off his feathers and crow about his accomplishments. But he’s also a Virgo, which means he’s got a practical, down-to-earth side that keeps his cockiness in check. This person is a hard worker who takes his responsibilities seriously. He’s a perfectionist who wants everything to be just so.

The Virgo/Rooster is enthusiastic and candid. He says what he thinks and doesn’t hold back. This can make him a bit abrasive at times, but it also means you always know where you stand with him. He’s a conservative at heart and likes things to be orderly and predictable. He’s not one for big risks or sudden changes.

This person has a great sense of humor and loves to entertain. He’s a natural performer who can light up a room with his wit and charm. But he’s also a bit of a pedant. He loves to lecture and can be a bit bossy at times. He’s convinced he’s right and doesn’t take kindly to being challenged.

The Virgo/Rooster is resilient and can bounce back from setbacks with ease. He’s not one to dwell on failure. He picks himself up, dusts himself off, and gets back to work. But he can also be a bit of a spendthrift. He loves the finer things in life and isn’t afraid to spend money to get them.`,
    love: `In love, the Virgo/Rooster is passionate and devoted but also a bit demanding. He wants a partner who will admire him and support his ambitions. He’s not one for casual flings. He wants a serious, committed relationship. If you love a Virgo/Rooster, be prepared to put up with his bossiness and his need to be the center of attention. He’ll reward you with loyalty and affection, but he’ll expect the same in return.`,
    compatibilities: `You get on well with Oxen, Snakes and Dragons, particularly those born in Taurus, Cancer, Scorpio and Capricorn. Avoid Cats, especially those born in Gemini, Sagittarius and Pisces. They’re too retiring for your outgoing nature.`,
    homeAndFamily: `The Virgo/Rooster’s home will be stylish and well-kept. He’s a bit of a neat freak and likes everything to be in its place. He’s also a bit of a show-off, so his home will be filled with beautiful objects that reflect his good taste. He loves to entertain and will often have friends over for dinner or cocktails.

As a parent, the Virgo/Rooster is strict but loving. He’ll want his children to succeed and will push them to do their best. He may be a bit critical at times, but it’s only because he wants the best for them. The Virgo/Rooster child will be bright and outgoing but may have trouble with authority. He’ll need a firm hand to keep him in line.`,
    profession: `The Virgo/Rooster is suited to careers that require precision and attention to detail. He’s a natural leader and does well in positions of authority. He’s also a great communicator and can inspire others with his enthusiasm. This person is happiest in a structured environment where he can show off his skills and be recognized for his efforts.

As a boss, the Virgo/Rooster is demanding but fair. He’ll expect a lot from his employees but will also reward them for their hard work. As an employee, he’s diligent and efficient but may have trouble taking orders if he thinks he knows better.

Careers suitable to the Virgo/Rooster are: manager, editor, teacher, accountant, lawyer, architect, surgeon.`,
  },
  "Virgo/Dog": {
    description: `The Virgo/Dog is a worrier. He’s a serious, introspective soul who takes life a bit too seriously. This person is a thinker who spends a lot of time analyzing and observing the world around him. He’s intelligent and perceptive but also a bit cynical. He doesn’t trust easily and tends to see the glass as half empty.

The Virgo/Dog is loyal and constant. Once he commits to something or someone, he’s in it for the long haul. He’s not one for casual relationships or fleeting interests. He takes his responsibilities seriously and will go to great lengths to fulfill his obligations. But he’s also a bit unsociable. He prefers his own company to that of others and can be a bit of a loner.

This person is independent and doesn’t like to rely on others. He’s stubborn and can be belligerent if pushed. He’s not one to back down from a fight, especially if he thinks he’s in the right. But he’s also capable of great kindness and compassion. He’s a loyal friend who will stand by you through thick and thin.

The Virgo/Dog can be a bit lazy at times. He’s not one for unnecessary exertion and prefers to conserve his energy for things that really matter. But when he’s motivated, he’s a hard worker who will stop at nothing to get the job done.`,
    love: `In love, the Virgo/Dog is loyal and devoted but not terribly demonstrative. He’s not one for grand gestures or public displays of affection. He shows his love through actions rather than words. If you love a Virgo/Dog, you’ll need to be patient. He takes time to open up and trust. But once he does, he’s a partner for life.`,
    compatibilities: `You get on well with Tigers, Horses and Cats, particularly those born in Taurus, Cancer, Scorpio and Capricorn. Avoid Dragons, especially those born in Gemini, Sagittarius and Pisces. They’re too flamboyant for your serious nature.`,
    homeAndFamily: `The Virgo/Dog’s home will be simple and functional. He’s not one for flashy decor or unnecessary frills. He likes things to be neat and orderly, and he’s a bit of a neat freak. He’s not much for entertaining, preferring quiet evenings at home with a good book or a favorite hobby.

As a parent, the Virgo/Dog is strict but fair. He’ll want his children to be responsible and hardworking like him. He may be a bit critical at times, but it’s only because he wants the best for them. The Virgo/Dog child will be serious and thoughtful. He’ll need a lot of reassurance and support to feel secure.`,
    profession: `The Virgo/Dog is suited to careers that require analysis and observation. He’s a natural problem-solver and does well in jobs that require attention to detail. He’s also a good leader, as he’s fair and just. This person is happiest in a quiet, structured environment where he can work at his own pace.

As a boss, the Virgo/Dog is demanding but reasonable. He’ll expect a lot from his employees but will also be there to support them. As an employee, he’s hardworking and reliable but may have trouble with authority if he feels it’s unjust.

Careers suitable to the Virgo/Dog are: researcher, analyst, detective, librarian, accountant, scientist, counselor.`,
  },
  "Virgo/Pig": {
    description: `The Virgo/Pig is a refined soul. He’s a cultured, sensitive person who loves the finer things in life. He’s a sensualist who enjoys good food, good wine, and good company. But he’s also a Virgo, which means he’s got a practical, down-to-earth side that keeps his excesses in check. This person is scrupulous and honest. He prides himself on his integrity and will go to great lengths to do the right thing.

The Virgo/Pig is gallant and charming. He’s a natural host who loves to entertain and make others feel comfortable. He’s sincere and straightforward, and you always know where you stand with him. But he’s also a bit naive. He tends to believe the best of people and can be easily taken advantage of.

This person is a bit of a hedonist. He loves pleasure and isn’t afraid to indulge. But he’s also hardworking and responsible. He knows how to balance his love of luxury with his need to get things done. The Virgo/Pig can be a bit hotheaded at times. He’s passionate and can get carried away by his emotions. But he’s also quick to forgive and doesn’t hold grudges.`,
    love: `In love, the Virgo/Pig is romantic and devoted. He’s a sensualist who loves to pamper his partner. He’s not one for casual flings. He wants a deep, meaningful relationship. If you love a Virgo/Pig, be prepared for a lot of affection and attention. He’ll want to spoil you and make you feel special. But he’ll also expect the same in return.`,
    compatibilities: `You get on well with Cats and Goats, particularly those born in Taurus, Cancer, Scorpio and Capricorn. Avoid Snakes, especially those born in Gemini, Sagittarius and Pisces. They’re too cunning for your honest nature.`,
    homeAndFamily: `The Virgo/Pig’s home will be warm and inviting. He loves comfort and will fill his home with soft furnishings and beautiful objects. He’s a great host and loves to entertain. His home will be a place where friends and family feel welcome and cared for.

As a parent, the Virgo/Pig is loving and indulgent. He’ll want his children to have the best of everything and will go out of his way to make them happy. He may have trouble with discipline, as he’s not fond of saying no. The Virgo/Pig child will be charming and sensitive. He’ll need a lot of love and attention to feel secure.`,
    profession: `The Virgo/Pig is suited to careers that allow him to use his creativity and charm. He’s a natural host and does well in jobs that involve entertaining or working with people. He’s also a hard worker who takes pride in doing a good job. This person is happiest in a comfortable, supportive environment where he can shine.

As a boss, the Virgo/Pig is generous and fair. He’ll expect a lot from his employees but will also be there to support them. As an employee, he’s hardworking and reliable but may have trouble with routine tasks.

Careers suitable to the Virgo/Pig are: chef, event planner, interior designer, art dealer, musician, writer, hotel manager.`,
  },
};
