
export const BOOK = {
  foundation: {
    ben_ming: `Ben Ming Nian ( 本命年 / 值太岁 ): The Year of One's Birth Sign. Zhi Tai Sui ( 值太岁 ) occurs when annual zodiac matches birth sign—every twelve years at ages 12, 24, 36, 48, 60, 72, 84. The classical formulation " 太岁当头坐，⽆喜必有祸 " (When Tai Sui sits above, without joy there must be misfortune) captures its dual potential: intensified energy amplifies both achievement and vulnerability . Traditional characteristics include: emotional volatility from resonant native energy; health vulnerability in element-associated organ systems; relationship turbulence as heightened sensitivity produces both deeper intimacy and more frequent conflict; career obstacles with recognition delays; and financial instability with unexpected expenses. Modern reframing treats Ben Ming Nian as natural developmental transition points.`,
    clash: `Direct Clash Years ( 冲太岁 ): Opposition and Confrontation. Direct Clash years ( 冲太岁 , Chong Tai Sui) occur when annual branch stands six positions opposite (180 degrees) from birth branch, creating maximum energetic confrontation. The six clash pairs are: Rat-Horse, Ox-Goat, Tiger-Monkey, Rabbit-Rooster, Dragon-Dog, and Snake-Pig. Traditional interpretation emphasizes sudden, dramatic disruption: forced relocation, unexpected career termination, relationship dissolution, health crises, and financial volatility. Classical advice focuses on "using movement to respond to movement"—proactive travel or strategic change rather than resistance.`,
    harm: `Harm Years ( 害太岁 ): Covert Damage and Betrayal. Harm years ( 害太岁 , Hai Tai Sui) operate through concealed mechanisms rather than overt confrontation, making them particularly insidious. The six harm pairs are: Rat-Goat, Ox-Horse, Tiger-Snake, Rabbit-Dragon, Monkey-Pig, and Rooster-Dog. Traditional characteristics include: betrayal by trusted associates with hidden grievances; miscommunication with authority figures damaging career trajectory; gradual financial drain through unexamined expenses or exploitative relationships; chronic health deterioration with asymptomatic development; and project failure through overlooked details.`,
    destroy: `Destruction Years ( 破太岁 ): Rupture and Financial Loss. Destruction years ( 破太岁 , Po Tai Sui) are characterized by fragmentation, dissolution, and structural failure. The six destruction pairs are: Rat-Rooster, Ox-Dragon, Tiger-Pig, Rabbit-Horse, Snake-Monkey, and Goat-Dog. Traditional interpretation emphasizes: partnership dissolution through accumulated incompatibility; unexpected major expenses depleting reserves; project failure near completion from structural weaknesses; investment losses from overconfidence; and reputation damage through association with failing enterprises.`,
    alliance: `Alliance Years ( 三合 / 六合 ): Harmonious Support and Prosperity. Alliance years comprise two distinct harmonious relationships: San He ( 三合 , Triple Harmony) and Liu He ( 六合 , Six Harmonies) . San He alliances form elemental triads: Monkey-Rat-Dragon (Water), Snake-Rooster-Ox (Metal), Tiger-Horse-Dog (Fire), and Pig-Rabbit-Goat (Wood). Liu He alliances create optimal yin-yang pairings: Rat-Ox, Tiger-Pig, Rabbit-Dog, Dragon-Rooster, Snake-Monkey, Horse-Goat. Traditional interpretation promises "Noble Persons" (贵⼈)— beneficial allies appearing unexpectedly; effortless progress with obstacles dissolving; and successful collaboration.`,
    neutral: `Neutral Years ( 平年 ): Unremarkable Transitional Periods. Neutral years ( 平年 , Ping Nian) comprise 4-5 years per 12-year cycle with no special Tai Sui relationship—neither conflict nor alliance . These periods are characterized by absence of dramatic cosmic influence, where individual effort and circumstance determine outcomes . Traditional interpretation emphasizes "cultivating virtue and awaiting opportunity"—steady progress without dramatic breakthrough.`,
  },
  animals: {
    Rat: {
      self: `Rat Ben Ming Nian (Earthly Branch Zi ⼦): Periods of " ⼼神不宁 " (spiritual and mental instability)—where native intelligence, adaptability, and resourcefulness become sources of impulsiveness, anxiety, and opportunism. The concentrated yin Water resonance creates emotional flooding: rapid mood fluctuations, obsessive rumination, and difficulty maintaining consistent judgment. Specific traditional vulnerabilities include: kidney and urinary system disorders, stress-related conditions, and financial speculation losses. Modern perspectives view this as a natural identity consolidation period.`,
      clash: `Rat-Horse Clash (Zi-Wu ⼦午冲): One of the most dramatic elemental conflicts: concentrated yin Water versus intense yang Fire—mutual extinction. Traditional sources identify this as "chong tai sui" at maximum strength, with major variation across all life domains. Management strategies include comprehensive contingency planning and using movement to respond to movement.`,
      harm: `Rat-Goat Harm (Zi-Wei ⼦未相害): Operates through subtle Earth-Water interaction where Goat's Earth element appears to stabilize Rat's Water while gradually absorbing and depleting its vitality. Manifests through concealment: betrayal by trusted associates, authority miscommunication, and gradual resource drain. Risk management requires background verification and enhanced documentation.`,
      destroy: `Rat-Rooster Destruction (Zi-You ⼦⾣破): Involves Metal-Water interaction where Rooster's Metal precision and structure progressively fragment Water's fluid adaptability. Associated with partnership dissolution, unexpected repair costs, and liquidity problems. Strategic response emphasizes structural stress-testing and financial conservatism.`,
      alliance: `Rat Alliances (Shen-Zi-Chen 申⼦⾠ Water triad and Zi-Chou ⼦丑 Liu He): Dragon and Monkey years bring large-scale achievement and innovation. Ox years provide optimal yin-yang stabilization ("fu qi zhi qin"). These periods reward broad relationship investment and complementary skill combination.`,
      neutral: `Rat Neutral Years (Tiger, Rabbit, Snake, Dog, Pig): Dynamics emphasize incremental advancement through sustained effort. This unremarkability demands self-generated momentum maintenance. Focused skill development and relationship consolidation are optimal during these periods.`
    },
    // Adding short versions for others to save space, but keeping structure
    Ox: { self: "Ox Ben Ming Nian: Amplification of natural persistence into rigidity. Health concerns in digestive systems. Focus on disciplined goal-setting.", clash: "Ox-Goat Clash: Competition for identical Earth territory. Partnership strain and directional instability.", harm: "Ox-Horse Harm: Fire-Earth tension. Superior-subordinate tensions and reputation risk.", destroy: "Ox-Dragon Destruction: Wet-Dry Earth conflict. Project failure and trust erosion.", alliance: "Ox Alliances: Snake, Rooster, and Rat years. Strategic precision and quality achievement.", neutral: "Ox Neutral Years: Tiger, Rabbit, Monkey, Dog, Pig. Consolidation and foundation-building." },
    Tiger: { self: "Tiger Ben Ming Nian: Aggression recoil and authority challenges. Liver fire imbalance. Focus on assertive leadership.", clash: "Tiger-Monkey Clash: Metal-Wood combat. Legal entanglements and competitive losses.", harm: "Tiger-Snake Harm: Concealed Fire-Wood tension. Insidious undermining.", destroy: "Tiger-Pig Destruction: Wood-Water imbalance. Resource depletion and emotional exhaustion.", alliance: "Tiger Alliances: Horse, Dog, and Pig years. Dynamic achievement and community building.", neutral: "Tiger Neutral Years: Rat, Ox, Rabbit, Dragon, Goat, Rooster. Sustained momentum." },
    Rabbit: { self: "Rabbit Ben Ming Nian: Heightened emotional receptivity. Relationship turbulence. Focus on emotional intelligence.", clash: "Rabbit-Rooster Clash: Direct Metal-Wood confrontation. Romantic disruption and aesthetic conflict.", harm: "Rabbit-Dragon Harm: Wood-Earth subjugation. Reputation damage and hidden competition.", destroy: "Rabbit-Horse Destruction: Fire-Wood consumption. Passion-driven losses and impulsive decisions.", alliance: "Rabbit Alliances: Goat, Pig, and Dog years. Creative collaboration and nurturing relationships.", neutral: "Rabbit Neutral Years: Rat, Ox, Tiger, Snake, Monkey, Rooster. Quiet cultivation." },
    Dragon: { self: "Dragon Ben Ming Nian: Power consolidation and visibility risks. Transformation overload. Focus on public accountability.", clash: "Dragon-Dog Clash: Earth element polarization. Loyalty tests and institutional challenges.", harm: "Dragon-Rabbit Harm: Wood-Earth subjugation. Subordinate rebellion and detail oversight.", destroy: "Dragon-Ox Destruction: Wet-Dry Earth conflict. Foundation erosion and resource misallocation.", alliance: "Dragon Alliances: Rat, Monkey, and Rooster years. Innovation cycles and market expansion.", neutral: "Dragon Neutral Years: Tiger, Snake, Horse, Goat, Pig. Authority maintenance." },
    Snake: { self: "Snake Ben Ming Nian: Wisdom tested and secret exposure. Patience exhausted. Focus on transparency balance.", clash: "Snake-Pig Clash: Fire-Water elemental extinction. Financial liquidation and emotional flooding.", harm: "Snake-Tiger Harm: Concealed Wood-Fire tension. Rival ambush and health fire imbalance.", destroy: "Snake-Monkey Destruction: Fire-Metal corrosion. Technological obsolescence.", alliance: "Snake Alliances: Ox, Rooster, and Monkey years. Strategic precise and innovation partnerships.", neutral: "Snake Neutral Years: Tiger, Rabbit, Horse, Goat, Pig. Strategic consolidation." }
  }
};
