/**
 * @fileOverview Verbatim definitions for Personal Years and Seasonal Phases.
 */

export const YEAR_DESCRIPTIONS: Record<number, any> = {
  1: {
    title: "Year of Origins",
    sub: "New Beginnings · The Monad · Spring Equinox",
    planet: "☉ Sun / Surya",
    season: "spring",
    phase: "Spring Equinox — Seed Planting",
    chakra: "Manipura (Solar Plexus)",
    kw: ["Initiation", "Independence", "Self-Definition", "Leadership", "Courage", "Pioneer"],
    isCrit: false,
    desc: `Year 1 — The seed year. The nine-year cycle resets. Whatever you initiate now carries influence across the following eight years. Independence, bold initiative, and self-determination are essential — passivity wastes the single most potent planting window of the cycle. Claim your authority over your own direction.`,
    pyth: `Spiritual challenge: individuation — claiming authentic existence separate from collective definitions. This is not selfishness but its precondition. One cannot give something genuine until one has become someone genuine. The practice appropriate to Year 1 is cultivating presence with the uncertainty of genuine new beginnings rather than prematurely seeking the comfort of familiar patterns in new clothing.`,
    vedic: `Governed by Surya — the Sun, source of light, life, and conscious will in Vedic cosmology. Surya's influence activates the Manipura chakra (solar plexus), center of personal power, metabolic fire, and the will to manifest. Physical vitality increases, supporting the ambitious undertakings Year 1 calls for.`,
    chinese: `Maps to the Lo Shu square's North position — Water element, Kan trigram (The Abysmal). Water in Year 1 paradoxically complements the year's initiating energy: effective initiation requires the Water qualities of depth, adaptability, and accurate reading of conditions, not merely the assertion of will.`,
    chald: `The 10/1 compound (Wheel of Fortune) carries karmic momentum — past cycle actions create this year's opportunities. The Wheel has turned in your favor; timing factors are particularly supportive. 19/1 (Sun, carrying karmic complexity) indicates patterns from previous cycles of misused power creating present requirement for genuine ego purification.`,
    overview: `Personal Year 1 is the cycle's threshold — the numerological monad, divine unity preceding multiplicity. In Pythagorean philosophy, 1 is the point without dimension that contains all dimensional possibility. In living experience: a year of heightened initiative, self-definition, and pioneering action.`,
    pr: [{i:"🌅",n:"Solar Meditation",d:"Sunrise practice facing east"},{i:"🙏",n:"Surya Namaskar",d:"12-round sun salutation cycle"},{i:"🎯",n:"Vision Architecture",d:"Nine-year arc visualization"},{i:"⚡",n:"Yang Qigong",d:"Rising energy cultivation"}]
  },
  2: {
    title: "Year of Receptivity",
    sub: "Partnership · The Dyad · Late Spring Germination",
    planet: "☽ Moon / Chandra",
    season: "spring",
    phase: "Late Spring — Germination",
    chakra: "Swadhisthana (Sacral)",
    kw: ["Partnership", "Cooperation", "Patience", "Intuition", "Diplomacy", "Emotional Intelligence"],
    isCrit: false,
    desc: `Year 2 — The cooperation year. Push and the year fragments; wait, cooperate, and gather — and it compounds. Emotional sensitivity is heightened, making you both more empathic and more vulnerable to perceived slights. Diplomacy is not weakness here — it is the specific intelligence the year rewards.`,
    pyth: `Spiritually, Year 2 practices surrender to timing not self-determined. Where Year 1 acted on will, Year 2 waits on emergence. This is not passive resignation but active receptivity — maintaining prepared openness while allowing development to proceed at its own pace.`,
    vedic: `Assigned to Chandra — the Moon, governor of mind, emotion, memory, and cyclical fluctuation. Chandra's influence activates the Swadhisthana chakra (sacral center), seat of creativity, sexuality, and emotional flow.`,
    chinese: `Occupies the Lo Shu's Southwest — the most yin position, associated with Kun (Earth, pure yin), pure receptivity, devotion, and the Earth's nurturing capacity. Its counsel: "The receptive brings about sublime success."`,
    chald: `The 11/2 compound introduces master number intensity — the Illumination frequency amplifying Year 2's intuitive capacity toward potentially psychic levels while adding the challenge of nervous system hypersensitivity.`,
    overview: `Personal Year 2 introduces the dyad — polarity, the generative tension between self and other that makes development possible. This year's energy shifts dramatically from Year 1's initiating yang to cultivating yin.`,
    pr: [{i:"🌙",n:"Moon Salutations",d:"Evening Chandra Namaskar practice"},{i:"👂",n:"Deep Listening",d:"Daily practice of listening without response"},{i:"💧",n:"Dream Journaling",d:"Morning recording of dream imagery"},{i:"🤝",n:"Partnership Audit",d:"Honest inventory of collaborative health"}]
  },
  3: {
    title: "Year of Expression",
    sub: "Creative Bloom · The Triad · Early Summer",
    planet: "♃ Jupiter / Guru",
    season: "spring",
    phase: "Early Summer — Blossoming",
    chakra: "Vishuddha (Throat)",
    kw: ["Creativity", "Joy", "Communication", "Optimism", "Artistic Output", "Social Expansion"],
    isCrit: false,
    desc: `Year 3 — The creative year. Ideas flow, social connections multiply, and communication becomes your primary instrument. Share your gifts publicly. Creative projects begun now often become defining works of the cycle. Guard against scattered energy and superficiality.`,
    pyth: `The spiritual curriculum of Year 3 is recognizing creative expression as sacred — not merely entertainment but genuine participation in the ongoing creation of meaning. Jupiter teaches that genuine creative work is one of the highest forms of practice.`,
    vedic: `Jupiter (Guru, Brihaspati) governs Year 3, activating education, wisdom transmission, creative legacy, and the expansion of philosophical understanding. The Vishuddha chakra activation makes Year 3 ideal for mantra practice.`,
    chinese: `Year 3 maps to the East — Wood element, Zhen trigram (The Arousing). Zhen's image is thunder awakening the earth after winter's silence: the sudden, irresistible emergence of growth energy.`,
    chald: `The 21/3 (Crown of the Magi) is considered the most auspicious compound number in Year 3's expression — promising victory through creative effort and representing the individual whose authentic vision succeeds.`,
    overview: `Personal Year 3 completes the spring triad with blossoming — the visible expression of two years of invisible cultivation. This year's energy is expansive, joyful, and creatively fertile.`,
    pr: [{i:"🎨",n:"Daily Creation",d:"15 minutes of uncensored expression"},{i:"🗣",n:"Throat Mantra",d:"Ham seed mantra vibration practice"},{i:"📖",n:"Jupiter Journaling",d:"Evening gratitude extraction"},{i:"🌱",n:"East Activation",d:"Feng shui Wood element placement"}]
  },
  4: {
    title: "Year of Foundation",
    sub: "Structure · The Tetrad · Midsummer Labour",
    planet: "☊ Rahu (North Node)",
    season: "summer",
    phase: "Midsummer — Fruit-Setting",
    chakra: "Muladhara (Root)",
    kw: ["Discipline", "Foundation", "Systematic Effort", "Security", "Endurance", "Manifestation"],
    isCrit: true,
    desc: `Year 4 — First Trough. The cycle's most internally pressured period. You may feel invisible, restricted, unrewarded. This is by design — the year constructs permanent foundation for what follows. Abandoning structures in PY 4 creates losses requiring multiple subsequent years to recover. The grind is the gift.`,
    pyth: `Spiritually, Year 4 is the deepest form of trust: trusting the process when the process is hard, slow, and unspectacular. Root-level security comes from genuine foundation-building, not from Rahu's compulsive accumulation.`,
    vedic: `Rahu's governance makes Year 4 materials productive but spiritually complex. Rahu amplifies desire for material security while ensuring that no material acquisition fully satisfies — each creates the hunger for more.`,
    chinese: `Year 4 occupies the Lo Shu's Southeast — Xun trigram (Gentle Wind, Wood element), associated with wealth accumulation and the patient growth of trees. The tree's wealth builds through root-deepening.`,
    chald: `The 13/4 (Regeneration) carries Year 4's most significant karmic weight: transformation that comes through structural collapse. What falls in a 13/4 year must fall — fighting the collapse prolongs suffering.`,
    overview: `Personal Year 4 corresponds to midsummer's demanding conditions — fruit-setting under sustained heat, when systems must support growth and foundations are tested by pressure.`,
    pr: [{i:"🌍",n:"Grounding Practice",d:"Daily barefoot earth contact"},{i:"📊",n:"Financial Architecture",d:"Build one solid financial system"},{i:"🏋",n:"Physical Discipline",d:"Non-negotiable daily health routine"},{i:"🔧",n:"Skill Mastery",d:"One technical skill pursued to competence"}]
  },
  5: {
    title: "Year of Liberation",
    sub: "Change · The Pentad · Late Summer Winds",
    planet: "☿ Mercury / Budha",
    season: "summer",
    phase: "Late Summer — Harvest Preparation",
    chakra: "Anahata (Heart)",
    kw: ["Freedom", "Adaptability", "Change", "Travel", "Experimentation", "Transformation"],
    isCrit: false,
    desc: `Year 5 — Liberation and flux. Dynamic shifts, travel, and freedom arrive suddenly. Opportunities appear and expire fast — adaptability is a requirement. Clinging to PY 4's structures creates dangerous friction. The year rewards those who move with its chaotic energy.`,
    pyth: `The spiritual curriculum of Year 5 is freedom with integrity — the discovery that genuine liberation is not freedom from commitment but freedom within it. The traveler who finds themselves everywhere they go has discovered the gift.`,
    vedic: `Mercury (Budha) governs Year 5, activating commerce, communication, adaptability, and the nervous system's capacity for rapid processing. Life areas: travel, commerce, and technology.`,
    chinese: `Year 5 occupies the Lo Shu's central position — no fixed direction, no fixed element. The center is the point from which all directions radiate — and where all energies converge and can conflict.`,
    chald: `The 23/5 (Royal Star of the Lion) is Year 5's most fortunate compound — promising success through adaptability, charm, and the ability to attract assistance.`,
    overview: `Personal Year 5 introduces late summer's variability — harvest approaches but weather remains unpredictable, demanding adaptability above all else.`,
    pr: [{i:"✈️",n:"Intentional Adventure",d:"Plan one journey beyond your comfort zone"},{i:"🧘",n:"Pranayama",d:"Daily breathwork for nervous system regulation"},{i:"📚",n:"Edge Learning",d:"Study one discipline outside your expertise"},{i:"💚",n:"Heart Opening",d:"Anahata practices: loving-kindness meditation"}]
  },
  6: {
    title: "Year of Harmony",
    sub: "Service · The Hexad · Early Autumn Abundance",
    planet: "♀ Venus / Shukra",
    season: "summer",
    phase: "Early Autumn — Abundance Sharing",
    chakra: "Anahata (Heart — Venus aspect)",
    kw: ["Responsibility", "Beauty", "Service", "Relationships", "Home", "Creative Partnership"],
    isCrit: false,
    desc: `Year 6 — Home and service. The universe calls for nurturing and commitment to family, community, and those who depend on you. Beauty and harmony can be restored in troubled relationships. Guard against martyrdom — give generously but maintain the capacity for sustained service.`,
    pyth: `Spiritual curriculum of Year 6: agape — unconditional care that serves the beloved's genuine wellbeing rather than the lover's need to be needed. This is Venus at her most evolved.`,
    vedic: `Venus (Shukra) governs Year 6, activating marriage and committed partnership, aesthetic expression and creative arts, financial partnership, and beauty industries.`,
    chinese: `Year 6 maps to the Northwest — Qian trigram (Heaven, pure yang, Metal element), associated with helpful people, mentors, and heaven's support.`,
    chald: `The 24/6 (long-term love) emphasizes Year 6's deepest relationship gift: partnerships and commitments formed in a 24/6 year carry unusual staying power.`,
    overview: `Personal Year 6 distributes summer's abundance — harvest shared, responsibilities embraced, harmony restored after Year 5's winds of change.`,
    pr: [{i:"💐",n:"Venus Ritual",d:"Friday evening beauty ritual"},{i:"🏠",n:"Home Sanctuary",d:"Beautify your living space consciously"},{i:"🎭",n:"Creative Service",d:"Offer your specific creative gift"},{i:"⚖️",n:"Service Audit",d:"Are you giving freely or from obligation?"}]
  },
  7: {
    title: "Year of the Mystic",
    sub: "Introspection · The Heptad · Mid-Autumn Wisdom",
    planet: "☋ Ketu (South Node)",
    season: "autumn",
    phase: "Mid-Autumn — Inward Turning",
    chakra: "Ajna (Third Eye)",
    kw: ["Introspection", "Analysis", "Spiritual Depth", "Solitude", "Refinement", "Inner Knowing"],
    isCrit: true,
    desc: `Year 7 — Second Trough. The cycle's inward-turning. External ambitions yield little. Introspection, spiritual seeking, research, and deep analysis are what the year supports. Forcing external action creates compounding frustration. Use withdrawal for genuine inner work — you emerge in Year 8 with capabilities external action could never have produced.`,
    pyth: `Ketu's spiritual curriculum: the direct encounter with the ground of being — the experiential discovery of what exists beneath thought, beneath identity, beneath the story.`,
    vedic: `Ketu's governance makes Year 7 the most spiritually distinctive year. Ketu represents accumulated spiritual merit — wisdom mastered in previous incarnations that seeks expression.`,
    chinese: `Year 7 maps to the West — Dui trigram (Joyous Lake, Metal element), associated with completion, joy, and the harvest of inner refinement.`,
    chald: `The 25/7 (Strength Through Experience) carries the energy of earned wisdom — this Year 7 brings the full weight of accumulated life experience into conscious awareness.`,
    overview: `Personal Year 7 corresponds to mid-autumn's introspective quality — days shortening, attention withdrawing from external achievement to internal processing.`,
    pr: [{i:"🔮",n:"Meditation Intensive",d:"Establish daily 20+ minute sit"},{i:"📜",n:"Deep Study",d:"Pursue one area of profound inquiry"},{i:"🌌",n:"Ajna Activation",d:"Third eye practices: inner light meditation"},{i:"🌿",n:"Radical Simplification",d:"Remove what is genuinely inessential"}]
  },
  8: {
    title: "Year of Power",
    sub: "Authority · The Octad · Late Autumn Harvest",
    planet: "♄ Saturn / Shani",
    season: "autumn",
    phase: "Late Autumn — Final Harvest",
    chakra: "Manipura (Solar Plexus — Saturn)",
    kw: ["Achievement", "Authority", "Material Success", "Karma", "Power", "Accountability"],
    isCrit: false,
    desc: `Year 8 — The material peak. Sustained effort of seven years can now convert into tangible results — financial achievement, professional authority, recognition. Guard against arrogance and overreach: the very confidence that makes Year 8 productive can generate decisions so outsized they damage what they were meant to build.`,
    pyth: `Spiritual curriculum of Year 8: power in service of something genuinely larger than personal ambition. Power that has been seasoned through genuine experience.`,
    vedic: `Saturn (Shani) governs Year 8, activating career authority and peak professional expression, and the harvest — positive or corrective — of genuine effort.`,
    chinese: `Year 8 maps to the Northeast — Gen trigram (Keeping Still, Earth element), associated with knowledge, self-cultivation, and the mountain's inherent authority.`,
    chald: `The 17/8 (Star of the Magi) is Year 8's most powerful compound expression — material success accompanied by genuine spiritual authority.`,
    overview: `Personal Year 8 concentrates autumn's final productive energy — the last harvest, careful accounting, and preparation for winter.`,
    pr: [{i:"📋",n:"Karmic Accounting",d:"Honest inventory of built assets"},{i:"🏆",n:"Authority Claim",d:"Seek the leadership role earned"},{i:"🕰",n:"Saturn Discipline",d:"Establish one non-negotiable practice"},{i:"🌾",n:"Harvest Gratitude",d:"Ritually acknowledge every genuine fruit"}]
  },
  9: {
    title: "Year of Completion",
    sub: "Release · The Ennead · Winter Solstice Return",
    planet: "♂ Mars / Mangal",
    season: "autumn",
    phase: "Winter Solstice — Seed Return",
    chakra: "Muladhara (Root — Mars completion)",
    kw: ["Completion", "Release", "Compassion", "Endings", "Integration", "Preparation"],
    isCrit: false,
    desc: `Year 9 — The great releasing. Simultaneously ending and beginning. Release what no longer serves: relationships, habits, beliefs, identities. This releasing is not optional — the universe accomplishes it one way or another. Those who cling experience loss; those who release deliberately experience liberation and perfect preparation for Year 1.`,
    pyth: `The Ennead's mathematical paradox is Year 9's spiritual teaching: 9 multiplied by any number always reduces back to 9. Nine is the container that absorbs all things without losing itself.`,
    vedic: `Mars (Mangal) governs Year 9, bringing warrior energy to completion and the specific courage required to release what has served its purpose.`,
    chinese: `Year 9 maps to the South — Li trigram (The Clinging, Fire element), associated with fame, recognition, clarity, and illumination.`,
    chald: `Chaldean tradition views Year 9 as the year when the individual most closely touches the divine intelligence, if they release enough personal ego.`,
    overview: `Personal Year 9 completes the cycle with winter's approach — release, completion, and the preparation for renewal.`,
    pr: [{i:"🕯",n:"Completion Ritual",d:"Ceremonially close each chapter"},{i:"🌊",n:"Grief Honoring",d:"Allow natural grief of ending"},{i:"✍️",n:"Cycle Summary",d:"Write the story of these nine years"},{i:"🌱",n:"Seed Visioning",d:"Plant clear intentions for the next cycle"}]
  }
};
