/**
 * @fileOverview Verbatim Personal Year oracles from your chunks.
 */
export const YD: Record<number, any> = {
  1: {
    title: "Year of Origins", sub: "Year of Origins", planet: "☉ Sun / Surya", phase: "Spring Equinox — Seed Planting", chakra: "Manipura (Solar Plexus)",
    overview: `Personal Year 1 is the cycle's threshold — the numerological monad, divine unity preceding multiplicity. In Pythagorean philosophy, 1 is the point without dimension that contains all dimensional possibility. In living experience: a year of heightened initiative, self-definition, and pioneering action. The transition from Year 9's completion creates a complete identity shedding — both the external presentation others perceive and the internal self-concept that has defined you through the previous cycle. This year carries the strongest energy for breaking old habits and establishing new trajectories. Numerological tradition consistently identifies Year 1 as "the most powerful year for adjustment" — when the cycle's momentum genuinely supports departures from established patterns. The seed choices of Year 1 carry the genetic blueprint of the entire next nine-year arc: what is initiated now determines what will flower, be harvested, and be released through Years 2 through 9.`,
    pyth: `Year 1's shadow emerges from its greatest strength. The self-focus enabling clear direction can become self-absorption that alienates potential collaborators precisely when you need them most. The courage to act independently may manifest as impulsivity — moving before adequate information, consultation, or preparation exists. The excitement of new beginnings may mask the unprocessed grief of what Year 9 completed: genuine endings require genuine mourning, and those who skip this processing carry unresolved loss into Year 1's initiatives.`,
    vedic: `Governed by Surya — the Sun, source of light, life, and conscious will in Vedic cosmology. Surya's influence activates the Manipura chakra (solar plexus), center of personal power, metabolic fire, and the will to manifest. Physical vitality increases, supporting the ambitious undertakings Year 1 calls for. Surya's domain includes professional identity, positions of public responsibility, and recognition.`,
    chinese: `Maps to the Lo Shu square's North position — Water element, Kan trigram (The Abysmal). Water in Year 1 paradoxically complements the year's initiating energy: effective initiation requires the Water qualities of depth, adaptability, and accurate reading of conditions, not merely the assertion of will. The most powerful Year 1 actions arise from genuine understanding of current conditions rather than willful imposition of predetermined agendas.`,
    chald: `The 10/1 compound (Wheel of Fortune) carries karmic momentum — past cycle actions create this year's opportunities. The Wheel has turned in your favor; timing factors are particularly supportive. 19/1 (Sun, carrying karmic complexity) indicates patterns from previous cycles of misused power creating present requirement for genuine ego purification.`,
    pr: [{ i: "🌅", n: "Solar Meditation", d: "Sunrise practice facing east, breathing gold light into solar plexus" }, { i: "🙏", n: "Surya Namaskar", d: "12-round sun salutation cycle, embodying forward movement" }, { i: "🎯", n: "Vision Architecture", d: "Nine-year arc visualization; commit to 1–3 core initiatives only" }, { i: "⚡", n: "Yang Qigong", d: "Rising energy cultivation through morning movement practice" }]
  },
  2: {
    title: "Partnership & Patience", sub: "Partnership & Patience", planet: "☽ Moon / Chandra", phase: "Late Spring — Germination", chakra: "Swadhisthana (Sacral)",
    overview: `Personal Year 2 introduces the dyad — polarity, the generative tension between self and other that makes development possible. This year's energy shifts dramatically from Year 1's initiating yang to cultivating yin: patience replaces urgency, cooperation supersedes competition, and emotional intelligence becomes more valuable than decisive action. Following Year 1's planting, Year 2 is late spring's germination phase — when the seed coat breaks and both root and shoot emerge in opposite directions simultaneously.`,
    pyth: `Year 2's challenges emerge from receptive quality taken to excess. Indecision results when multiple perspectives seem equally valid — when no option clearly dominates, when the desire to preserve all relationship possibilities prevents any commitment. The year's characteristic slowed pace can become paralysis, with important decisions deferred indefinitely in the name of "not being ready."`,
    vedic: `Assigned to Chandra — the Moon, governor of mind, emotion, memory, and cyclical fluctuation. Chandra's influence activates the Swadhisthana chakra (sacral center), seat of creativity, sexuality, and emotional flow. Mental states become more variable, with mood cycles more pronounced, dream life more vivid, and the emotional body more accessible to both genuine depth and reactive disturbance.`,
    chinese: `Occupies the Lo Shu's Southwest — the most yin position, associated with Kun (Earth, pure yin), pure receptivity, devotion, and the Earth's nurturing capacity. Kun comprises six broken yin lines — the perfect complement to Year 1's Qian. Its counsel: "The receptive brings about sublime success, furthering through the perseverance of a mare."`,
    chald: `The 11/2 compound introduces master number intensity — the Illumination frequency amplifying Year 2's intuitive capacity toward potentially psychic levels while adding the challenge of nervous system hypersensitivity. 20/2 compound carries the Judgment archetype: spiritual awakening energy, the revelation of what has been hidden.`,
    pr: [{ i: "🌙", n: "Moon Salutations", d: "Evening Chandra Namaskar practice, attuning to lunar rhythms" }, { i: "👂", n: "Deep Listening", d: "Daily practice of listening without formulating response" }, { i: "💧", n: "Dream Journaling", d: "Morning recording of dream imagery and emotional tone" }, { i: "🤝", n: "Partnership Audit", d: "Honest inventory of all collaborative relationships' health and reciprocity" }]
  },
  3: {
    title: "Year of Expression", sub: "Year of Expression", planet: "♃ Jupiter / Guru", phase: "Early Summer — Blossoming", chakra: "Vishuddha (Throat)",
    overview: `Personal Year 3 completes the spring triad with blossoming — the visible expression of two years of invisible cultivation. What was planted in Year 1 and nurtured through Year 2's receptive patience now breaks into visible bloom. This year's energy is expansive, joyful, and creatively fertile in ways that feel almost effortless after Year 2's careful germination work. Jupiter governs Year 3 — the great benefic, Guru of the gods, lord of wisdom and creative progeny.`,
    pyth: `Year 3's shadow is superficiality and creative scattering. Jupiter's expansiveness without discipline produces creative excess — too many ideas pursued too shallowly, too many social obligations accepted beyond available capacity, too much optimism about realistic timelines. Gossip, social performance, and the constant stimulation of an expanded social world can consume the year's creative energy.`,
    vedic: `Jupiter (Guru, Brihaspati) governs Year 3, activating education, wisdom transmission, creative legacy, and the expansion of philosophical understanding. Life areas activated: higher education and teaching, publishing and broadcasting, international travel and philosophical inquiry, children and students, and creative projects of lasting significance.`,
    chinese: `Year 3 maps to the East — Wood element, Zhen trigram (The Arousing). Zhen's image is thunder awakening the earth after winter's silence: the sudden, irresistible emergence of growth energy that has been building invisibly through Years 1 and 2. This is precisely Year 3's quality — the creative jolt that disturbs comfortable stasis into genuine aliveness.`,
    chald: `The 21/3 (Crown of the Magi) is considered the most auspicious compound number in Year 3's expression — promising victory through creative effort and representing the individual whose authentic vision ultimately succeeds despite obstacles. 12/3 presents the challenge of premature expression.`,
    pr: [{ i: "🎨", n: "Daily Creation", d: "15 minutes of uncensored creative expression every morning" }, { i: "🗣", n: "Throat Mantra", d: "Ham seed mantra vibration practice for Vishuddha activation" }, { i: "📖", n: "Jupiter Journaling", d: "Evening gratitude extraction and wisdom documentation from each day" }, { i: "🌱", n: "East Activation", d: "Feng shui Wood element placement in the Eastern sector" }]
  },
  4: {
    title: "Year of Foundation", sub: "Year of Foundation", planet: "☊ Rahu (North Node)", phase: "Midsummer — Fruit-Setting", chakra: "Muladhara (Root)",
    overview: `Personal Year 4 corresponds to midsummer's demanding conditions — fruit-setting under sustained heat, when systems must support growth and foundations are tested by pressure. This year's energy is structural, disciplined, and methodical. The individual faces the practical requirements of manifesting visions developed in Years 1-3: financial management, organizational development, skill acquisition, and the unglamorous consistency that turns possibilities into realities. In Vedic numerology, Year 4 is uniquely governed by Rahu — the North Node of the Moon.`,
    pyth: `Year 4's primary danger is conflating busyness with productivity. Rahu's compulsive energy produces workaholism — exhausting effort that fills the calendar while missing the actual foundation-building the year requires. The appearance of disciplined hard work can mask the avoidance of the specific, difficult structural work that the year actually calls for.`,
    vedic: `Rahu's governance makes Year 4 simultaneously the cycle's most materially productive and spiritually complex year. Rahu amplifies desire for material security while ensuring that no material acquisition fully satisfies — each achieved security creates the hunger for greater security, pointing the seeker beyond matter to the source of genuine stability.`,
    chinese: `Year 4 occupies the Lo Shu's Southeast — Xun trigram (Gentle Wind, Wood element), associated with wealth accumulation and the patient growth of trees. The tree's wealth builds through root-deepening entirely invisible from the surface — an encouraging and sobering metaphor for Year 4's work: the most important structural building is the work that produces no visible result during the year itself.`,
    chald: `The 13/4 (Regeneration) carries Year 4's most significant karmic weight: transformation that comes through structural collapse rather than linear building. What falls in a 13/4 year must fall — fighting the collapse prolongs suffering without preventing the eventual clearing. 22/4 master number year is Year 4's highest octave: the Master Builder.`,
    pr: [{ i: "🌍", n: "Grounding Practice", d: "Daily barefoot earth contact; root chakra meditation before work" }, { i: "📊", n: "Financial Architecture", d: "Build one solid financial system: budget, savings automation, debt plan" }, { i: "🏋️", n: "Physical Discipline", d: "Non-negotiable daily health routine; consistency over intensity always" }, { i: "🔧", n: "Skill Mastery", d: "One technical skill pursued to genuine competence through this year" }]
  },
  5: {
    title: "Year of Liberation", sub: "Year of Liberation", planet: "☿ Mercury / Budha", phase: "Late Summer — Harvest Preparation", chakra: "Anahata (Heart)",
    overview: `Personal Year 5 introduces late summer's variability — harvest approaches but weather remains unpredictable, demanding adaptability above all else. After Year 4's intensive foundation-building, the completed structures now create the platform from which Year 5 launches into genuine freedom of movement. The individual experiences restlessness with established patterns, seeking new experiences, locations, relationships, and ways of understanding the world. Mercury governs Year 5 — quicksilver lord of commerce, communication, adaptability, and the nervous system.`,
    pyth: `Year 5's shadow is instability mistaken for freedom. The compulsive change-seeker who abandons Year 4's foundations at the first sign of restlessness — job-changing without developing expertise, relationship-abandoning without developing intimacy, country-hopping without developing genuine depth — confuses the freedom to leave with the freedom to arrive somewhere meaningful.`,
    vedic: `Mercury (Budha) governs Year 5, activating commerce, communication, adaptability, and the nervous system's capacity for rapid information processing. Life areas: short travel and siblings, commerce and negotiation, communication media and technology, education and skill development, health, and all forms of information exchange and synthesis.`,
    chinese: `Year 5 occupies the Lo Shu's central position — no fixed direction, no fixed element, partaking of all and governing none. This central position creates Year 5's paradox: simultaneously the most pivotal year in the cycle and the most volatile, the year of maximum potential and maximum unpredictability. The center of the Lo Shu square is the point from which all directions radiate.`,
    chald: `The 14/5 (inconstancy) carries the specific warning of brilliant starts that lack follow-through — freedom used as escape from the responsibility of genuine completion. The 23/5 (Royal Star of the Lion) is Chaldean Year 5's most fortunate compound — promising success through adaptability and charm.`,
    pr: [{ i: "✈️", n: "Intentional Adventure", d: "Plan one meaningful journey beyond your established comfort zone" }, { i: "🧘", n: "Pranayama", d: "Daily breathwork for nervous system regulation, integration, and clarity" }, { i: "📚", n: "Edge Learning", d: "Study one discipline completely outside your established expertise" }, { i: "💚", n: "Heart Opening", d: "Anahata practices: loving-kindness meditation, heart coherence breathing" }]
  },
  6: {
    title: "Year of Harmony", sub: "Year of Harmony", planet: "♀ Venus / Shukra", phase: "Early Autumn — Abundance Sharing", chakra: "Anahata (Heart — Venus aspect)",
    overview: `Personal Year 6 distributes summer's abundance — harvest shared, responsibilities embraced, harmony restored after Year 5's winds of change. This year's energy is nurturing, service-oriented, and relationally focused in ways that feel both deeply fulfilling and potentially overwhelming. Family matters, domestic concerns, and community involvement come to prominence with unusual intensity. Venus governs Year 6 — the great feminine benefic, goddess of beauty, love, aesthetics, financial partnership, and the arts.`,
    pyth: `Year 6's shadow is the martyr pattern — the compulsive over-giver who uses service to avoid their own needs, who defines worth through others' approval, who creates dependency through excessive caretaking rather than genuine empowerment. Venus's shadow is possessive love: love that hoards rather than liberates, that gives in order to bind rather than to set free.`,
    vedic: `Venus (Shukra, Lakshmi's planetary representative) governs Year 6, activating marriage and committed partnership, aesthetic expression and creative arts, financial partnership, luxury goods and beauty industries, and the reproductive system. Well-placed Venus produces extraordinary Year 6 bounty: beauty, love, artistic achievement, and the grace of financial abundance.`,
    chinese: `Year 6 maps to the Northwest — Qian trigram (Heaven, pure yang, Metal element), associated with helpful people, mentors, and heaven's support. Qian in the Northwest means Year 6 activates the highest quality external support: mentors appearing with precisely needed guidance, institutional backing arriving for worthy initiatives.`,
    chald: `The 15/6 (Magician) represents Year 6's most auspicious compound in Chaldean practice — the unusual capacity to attract both material support and protective spiritual forces. The 24/6 (long-term love) emphasizes Year 6's deepest relationship gift: partnerships and commitments with unusual staying power.`,
    pr: [{ i: "💐", n: "Venus Ritual", d: "Friday evening beauty ritual honoring what you genuinely love and serve" }, { i: "🏠", n: "Home Sanctuary", d: "Beautify your living space as a conscious offering to all who inhabit it" }, { i: "🎭", n: "Creative Service", d: "Offer your specific creative gift in service of a genuine community need" }, { i: "⚖️", n: "Service Audit", d: "Are you giving freely from abundance or from obligation? Recalibrate honestly." }]
  },
  7: {
    title: "Year of the Mystic", sub: "Year of the Mystic", planet: "☋ Ketu (South Node)", phase: "Mid-Autumn — Inward Turning", chakra: "Ajna (Third Eye)",
    overview: `Personal Year 7 corresponds to mid-autumn's introspective quality — days shortening, attention withdrawing from external achievement to internal processing. This year's energy is analytical, mystical, and solitude-seeking with an urgency that cannot be socially medicated away. The individual experiences a genuine, non-negotiable need for study, reflection, and spiritual deepening. Ketu governs Year 7 — the South Node of the Moon, the planet of liberation and detachment.`,
    pyth: `The practical challenge of Year 7 is its invisibility: most of the year's important work occurs internally and produces no immediately measurable external output. Family members, employers, and social networks may perceive the Year 7 individual as withdrawn, unproductive, or depressed when they are engaged in the most sophisticated developmental work of the entire cycle.`,
    vedic: `Ketu's governance makes Year 7 the most spiritually distinctive year in the nine-year cycle. Ketu represents accumulated spiritual merit and its specific demands — the wisdom mastered in previous incarnations that now seeks expression, and the karmic patterns from previous cycles that seek final release.`,
    chinese: `Year 7 maps to the West — Dui trigram (Joyous Lake, Metal element), associated with completion, joy, and the harvest of inner refinement. Metal element in the West represents refinement, reduction to essence, the cutting away of all that is extraneous to reveal the pure inner form that has been there all along.`,
    chald: `The Chaldean tradition views Year 7 with unusual reverence. 16/7 (Shattered Citadel) indicates that structures built for security — material, social, psychological — may be dismantled. Those who have built on genuine values experience this as liberation; those who have built on fear experience it as loss.`,
    pr: [{ i: "🔮", n: "Meditation Intensive", d: "Establish daily 20+ minute sit; explore one lineage with genuine depth" }, { i: "📜", n: "Deep Study", d: "One area of profound intellectual or spiritual inquiry, pursued to genuine depth" }, { i: "🌌", n: "Ajna Activation", d: "Third eye practices: trataka flame gazing, inner light meditation, active dreamwork" }, { i: "🌿", n: "Radical Simplification", d: "Remove what is genuinely inessential from environment, schedule, and mind" }]
  },
  8: {
    title: "Year of Power", sub: "Year of Power", planet: "♄ Saturn / Shani", phase: "Late Autumn — Final Harvest", chakra: "Manipura (Solar Plexus — Saturn)",
    overview: `Personal Year 8 concentrates autumn's final productive energy — the last harvest, careful accounting, and preparation for winter. This year's energy is powerful, materially focused, and karmically active in ways that feel more fated than any other year in the cycle. The individual faces both opportunities for significant achievement and consequences for prior choices. Saturn governs Year 8 — the great disciplinarian, lord of karma, time, and authority.`,
    pyth: `Year 8's challenges are proportional to the gap between self-perception and genuine achievement. Saturn reveals this gap with clinical precision that feels neither cruel nor kind but simply accurate. Those who have been performing competence rather than developing it encounter exposure that is ultimately redemptive — the invitation to build authentically.`,
    vedic: `Saturn (Shani) governs Year 8, activating career authority and peak professional expression, karmic accounting for choices made throughout the cycle, and the harvest — positive or corrective — of genuine effort versus performed effort. Saturn's natal placement determines whether Year 8 brings deserved harvest or corrective accounting.`,
    chinese: `Year 8 maps to the Northeast — Gen trigram (Keeping Still, Earth element), associated with knowledge, self-cultivation, and the mountain's inherent authority. The mountain commands not by assertion but by virtue of what it genuinely is — the most profound teaching about Year 8's authority.`,
    chald: `The 17/8 (Star of the Magi) is Year 8's most powerful compound expression — material success accompanied by genuine spiritual authority, harvest that includes wisdom as well as wealth. The 26/8 brings success alongside significant weight of responsibility for others' wellbeing.`,
    pr: [{ i: "📋", n: "Karmic Accounting", d: "Honest inventory of what you've genuinely built; consciously release illusions" }, { i: "🏆", n: "Authority Claim", d: "Apply for, seek, or consciously accept the leadership role you've genuinely earned" }, { i: "🕰️", n: "Saturn Discipline", d: "Establish one non-negotiable daily practice and honor it with complete consistency" }, { i: "🌾", n: "Harvest Gratitude", d: "Ritually acknowledge every genuine fruit of the preceding seven years" }]
  },
  9: {
    title: "Year of Completion", sub: "Year of Completion", planet: "♂ Mars / Mangal", phase: "Winter Solstice — Seed Return", chakra: "Muladhara (Root — Mars completion)",
    overview: `Personal Year 9 completes the cycle with winter's approach — release, completion, and the preparation for renewal that is simultaneously an ending and the most profound beginning available. The individual experiences necessary endings: projects completing their purpose, outgrown patterns dissolving to make room for what genuinely serves the next cycle. Grief and gratitude intermingle as the cycle's full harvest is integrated.`,
    pyth: `Year 9's challenges center on the grief of completion and the terror of the unknown that follows. Clinging to what is completing — to relationships, projects, identities, and life stages whose time is genuinely over — prevents the completion that would allow genuine renewal. The cycle cannot begin anew until Year 9's endings are fully honored.`,
    vedic: `Mars (Mangal, Kartikeya) governs Year 9, bringing warrior energy to completion and the specific courage required to release what has genuinely served its purpose. Life areas activated: completion and conscious release across all domains, travel to places of personal significance, and direct confrontation with what has been avoided.`,
    chinese: `Year 9 maps to the South — Li trigram (The Clinging, Fire element), associated with fame, recognition, clarity, and illumination. Fire in Year 9 represents the cycle's final brilliant flaring before the energy returns to the earth that will seed the next cycle. Li's image is the flame that simultaneously illuminates and consumes.`,
    chald: `Nine's sacred status in Chaldean numerology gives Year 9 metaphysical weight that no other year carries. Chaldean tradition views Year 9 as the year when the individual most closely touches the divine intelligence governing the entire cycle. The 18/9 indicates significant confrontation and final reckoning.`,
    pr: [{ i: "🕯️", n: "Completion Ritual", d: "Ceremonially close each significant chapter with genuine gratitude and release" }, { i: "🌊", n: "Grief Honoring", d: "Allow and fully witness the natural grief of genuine ending without bypassing" }, { i: "✍️", n: "Cycle Summary", d: "Write the story of these nine years: what was planted, built, harvested, released" }, { i: "🌱", n: "Seed Visioning", d: "What genuinely wants to be born in the next Year 1? Plant it as clear intention." }]
  }
};
