/**
 * @fileOverview Verbatim Pinnacle and Challenge definitions from Chunk 08.
 */
export const PINNACLE_DESC: Record<number, string> = {
  0: 'The Zero Pinnacle is the rarest and most demanding — a call to complete mastery of all nine vibrations simultaneously. No single quality dominates; every situation requires perfect discernment about which energy is needed. The gift is extraordinary adaptability; the challenge is finding solid ground without a fixed orientation.',
  1: 'The First Pinnacle emphasises individuation and self-definition. This long arc of life asks: who are you, independent of family and collective expectation? Career independence, entrepreneurial initiative, and the courage to lead authentically are this pinnacle\'s recurring themes.',
  2: 'The Second Pinnacle deepens emotional intelligence, diplomatic skill, and the capacity for genuine partnership. Relationships — romantic, professional, communal — are the primary classroom. The lesson: genuine cooperation requires genuine self-knowledge, not self-erasure.',
  3: 'The Third Pinnacle expands creative expression, communication, and joyful engagement with life\'s abundance. This is often a creatively fertile period where artistic, communicative, and social gifts reach their highest expression. The shadow: scattering gifts across too many surfaces.',
  4: 'The Fourth Pinnacle builds foundations — career structure, financial systems, health discipline, and practical competence. Hard work is not merely required but specifically rewarded during this arc. The invitation: trust the process of methodical building, even when results are slow to appear.',
  5: 'The Fifth Pinnacle brings freedom, change, and the expansion of experience. Travel, diverse relationships, varied careers, and the fullness of sensory engagement characterise this arc. The lesson: freedom with integrity — liberation that serves genuine development rather than mere escape.',
  6: 'The Sixth Pinnacle centres on responsibility, service, and the creation of beauty in all its forms — home, family, creative work, community. The deepest call is to love maturely: generously and with clear-eyed realism about both others\' needs and one\'s own limits.',
  7: 'The Seventh Pinnacle turns attention inward — toward study, spiritual development, philosophical inquiry, and the direct encounter with what lies beneath surface experience. Solitude, specialisation, and depth of understanding characterise this arc\'s most fruitful expression.',
  8: 'The Eighth Pinnacle activates material mastery, executive authority, and the harvest of genuine competence. Financial achievement, career authority, and the assumption of significant responsibility are this pinnacle\'s signature expressions. Saturn\'s precision: rewards flow precisely to genuine effort, never to performance.',
  9: 'The Ninth Pinnacle completes a major life chapter through service, creative synthesis, and the integration of accumulated wisdom. Universal compassion, humanitarian contribution, and the graceful release of what has been built characterise this arc\'s highest expression.'
};

export const CHALLENGE_DESC: Record<number, string> = {
  0: 'The Zero Challenge — the Master Test — asks for complete mastery of all vibrations. No single quality is specifically lacking; every quality must be consciously developed and balanced. This is simultaneously the most open and the most demanding challenge number.',
  1: 'The Challenge of 1 asks for the development of genuine self-assertion, independent thinking, and appropriate leadership. The pattern being overcome: excessive dependency on others\' approval, fear of standing out, or conversely, domineering assertion that masks underlying insecurity.',
  2: 'The Challenge of 2 addresses over-sensitivity, excessive compliance, and difficulty maintaining boundaries in relationship. The lesson: genuine cooperation requires clear self-knowledge. Hypersensitivity to criticism and the compulsive need for approval are the specific patterns to develop through.',
  3: 'The Challenge of 3 invites the development of authentic self-expression and creative confidence. The pattern: self-criticism that suppresses expression before it reaches others, or conversely, superficial social performance that substitutes for genuine creative depth.',
  4: 'The Challenge of 4 asks for the development of practical discipline, organisational capacity, and willingness to work systematically toward long-term goals. The shadow: resistance to effort, tendency to abandon foundations before completion, or excessive rigidity in established methods.',
  5: 'The Challenge of 5 addresses excessive freedom-seeking, irresponsibility, or sensory over-indulgence. The lesson: genuine freedom is earned through the discipline of completing what has been begun and honouring commitments even when the horizon calls.',
  6: 'The Challenge of 6 invites the development of genuine service that comes from abundance rather than obligation, beauty-creation without perfectionist paralysis, and family responsibility that doesn\'t consume individual identity.',
  7: 'The Challenge of 7 asks for the development of genuine trust — in intuition, in life\'s intelligence, and in the willingness to rest in not-knowing. The pattern: either excessive scepticism that prevents genuine depth, or naive credulity that substitutes spiritual bypassing for genuine development.',
  8: 'The Challenge of 8 addresses the relationship with power, money, and authority. The lesson: material resources and authority are tools for genuine service, not measures of intrinsic worth. Both excessive materialism and chronic financial self-sabotage are this challenge\'s shadow expressions.',
  9: 'The Challenge of 9 invites the development of genuine compassion without martyrdom, completion without clinging, and service without the unconscious demand for recognition. The pattern: either cold detachment masking as philosophical non-attachment, or compulsive giving that depletes the giver.'
};
